### PR TITLE
fix: Send event startsAt and endsAt time in event timezone

### LINKED ISSUE #3632: Send event timing in event timezone to server
**Describe the bug**
Make frontend send event timings in event timezone and render time correctly on the event basic details page.

**Additional context**
Look https://github.com/fossasia/open-event-frontend/issues/3582 for more details.

### PR DESCRIPTION
**Pull request by prateekj117**
Fixes #3632 

#### Short description of what this resolves:
Send event timings in event timezone and render time correctly on event basic details page.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by prateekj117** [comment]
@iamareebjamal Please review.

File: app/utils/computed-helpers.js [hunk 1]
```diff
@@ -47,13 +47,13 @@ export const computedSegmentedLink = function(property) {
 export const computedDateTimeSplit = function(property, segmentFormat, endProperty) {
   return computed(property, {
     get() {
-      return moment(this.get(property)).format(getFormat(segmentFormat));
+      return moment(this.get(property)).tz(this.timezone).format(getFormat(segmentFormat));
```
Comment (iamareebjamal) [inline app/utils/computed-helpers.js]: Will fail for everything except event

Comment (kushthedude) [reply app/utils/computed-helpers.js]: @prateekj117 Dont send the timezone with time, as we are already collecting timezone in seperate field. I dont think sending timezone with date & time would be mandatory.

Comment (iamareebjamal) [reply app/utils/computed-helpers.js]: It is mandatory. As I said, please read about moment and timezones and ISO 8601 format a bit more

Comment (kushthedude) [reply app/utils/computed-helpers.js]: @iamareebjamal So adding a if conditional should work in that case here.

Comment (iamareebjamal) [reply app/utils/computed-helpers.js]: Yes

**Comment by iamareebjamal** [comment]
@prateekj117 Status?

**Comment by prateekj117** [comment]
@iamareebjamal I am having an issue in case of `startsAt` and `endsAt` time in speakers and sessions. The page crashes when I try `this.event.timezone` in case of session and speakers.

**Comment by iamareebjamal** [comment]
Just handle the case for event wizard right now and open an issue to handle others

**Comment by kushthedude** [comment]
Use a if condition just to handle the event case, session and speaker can
be handled after the release.

**Comment by prateekj117** [comment]
@iamareebjamal Please review.

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/utils/computed-helpers.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/open-event-frontend/open-event-frontend/pullRequest?prid=4512036&bid=15203352)

File: app/utils/computed-helpers.js [hunk 2]
```diff
@@ -47,13 +47,24 @@ export const computedSegmentedLink = function(property) {
 export const computedDateTimeSplit = function(property, segmentFormat, endProperty) {
   return computed(property, {
     get() {
-      return moment(this.get(property)).tz(this.timezone).format(getFormat(segmentFormat));
+      if (this.constructor.toString() === 'model:event') {
```
Comment (iamareebjamal) [inline app/utils/computed-helpers.js]: Wrong way. Use this.type

File: app/utils/computed-helpers.js [hunk 3]
```diff
@@ -47,13 +47,24 @@ export const computedSegmentedLink = function(property) {
...
+        return moment(this.get(property)).tz(this.timezone).format(getFormat(segmentFormat));
+      } else {
+        return moment(this.get(property)).format(getFormat(segmentFormat));
```
Comment (iamareebjamal) [inline app/utils/computed-helpers.js]: Code duplication

**Comment by prateekj117** [comment]
@iamareebjamal Please review.

File: app/utils/computed-helpers.js [hunk 4]
```diff
@@ -47,24 +47,31 @@ export const computedSegmentedLink = function(property) {
...
   return computed(property, {
     get() {
-      if (this.constructor.toString() === 'model:event') {
-        return moment(this.get(property)).tz(this.timezone).format(getFormat(segmentFormat));
+      let timezone = '';
+      if (this.constructor.modelName === 'event') {
+        timezone = this.timezone;
       } else {
-        return moment(this.get(property)).format(getFormat(segmentFormat));
+        timezone = this.event.get('timezone');
```
Comment (iamareebjamal) [inline app/utils/computed-helpers.js]: This is worse than before

Comment (iamareebjamal) [reply app/utils/computed-helpers.js]: Idea is to write less code, not more

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/utils/computed-helpers.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/open-event-frontend/open-event-frontend/pullRequest?prid=4512036&bid=15203352)

File: app/utils/computed-helpers.js (hunk 4 above)
Comment (iamareebjamal) [reply app/utils/computed-helpers.js]: So, make this work in least code possible, please

Comment (prateekj117) [reply app/utils/computed-helpers.js]: I don't want to assign a variable outside if as it may crash the page of the other model inside an if condition.
For example:
```
let timezone = this.timezone;
if(this.constuctor.modelName !== 'event') {
	timezone = this.event.get('timezone');
}
```
This may break in session-speakers page, as it will first search for this.timezone.

**Comment by iamareebjamal** [comment]
Normally, I'd wait for you to figure out this so you learn and develop an insight of how to write concise code and not duplicate anything, but since this PR has already delayed the release a lot, this is what you should do:

```js
    let momentDate = moment(this.get(property));
    if (this.constructor.modelName === 'event')
        momentDate = momentDate.tz(this.timezone)
    return momentDate.format(getFormat(segmentFormat));
```

File: app/utils/computed-helpers.js (hunk 4 above)
Comment (prateekj117) [reply app/utils/computed-helpers.js]: I don't want to assign a variable outside if as it may crash the page of the other model inside an if condition.
For example:
```
let timezone = this.timezone;
if(this.constuctor.modelName !== 'event') {
	timezone = this.event.get('timezone');
}
```
This may break in session-speakers page, as it will first search for this.timezone.

**Comment by iamareebjamal** [comment]
And as said previously, only handle event case as we don't know the effects of changing behaviours of sessions and tracks. And we don't have devs and time to test it out. They are not immediate bugs and fixing them may break the site even more. As discussed, they are planned for next release. Perfection is the killer of pragmatism

File: app/utils/computed-helpers.js [hunk 5]
```diff
@@ -47,13 +47,31 @@ export const computedSegmentedLink = function(property) {
...
       let oldDate = newDate;
       if (this.get(property)) {
-        oldDate = moment(this.get(property), segmentFormat === 'date' ? FORM_DATE_FORMAT : FORM_TIME_FORMAT);
+        timezone = '';
+        if (this.constructor.modelName === 'event') {
+          timezone = this.timezone;
+        } else {
+          timezone = this.event.get('timezone');
+        }
+        oldDate = moment(this.get(property), segmentFormat === 'date' ? FORM_DATE_FORMAT : FORM_TIME_FORMAT).tz(timezone, true);
```
Comment (iamareebjamal) [inline app/utils/computed-helpers.js]: Somehow you managed to increase the duplication even more from previous iteration

File: app/utils/computed-helpers.js [hunk 6]
```diff
@@ -47,13 +47,31 @@ export const computedSegmentedLink = function(property) {
...
+      let newDate = moment(value, getFormat(segmentFormat)).tz(timezone, true);
       let oldDate = newDate;
       if (this.get(property)) {
-        oldDate = moment(this.get(property), segmentFormat === 'date' ? FORM_DATE_FORMAT : FORM_TIME_FORMAT);
+        timezone = '';
+        if (this.constructor.modelName === 'event') {
+          timezone = this.timezone;
+        } else {
+          timezone = this.event.get('timezone');
+        }
```
Comment (iamareebjamal) [inline app/utils/computed-helpers.js]: I don't even understand why this block of code is repeated here in this if statement.

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/utils/computed-helpers.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/open-event-frontend/open-event-frontend/pullRequest?prid=4512036&bid=15203352)

**Comment by prateekj117** [comment]
@iamareebjamal Please review.

**Comment by kushthedude** [comment]
@prateekj117 Are you sure the time is being sent into event timezone after this ?

**Comment by kushthedude** [comment]
I tried it and time was stored in my browser timezone only .

**Comment by iamareebjamal** [comment]
Yes, I tested it personally

**Comment by iamareebjamal** [comment]
> time was stored in my browser timezone only

How did you test that?

**Comment by kushthedude** [comment]
I pulled the changes and created new event and accessed the database to see
the time.

**Comment by iamareebjamal** [comment]
And what did you find? Please tell completely. What you did, which timezone you selected, what time did you input and what did you find in DB, and what you expected to find in the DB instead.

Steps of Reproduction, Expected, Actual.

**Comment by kushthedude** [comment]
Its working fine, I checked the time for older event.
Sorry for the confusion.
