### PR TITLE
fix: public url under admin groups list

### LINKED ISSUE #7851: Groups admin page: Public URL fields display link to private edit URL
The public URL field shows and links to the private URLs to edit the events of a group. Expected: Link to the public group URL.

Compare https://eventyay.com/admin/groups/live (This page is only accessible for admins. In order to view this page please set up the system on your local machine and access the respective slug there)
Screenshot from 2021-09-24 06-28-57

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #7851

### CODE REVIEW

**Review by daretobedifferent18 — CHANGES_REQUESTED** [review]
Please fix the indentation

**Comment by progmatic-99** [comment]
double quotes should be changed to single quotes, too??

**Comment by pc-beast** [comment]
> double quotes should be changed to single quotes, too??

Yes

File: app/models/group.js [hunk 1]
```diff
@@ -29,8 +27,9 @@ export default class Group extends ModelBase.extend({
   followers     : hasMany('user-follow-group'),
 
   url: computed('identifier', function() {
-    const origin = this.fastboot.isFastBoot ? `${this.fastboot.request.protocol}//${this.fastboot.request.host}` : location.origin;
-    return origin + this.router.urlFor('groups.edit.events', this.id);
+    const origin = this.fastboot.isFastBoot
+      ? `${this.fastboot.request.protocol}//${this.fastboot.request.host}`
+      : location.origin;
+    return origin + `/g/${this.id}`;
```
Comment (daretobedifferent18) [inline app/models/group.js:33]: @progmatic-99 
What I see is that only this line is been modified in this PR. Pls revert other indent changes back to normal.
and pls disable any auto-format extention that might have installed in your code-editor to avoid this small indent issues.

**Review by daretobedifferent18 — CHANGES_REQUESTED** [review]

File: app/models/group.js (hunk 1 above)
Comment (progmatic-99) [reply app/models/group.js:33]: This is more readable. I will change other things.

**Review by mariobehling — APPROVED** [review]
