### PR TITLE
Filter speakers list according to session's state

### LINKED ISSUE #1287: Speakers not getting filtered as per the session state in the list of Speakers
**Describe the bug**
In the route /events/{event_identifier}/speakers where the speakers are listed when you press accepted pending buttons the same list of speakers appear.

**To Reproduce**
1. Go to  /events/{event_identifier}/speakers
2. Go to ' /events/{event_identifier}/speakers/pending' or ' /events/{event_identifier}/speakers/accepted'
3. The same list of speakers appear.

**Expected behavior**
The speakers should be filtered according to the state of the session.

**Screenshots**
 
image

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium

### PR DESCRIPTION
**Pull request by ritikamotwani**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
The list of the speakers was not getting filtered. The list would appear same for all tabs like pending, accepted.

#### Changes proposed in this pull request:

- The filtering function is added to the list of speakers

Fixes #1287

### CODE REVIEW

File: app/routes/events/view/speakers/list.js [hunk 1]
```diff
@@ -11,39 +11,55 @@ export default Route.extend({
         return this.get('l10n').t('Rejected');
     }
   },
-  model(params) {
+  async model(params) {
```
Comment (mayank8318) [inline app/routes/events/view/speakers/list.js]: Why is `async` required here?

Comment (ritikamotwani) [reply app/routes/events/view/speakers/list.js]: @mayank8318 I thought to filter on the basis of a related model async might be required but it's not so. Please review now. :sweat_smile:
