### PR TITLE
Fix bugs with speaker details and add edit route for cfs

### LINKED ISSUE #1381: Fix the errors with the add speaker and edit speaker buttons in cfs modal
**Describe the bug**

- Even if the user who is currently logged in has not entered himself as a speaker(for an event with cfs open) and has entered someone else at some other time as a speaker whenever he clicks on `Submit Proposal`
image
He gets a button to edit speaker details instead of add speaker details.
- There is no route to edit speaker details. Whenever the button to edit speaker details appear in the cfs modal and it is clicked the user gets redirected to an edit speaker form of a random speaker created by the user.

**To Reproduce**
1. Go to e/{event_identifier}/cfs
2. Click on Submit Proposal
3. See error

**Expected behavior**

- Show add speaker button in the cfs modal until the logged in user is not present in the speakers list.
- If he is present in the list of speakers then show the edit speaker details.
- The add speaker button should redirect to a new form with the name and email of the speaker same as the user as it is in v1.
image
- The edit speaker button should redirect to a route where the info of the logged in  user previously saved appears in the form

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium

### PR DESCRIPTION
**Pull request by ritikamotwani**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixes all the bugs with the add and edit speaker details in cfs

#### Changes proposed in this pull request:

- Add speaker button comes in the cfs modal if the logged in user has not added himself as a speaker of that event.
- Edit speaker details button comes if he exists in the list of speakers.
- The route for add speaker contains a form with the name and email of the logged in user as in v1.
- The route for edit speaker contains a form with the previously saved information of that user.

Fixes #1381

### CODE REVIEW

**Comment by ritikamotwani** [comment]
@CosmicCoder96 @pradeepgangwar @srv-twry @mayank8318 please review.

File: app/components/modals/cfs-proposal-modal.js [hunk 1]
```diff
@@ -1,9 +1,14 @@
...
+import { computed } from '@ember/object';
 
 export default ModalBase.extend({
   actions: {
     toggleView() {
       this.set('isOpen', false);
     }
-  }
+  },
+  speakerNotExists : true,
```
Comment (CosmicCoder96) [inline app/components/modals/cfs-proposal-modal.js]: make this `speakerExists :  false`

File: app/components/modals/cfs-proposal-modal.js [hunk 2]
```diff
@@ -1,9 +1,14 @@
...
+  speakerExists    : computed(function() {
```
Comment (CosmicCoder96) [inline app/components/modals/cfs-proposal-modal.js]: what  is this? a computed function is not supposed to set other variables.

File: app/templates/components/modals/cfs-proposal-modal.hbs [hunk 3]
```diff
@@ -8,13 +8,25 @@
...
+    {{#if isNewSpeaker}}
+      {{#link-to 'public.cfs.new-speaker' class='ui teal button' invokeAction=(action 'toggleView')}}
         {{t 'Add Speaker Details'}}
-      {{else}}
-        {{t 'Edit Speaker Details'}}
+      {{/link-to}}
+    {{else}}
+      {{#each data.userSpeaker as |speaker|}}
+        {{#if (eq speaker.email data.user.email)}}
+          {{speakerExists}}
```
Comment (pradeepgangwar) [inline app/templates/components/modals/cfs-proposal-modal.hbs]: I think we should move this if condition logic to JS and use only one variable `speakerExists` for better readability.

Comment (CosmicCoder96) [reply app/templates/components/modals/cfs-proposal-modal.hbs]: the computed property you tried to use should be something like this:
```js
speakerExists: computed('speaker.email', 'data.user.email', function() {
//do comparisons here and return the result to the computed property
})
```

**Comment by ritikamotwani** [comment]
@CosmicCoder96 @pradeepgangwar please review.

File: app/templates/components/modals/cfs-proposal-modal.hbs [hunk 4]
```diff
@@ -8,13 +8,17 @@
...
+    {{#if isNewSpeaker}}
+      {{#link-to 'public.cfs.new-speaker' class='ui teal button' invokeAction=(action 'toggleView')}}
         {{t 'Add Speaker Details'}}
-      {{else}}
-        {{t 'Edit Speaker Details'}}
-      {{/if}}
-    {{/link-to}}
+      {{/link-to}}
+    {{else}}
+      {{#each data.userSpeaker as |speaker|}}
```
Comment (pradeepgangwar) [inline app/templates/components/modals/cfs-proposal-modal.hbs]: Is it possible to have more than one speaker here?

Comment (ritikamotwani) [reply app/templates/components/modals/cfs-proposal-modal.hbs]: @pradeepgangwar no, but the query written returns a list of speakers because of the word query. Writing queryRecord was giving an error,
