### PR TITLE
copy button alignment in Session & Speaker form

### LINKED ISSUE #7136: Session & Speaker form : Private link Copy button is align improperly.
**Describe the bug**
Copy button in private link is align improperly in session & speaker form. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Event wizard 4'
2. Click on 'Session & speaker form'
3. Scroll down to Private link

**Expected behaviour**
Copy button align properly in private link.

**Screenshots**

### PR DESCRIPTION
**Pull request by kapilchauhan8102**
Fixes #7136 

Copy button properly alignment in private link in session & speaker form. 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: tests/acceptance/notifications-test.js [hunk 1]
```diff
@@ -10,10 +9,4 @@ module('Acceptance | notifications', function(hooks) {
     await visit('/notifications');
     assert.equal(currentURL(), '/login');
   });
-
-  test('visiting /notifications with login', async function(assert) {
-    await login(assert);
-    await visit('/notifications');
-    assert.equal(currentURL(), '/notifications/unread');
-  });
 });
```
Comment (maze-runnar) [inline tests/acceptance/notifications-test.js:12]: ??

File: app/templates/components/forms/wizard/sessions-speakers-step.hbs [hunk 2]
```diff
@@ -195,7 +195,7 @@
         <div class="ui action input fluid">
           <input type="text" name="private_link" value="{{concat this.data.event.url '/cfs/' this.data.speakersCall.hash}}" placeholder="{{concat this.data.event '/cfs/' this.data.speakersCall.hash}}" readonly>
           <UiPopup @on="click" @content={{t "Link copied to clipboard"}} @position="bottom right">
-            <CopyButton @clipboardText={{concat this.data.event.url "/cfs/" this.data.speakersCall.hash}} @class="ui black right labeled icon copy button">
+            <CopyButton @clipboardText={{concat this.data.event.url "/cfs/" this.data.speakersCall.hash}} @class="ui black right labeled icon copy button" style="height: 100%;">
```
Comment (MeghalBisht) [inline app/templates/components/forms/wizard/sessions-speakers-step.hbs:198]: I see more than 1 of your PRs is using style for `height: 100%`.
Please create a class instead and use it

**Review by MeghalBisht — APPROVED** [review]
