### PR TITLE
fix: Show only scheduled days

### LINKED ISSUE #6092: Public Schedule: Only show days with sessions scheduled
For events that take place over several days please only show days that have sessions scheduled. Please take care that the scheduler used to put the sessions into the day used by the organizer is not changed.

e.g. compare https://eventyay.com/e/ae73f280/schedule

Screenshot from 2020-12-20 00-58-38

### PR DESCRIPTION
**Pull request by Creatoon**
Fixes #6092 

#### Short description of what this resolves:
Previously it was showing all the dates between starting and ending date.
for ex - i have created an event for 1 year and i only have 6 scheduled sessions, see what happens.

Screenshot_2021-01-06 Sessions js engines Open Event

And this is not ideal at all , but now with this pr only scheduled days will be shown , as i have said , i created only 6 sessions.

Screenshot from 2021-01-06 11-29-54

and after clicking a specific date.

Screenshot from 2021-01-06 11-30-06

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Creatoon** [comment]
@iamareebjamal sir please review.

File: app/controllers/public/sessions.js [hunk 1]
```diff
@@ -17,23 +17,21 @@ export default class SessionsController extends Controller {
...
+  @computed('model.session.@each', 'timezone')
   get allDates() {
     const arr = [];
-    const difference = (this.model.event.endsAt).diff(this.model.event.startsAt, 'days');
-    for (let i = 0; i <= Math.abs(difference); i++) {
-      arr.push(moment.tz(this.model.event.startsAt, this.timezone).add(i, 'days').toISOString());
-    }
+    const sessions = groupBy(this.model.session.toArray());
+    Object.values(sessions).forEach(el => {
+      arr.push(moment.tz(el[0].startsAt, this.timezone).toISOString());
```
Comment (ranjitkshah) [inline app/controllers/public/sessions.js:33]:
```
if(!arr.includes(el[0].startAtDate))
       arr.push(el[0].startAtDate)   
```
for now, it shows multiple buttons for a single day event
image

**Review by ranjitkshah — CHANGES_REQUESTED** [review]

File: app/controllers/public/sessions.js [hunk 2]
```diff
@@ -17,23 +17,21 @@ export default class SessionsController extends Controller {
...
 
-  @computed('model.event.startsAt', 'model.event.endsAt', 'timezone')
+  @computed('model.session.@each', 'timezone')
   get allDates() {
     const arr = [];
-    const difference = (this.model.event.endsAt).diff(this.model.event.startsAt, 'days');
-    for (let i = 0; i <= Math.abs(difference); i++) {
-      arr.push(moment.tz(this.model.event.startsAt, this.timezone).add(i, 'days').toISOString());
-    }
+    const sessions = groupBy(this.model.session.toArray());
```
Comment (afzal442) [inline app/controllers/public/sessions.js:31]: I have had the same solution using group by in my mind. Thanks for your PR.

File: app/controllers/public/sessions.js (hunk 1 above)
Comment (Creatoon) [reply app/controllers/public/sessions.js:33]: Thanks buddy I am fixing this

**Comment by iamareebjamal** [comment]
Please stick to what we discussed in the meeting or I have to re-iterate things you did you consider and it'll take weeks to finalize the PR

https://open-event-frontend-git-fork-creatoon-issues-6092patch.eventyay.vercel.app/e/a74665c3/schedule

**Comment by Creatoon** [comment]
@iamareebjamal 
Sir please review. As this time everything is working just fine on my side,
i have attached screenshots for the proofs.

we can see that , it is working fine for the events having multiple sessions on one day
 
Screenshot_2021-01-07 Sessions Pi shaped learning with FOSS Open Event

Another screenshot, for the event with one year time which have 20 scheduled sessions.

Screenshot_2021-01-07 Sessions js engines Open Event

But if we select a particular day, let's say 17'th

Screenshot_2021-01-07 Sessions js engines Open Event(1)

please try it on your side once and tell me if i am doing it in a wrong way.

File: app/controllers/public/sessions.js (hunk 1 above)
Comment (Creatoon) [reply app/controllers/public/sessions.js:34]: @ranjitkshah didn't worked at all

**Comment by iamareebjamal** [comment]
You're loading all sessions in one go. What if there are 200 sessions?

**Comment by Creatoon** [comment]
> You're loading all sessions in one go. What if there are 200 sessions?

No sir , that's the long screenshot i have taken , i have taken the screenshot after scrolling the page to the bottom, i am not loading all the sessions at once.

File: app/routes/public/sessions.js [hunk 3]
```diff
@@ -140,7 +140,43 @@ export default class SessionsRoute extends Route {
...
+              }
+            ]
+          }
+        ]
+      }
+    ];
+
+    const sessions = await event.query('sessions', {
+      filter       : scheduledFilterOptions,
+      'page[size]' : 0
```
Comment (iamareebjamal) [inline app/routes/public/sessions.js:177]: You are

File: app/routes/public/sessions.js [hunk 4]
```diff
@@ -146,35 +146,10 @@ export default class SessionsRoute extends Route {
...
-        ]
-      }
-    ];
 
     const sessions = await event.query('sessions', {
-      filter       : scheduledFilterOptions,
-      'page[size]' : 0
+      'fields[session]' : 'starts-at',
+      'page[size]'      : 0
     });
```
Comment (iamareebjamal) [inline app/routes/public/sessions.js]: Not this includes non accepted sessions

Comment (Creatoon) [reply app/routes/public/sessions.js]: ok then i should add accepted and confirmed sessions

File: app/routes/public/sessions.js (hunk 3 above)
Comment (Creatoon) [reply app/routes/public/sessions.js]: @iamareebjamal  sir by now the url for getting start-dates look-likes 

  http://localhost:5000/v1/events/4/sessions?fields[session]=starts-at&page[size]=0

if i will not use page[size]=0 , then how will i get all the start-dates

**Comment by Creatoon** [comment]
@iamareebjamal sir please review.

File: app/routes/public/sessions.js [hunk 5]
```diff
@@ -140,7 +140,40 @@ export default class SessionsRoute extends Route {
...
-      })
+      }),
+      schedules: await this.getSchedules(eventDetails)
     };
   }
+
+  async getSchedules(event) {
+
+    const scheduledFilterOptions = [
+      {
```
Comment (iamareebjamal) [inline app/routes/public/sessions.js:151]: filter out sessions with no starts at

File: app/routes/public/sessions.js [hunk 6]
```diff
@@ -140,7 +140,40 @@ export default class SessionsRoute extends Route {
         perPageParam : 'page[size]',
         pageParam    : 'page[number]',
         store        : eventDetails
-      })
+      }),
+      schedules: await this.getSchedules(eventDetails)
```
Comment (iamareebjamal) [inline app/routes/public/sessions.js:144]: blocking wait

**Comment by Creatoon** [comment]
@iamareebjamal sir please review

File: app/routes/public/sessions.js [hunk 7]
```diff
@@ -141,8 +142,8 @@ export default class SessionsRoute extends Route {
         pageParam    : 'page[number]',
         store        : eventDetails
       }),
-      schedules: await this.getSchedules(eventDetails)
-    };
+      schedules: this.getSchedules(eventDetails)
```
Comment (iamareebjamal) [inline app/routes/public/sessions.js:145]:
```suggestion
      dates: this.getDates(eventDetails)
```

File: app/controllers/public/sessions.js [hunk 8]
```diff
@@ -17,24 +17,37 @@ export default class SessionsController extends Controller {
...
+    Object.values(sessions).forEach(el => {
+      arr.push(moment.tz(el[0].startsAt, this.timezone).toISOString());
+    });
+
+    const arrSet = new Set();
+
+    arr.forEach(el => {
+      el = el.split('T')[0];
+      for (let j = 0; j < arr.length; j++) {
+        if (el === arr[j].split('T')[0]) {
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:42]: Use moment to parse

Comment (Creatoon) [reply app/controllers/public/sessions.js]: done

File: app/controllers/public/sessions.js [hunk 9]
```diff
@@ -37,9 +37,9 @@ export default class SessionsController extends Controller {
     const arrSet = new Set();
 
     arr.forEach(el => {
-      el = el.split('T')[0];
+      el = moment(el).utc().format('YYYY-MM-DD');
       for (let j = 0; j < arr.length; j++) {
-        if (el === arr[j].split('T')[0]) {
+        if (el === moment(arr[j]).utc().format('YYYY-MM-DD')) {
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js]: Use map and filter

Comment (Creatoon) [reply app/controllers/public/sessions.js]: sir , map will return a new array with same no of elements , but i don't want to do it here,
what i did , find all the elements of arr with same date and pushed those inside a set and set will automatically make it unique and that's why we are not getting repeated dates in the array.

Comment (iamareebjamal) [reply app/controllers/public/sessions.js]: Use Set

**Comment by Creatoon** [comment]
@iamareebjamal sir please review , this time i reduced all the code and used map and filter methods, and it works fine as well.

File: app/controllers/public/sessions.js [hunk 10]
```diff
@@ -27,27 +27,15 @@ export default class SessionsController extends Controller {
...
-        if (el === moment(arr[j]).utc().format('YYYY-MM-DD')) {
-          el = arr[j];
-          break;
-        }
-      }
-      arrSet.add(el);
-    });
-
-    return Array.from(arrSet).sort();
+    arr = arr.sort().filter((el, i) => moment(el).utc().format('YYYY-MM-DD') !== moment(arr[i + 1]).utc().format('YYYY-MM-DD')).map(el => el);
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:37]: No reason to reassign when you are returning on next line

File: app/controllers/public/sessions.js [hunk 11]
```diff
@@ -27,27 +27,15 @@ export default class SessionsController extends Controller {
 
   @computed('model.dates', 'timezone')
   get allDates() {
-    const arr = [];
+    let arr = [];
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:30]: const

File: app/controllers/public/sessions.js [hunk 12]
```diff
@@ -27,27 +27,15 @@ export default class SessionsController extends Controller {
...
     const sessions = groupBy(this.model.dates.toArray());
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:31]: Don't think it'll do anything, all start times are different

File: app/controllers/public/sessions.js (hunk 11 above)
Comment (Creatoon) [reply app/controllers/public/sessions.js]: done sir

File: app/controllers/public/sessions.js (hunk 10 above)
Comment (Creatoon) [reply app/controllers/public/sessions.js]: done

File: app/controllers/public/sessions.js (hunk 12 above)
Comment (Creatoon) [reply app/controllers/public/sessions.js:31]: ok sir ,got it

**Comment by Creatoon** [comment]
@iamareebjamal sir please review

File: app/controllers/public/sessions.js [hunk 13]
```diff
@@ -27,15 +27,14 @@ export default class SessionsController extends Controller {
...
+    const arr = [];
     const sessions = groupBy(this.model.dates.toArray());
 
     Object.values(sessions).forEach(el => {
       arr.push(moment.tz(el[0].startsAt, this.timezone).toISOString());
     });
 
-    arr = arr.sort().filter((el, i) => moment(el).utc().format('YYYY-MM-DD') !== moment(arr[i + 1]).utc().format('YYYY-MM-DD')).map(el => el);
-    return arr;
+    return arr.sort().filter((el, i) => moment(el).utc().format('YYYY-MM-DD') !== moment(arr[i + 1]).utc().format('YYYY-MM-DD')).map(el => el);
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:37]: Instead of using filter like this, use Set or distinct/unique from lodash

Comment (iamareebjamal) [inline app/controllers/public/sessions.js:37]:
```
map(el => el)
```

What does this do?

File: app/controllers/public/sessions.js [hunk 14]
```diff
@@ -27,15 +27,14 @@ export default class SessionsController extends Controller {
 
   @computed('model.dates', 'timezone')
   get allDates() {
-    let arr = [];
+    const arr = [];
     const sessions = groupBy(this.model.dates.toArray());
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:31]: As I already said, groupBy does nothing here

File: app/controllers/public/sessions.js (hunk 13 above)
Comment (Creatoon) [reply app/controllers/public/sessions.js:37]: sorry , it does nothing sir , i am removing that

Comment (Creatoon) [reply app/controllers/public/sessions.js:37]: Sir Set only contain unique elements , and because every date is different , set will store all of them

Actually i am getting all the sessions and from the session i want to filter the date.

```js
dates = ["2021-09-17T03:40:00.000Z", "2021-09-17T04:50:00.000Z",  "2021-09-17T06:05:00.000Z", ​
 "2021-09-17T07:45:00.000Z"]
```

that's why what i am doing if the only the date part of the ISO string first element does not match with next element , then i return that date, 
instead if i use Set here it will store all the dates because every date is different

Comment (iamareebjamal) [reply app/controllers/public/sessions.js:37]: Convert to date only and then use Set, obviously

File: app/controllers/public/sessions.js [hunk 15]
```diff
@@ -28,13 +28,20 @@ export default class SessionsController extends Controller {
...
-      arr.push(moment.tz(el[0].startsAt, this.timezone).toISOString());
+    this.model.dates.toArray().forEach(el => {
+      arr.push(moment.tz(el.startsAt, this.timezone).toISOString());
     });
 
-    return arr.sort().filter((el, i) => moment(el).utc().format('YYYY-MM-DD') !== moment(arr[i + 1]).utc().format('YYYY-MM-DD')).map(el => el);
+    const uniqueDates = new Set();
+
+    arr.sort().forEach((el, i) => {
+      if (moment(el).utc().format('YYYY-MM-DD') !== moment(arr[i + 1]).utc().format('YYYY-MM-DD')) {
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:39]: What's the point of the Set if you do this

**Comment by Creatoon** [comment]
@iamareebjamal please review sir,  actually now i got your point sir, i was misunderstanding till now,
thank you sir for your valuable reviews.

File: app/controllers/public/sessions.js [hunk 16]
```diff
@@ -17,24 +17,29 @@ export default class SessionsController extends Controller {
...
   get allDates() {
     const arr = [];
-    const difference = (this.model.event.endsAt).diff(this.model.event.startsAt, 'days');
-    for (let i = 0; i <= Math.abs(difference); i++) {
-      arr.push(moment.tz(this.model.event.startsAt, this.timezone).add(i, 'days').toISOString());
-    }
-    return arr;
+
+    this.model.dates.toArray().forEach(el => {
+      arr.push(moment.tz(el.startsAt, this.timezone).toISOString());
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:33]: Use .map

File: app/controllers/public/sessions.js [hunk 17]
```diff
@@ -17,24 +17,26 @@ export default class SessionsController extends Controller {
...
-      arr.push(moment.tz(this.model.event.startsAt, this.timezone).add(i, 'days').toISOString());
-    }
-    return arr;
+
+    const arr = this.model.dates.toArray().map(el => moment.tz(el.startsAt, this.timezone).toISOString());
+
+    const uniqueDates = new Set();
+
+    arr.sort().forEach(el => {
+      uniqueDates.add(moment(el).format('YYYY-MM-DD'));
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:36]: This can be moved to .sort().map above

Comment (Creatoon) [reply app/controllers/public/sessions.js:36]: map().sort() will do the correct job sir

Comment (iamareebjamal) [reply app/controllers/public/sessions.js:36]: This can be moved to .map above

**Comment by Creatoon** [comment]
@iamareebjamal sir please review.

**Comment by iamareebjamal** [comment]
Already done https://github.com/fossasia/open-event-frontend/pull/6247#discussion_r553978716

**Comment by Creatoon** [comment]
> Already done [#6247 (comment)](https://github.com/fossasia/open-event-frontend/pull/6247#discussion_r553978716)

ok sir thank you

**Comment by Creatoon** [comment]
@iamareebjamal Sir , if there are no sessions , then what is the need of these filters and "ALL" button, i think page will look much less bulky or easy to understand if there are no sessions, what do you think?

Screenshot_2021-01-09 Sessions dcdsdsvdvdfvdfvd Open Event

Screenshot_2021-01-09 Sessions dcdsdsvdvdfvdfvd Open Event(1)

should i commit these changes alongwith this pr.

**Comment by iamareebjamal** [comment]
There shouldn't be a schedule button if there are no sessions

**Comment by Creatoon** [comment]
> There shouldn't be a schedule button if there are no sessions

yes sir you are right , but if a user search like this e/123/schedule, then this page can appear

**Comment by iamareebjamal** [comment]
No that important, Fix what I have said

**Comment by Creatoon** [comment]
> Not that important, Fix what I have said

Ok sir,  but what else left,  dates are shown correctly, If there anything left please tell me

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-frontend/pull/6247#issuecomment-756867090

**Comment by Creatoon** [comment]
@iamareebjamal done sir

File: app/controllers/public/sessions.js [hunk 18]
```diff
@@ -17,24 +17,24 @@ export default class SessionsController extends Controller {
...
-    const arr = [];
-    const difference = (this.model.event.endsAt).diff(this.model.event.startsAt, 'days');
-    for (let i = 0; i <= Math.abs(difference); i++) {
-      arr.push(moment.tz(this.model.event.startsAt, this.timezone).add(i, 'days').toISOString());
-    }
-    return arr;
+
+    const uniqueDates = new Set();
+
+    this.model.dates.toArray().map(el => moment.tz(el.startsAt, this.timezone).toISOString()).sort().forEach(el => {
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:33]: No need of forEach, use .map

Comment (Creatoon) [reply app/controllers/public/sessions.js:33]: i will use the .map here , but i am not getting , what's the difference , because .map will return the new array but forEach will only give the access to each element , i want to know about it?

File: app/controllers/public/sessions.js [hunk 19]
```diff
@@ -17,24 +17,24 @@ export default class SessionsController extends Controller {
...
-    const difference = (this.model.event.endsAt).diff(this.model.event.startsAt, 'days');
-    for (let i = 0; i <= Math.abs(difference); i++) {
-      arr.push(moment.tz(this.model.event.startsAt, this.timezone).add(i, 'days').toISOString());
-    }
-    return arr;
+
+    const uniqueDates = new Set();
+
+    this.model.dates.toArray().map(el => moment.tz(el.startsAt, this.timezone).toISOString()).sort().map(el => {
+      uniqueDates.add(moment(el).format('YYYY-MM-DD'));
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:34]: Move `moment(el).format('YYYY-MM-DD')` to map

Comment (Creatoon) [reply app/controllers/public/sessions.js]: @iamareebjamal  done sir

File: app/controllers/public/sessions.js [hunk 20]
```diff
@@ -17,24 +17,22 @@ export default class SessionsController extends Controller {
...
-    const arr = [];
-    const difference = (this.model.event.endsAt).diff(this.model.event.startsAt, 'days');
-    for (let i = 0; i <= Math.abs(difference); i++) {
-      arr.push(moment.tz(this.model.event.startsAt, this.timezone).add(i, 'days').toISOString());
-    }
-    return arr;
+
+    const uniqueDates = new Set();
+
+    this.model.dates.toArray().map(el => moment(moment.tz(el.startsAt, this.timezone)).format('YYYY-MM-DD')).sort().map(el => uniqueDates.add(el));
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:33]:
```suggestion
    const uniqueDates = new Set(this.model.dates.toArray().map(date => moment.tz(date.startsAt, this.timezone)).sort().map(date => moment().format('YYYY-MM-DD')));
```

How hard was this?

I'm reviewing it for 2 days. More than 26 commits later, it is still not at desired stage

Comment (Creatoon) [reply app/controllers/public/sessions.js:33]: sir , i literally thought , it would be not readable , that's why i wrote the code in full length from the very beginning.

Comment (Creatoon) [reply app/controllers/public/sessions.js]: Sir you wrote the code full code, i don't want this pr to be fall in my contributions, thank you , i will find another issue to solve completely.

**Comment by iamareebjamal** [comment]
```js
let arr = [];
const sessions = groupBy(this.model.schedules.toArray());

Object.values(sessions).forEach(el => {
    arr.push(moment.tz(el[0].startsAt, this.timezone).toISOString());   
});

let arrSet = new Set();

arr.forEach(el => {
  el = el.split('T')[0];
  for (let j = 0; j < arr.length; j++) {
    if (el === arr[j].split('T')[0]) {
      el = arr[j];
      break;
    }
  }
  arrSet.add(el);
})

return Array.from(arrSet).sort();
```

```js
const arr = [];

this.model.dates.toArray().forEach(el => {
  arr.push(moment.tz(el.startsAt, this.timezone).toISOString());
});

const uniqueDates = new Set();

arr.sort().forEach((el, i) => {
  if (moment(el).utc().format('YYYY-MM-DD') !== moment(arr[i + 1]).utc().format('YYYY-MM-DD')) {
    uniqueDates.add(el);
  }
});

return [...uniqueDates];
```

```js
const arr = [];

this.model.dates.toArray().forEach(el => {
  arr.push(moment.tz(el.startsAt, this.timezone).toISOString());
});

const uniqueDates = new Set();

arr.sort().forEach(el => {
  uniqueDates.add(moment(el).format('YYYY-MM-DD'));
})

return [...uniqueDates]
```

```js
const uniqueDates = new Set(this.model.dates.toArray()
    .map(date => moment.tz(date.startsAt, this.timezone).toISOString())
    .sort()
    .map(date => moment(date).format('YYYY-MM-DD')));

return [...uniqueDates];
```

Which is simpler and easier to read?

**Comment by Creatoon** [comment]
> Which is simpler and easier to read?

yes sir the last one , i am wrong here

**Comment by Creatoon** [comment]
sir one miute , it is giving wrong output ,  i am fixing this

File: app/routes/public/sessions.js [hunk 21]
```diff
@@ -140,7 +141,44 @@ export default class SessionsRoute extends Route {
...
+              }
+            ]
+          }
+        ]
+      }
+    ];
+
+    const sessions = await event.query('sessions', {
+      filter       : scheduledFilterOptions,
+      'page[size]' : 0
```
Comment (iamareebjamal) [inline app/routes/public/sessions.js:179]: I am so confused. Why did you remove fields[session]=starts-at from here

Did you not understand why I added it?

Comment (Creatoon) [reply app/routes/public/sessions.js:179]: yes sir i got that , in order to get the starting dates of all sessions  , but i checked after removing that , it was working just fine , that's why i removed , i am adding it again.

Comment (iamareebjamal) [reply app/routes/public/sessions.js:179]: LOL, it was not added just for the sake of it, now it is loading 2 MB of data from server instead of 256KB

File: app/controllers/public/sessions.js [hunk 22]
```diff
@@ -12,29 +12,76 @@ export default class SessionsController extends Controller {
...
 
   @computed('model.session.@each', 'timezone')
   get groupByDateSessions() {
     let sessions;
-
     if (this.sort === 'title') {
       sessions = groupBy(this.model.session.toArray(), '');
     } else {
       sessions = groupBy(this.model.session.toArray(), s => moment.tz(s.startsAt, this.timezone).format('dddd, Do MMMM'));
     }
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:25]:
```suggestion
    }

```

File: app/routes/public/sessions.js [hunk 23]
```diff
@@ -143,4 +143,5 @@ export default class SessionsRoute extends Route {
       })
     };
   }
+
```
Comment (iamareebjamal) [inline app/routes/public/sessions.js:146]:
```suggestion
```

File: app/controllers/public/sessions.js [hunk 24]
```diff
@@ -12,29 +12,76 @@ export default class SessionsController extends Controller {
   sort = 'starts-at';
   isTrackVisible = false;
   timezone = null;
+  dates = null;
   preserveScrollPosition = true;
 
   @computed('model.session.@each', 'timezone')
   get groupByDateSessions() {
     let sessions;
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:20]:
```suggestion
    let sessions;
 
```

File: app/controllers/public/sessions.js [hunk 25]
```diff
@@ -12,12 +12,13 @@ export default class SessionsController extends Controller {
...
-
+
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:21]:
```suggestion
   
```

File: app/routes/public/sessions.js (hunk 21 above)
Comment (Creatoon) [reply app/routes/public/sessions.js]: yes sir I didn't understood it properly, I was not able to solve the issue,  sorry for that,  I will not bother you again.

File: app/controllers/public/sessions.js [hunk 26]
```diff
@@ -12,12 +12,13 @@ export default class SessionsController extends Controller {
...
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:21]:
```suggestion

```

File: app/controllers/public/sessions.js [hunk 27]
```diff
@@ -12,12 +12,12 @@ export default class SessionsController extends Controller {
   sort = 'starts-at';
   isTrackVisible = false;
   timezone = null;
+  dates = null;
   preserveScrollPosition = true;
 
   @computed('model.session.@each', 'timezone')
   get groupByDateSessions() {
     let sessions;
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:20]:
```suggestion
    let sessions;
    
```

File: app/controllers/public/sessions.js [hunk 28]
```diff
@@ -12,12 +12,13 @@ export default class SessionsController extends Controller {
...
-
+
```
Comment (iamareebjamal) [inline app/controllers/public/sessions.js:21]:
```suggestion

```
