### PR TITLE
 fix: made same color of status badges on the speakers as well as session pages

### LINKED ISSUE #6521: Organizer Speaker/Session Page: Colors of status badge differ
The colors of the status badges e.g. "Accepted" differ between the speaker overview page and the session overview page of organizers.

Please use the same colors everyhwere.

Screenshot from 2021-01-29 06-58-43
Screenshot from 2021-01-29 06-58-26
Screenshot from 2021-01-29 06-58-00

### PR DESCRIPTION
**Pull request by Creatoon**
Fixes #6521 

#### Short description of what this resolves:
Previously the status badges colors were not matching , but now it is resolved.

#### Changes proposed in this pull request:
I used same source of colors which is stateColorMap for speakers page also, so that if one changes , the other will automatically gets changed.

On speaker page

Screenshot_2021-02-01 All Speakers brom bones Events Open Event

On sessions page

Screenshot_2021-02-01 Session Sessions brom bones Events Open Event

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Creatoon** [comment]
@iamareebjamal Sir please review, thanks

File: app/helpers/session-color.js [hunk 1]
```diff
@@ -1,13 +1,14 @@
...
   switch (params[0]) {
     case 'accepted':
-      return 'yellow';
+      return stateColorMap.accepted;
     case 'pending':
-      return 'yellow';
+      return stateColorMap.pending;
     case 'confirmed':
-      return 'green';
+      return stateColorMap.confirmed;
```
Comment (iamareebjamal) [inline app/helpers/session-color.js:11]: Don't you find it redundant?

Comment (Creatoon) [reply app/helpers/session-color.js]: @iamareebjamal So sir, what should i do, can you elaborate me a bit

File: app/helpers/session-color.js [hunk 2]
```diff
@@ -2,16 +2,7 @@ import Helper from '@ember/component/helper';
...
-    case 'accepted':
-      return stateColorMap.accepted;
-    case 'pending':
-      return stateColorMap.pending;
-    case 'confirmed':
-      return stateColorMap.confirmed;
-    default:
-      return 'red';
-  }
+  return stateColorMap[`${params[0]}`];
```
Comment (iamareebjamal) [inline app/helpers/session-color.js:5]: Why `${}`?

**Comment by Creatoon** [comment]
@iamareebjamal Sir i have made the  changes , is it fine now
