### PR TITLE
fix: empty error box during oneclicksignup

### LINKED ISSUE #7779: Empty error box appears during registration process
When ordering a ticket using the registration option an empty red error box appears during the order process on the bottom right. It appears even if there is no error.

Screenshot from 2021-09-13 11-03-35

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #7779 

#### Screenshot
image

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/controllers/public/index.js [hunk 1]
```diff
@@ -153,11 +153,7 @@ export default class IndexController extends Controller {
       }
     }
     try {
-      const order = await this.loader.post('/orders/create-order', myinput);
-      this.notify.success(this.l10n.t('Order details saved. Please fill further details within {{time}} minutes.', {
-        time: this.settings.orderExpiryTime
-      }));
-      this.transitionToRoute('orders.new', order.data.attributes.identifier);
+      this.set('orderInput', myinput);
```
Comment (maze-runnar) [inline app/controllers/public/index.js:156]: can you explain  this line.

Comment (pc-beast) [reply app/controllers/public/index.js:156]: this post request is being handled in save() by placeOrder(). request was being sent two times: once with payload and once without payload(during save()). Now only save will send request which is in pipe action with placeOrder().
https://github.com/fossasia/open-event-frontend/blob/f3ab0cea6561f4b4326ef3e40c12e9496a600b7c/app/templates/public/index.hbs#L55

**Review by mariobehling — COMMENTED** [review]
Works as expected. Please verify code is as expected and merge when done @maze-runnar Thanks.

**Review by maze-runnar — APPROVED** [review]
