### PR TITLE
fix: Restructure Account Invoice Tab 

### LINKED ISSUE #4959: Organizer Invoice Tab: In overview table add Invoice date and Pay with Paypal or Credit Card (Stripe)
In the organizer invoice tab we need to have additional options:
* [x] Change main tab name from "Billing Info" to "Billing"
* [x] On Invoice Page implement filters: Unpaid, Overdue, Paid, Failed, Refunding, Refunded
* [x] For the invoice use company data provided in payment info
* [x] In invoice # column provide the invoices as downloadable PDF 
* [x] Add a column "Date" after "Event Name"
* [x] Make table sortable according to Invoice ID, Event Name, Date
* [x] Add a Paypal Pay button and a Credit Card (Pay with Stripe Button) in the actions column
* [x] Once the invoice has been paid update the status to "Paid" 

compare https://eventyay.com/account/billing/
Screenshot from 2020-09-03 15-59-27

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4959
- [x] Change main tab name from "Billing Info" to "Billing"
- [x]  initial frontend change On Invoice Page implement filters: Unpaid, Overdue, Paid, Failed, Refunding, Refunded
- [x] Add a column "Date" after "Event Name"
Screenshot from 2020-09-11 10-35-42

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/routes/account/billing/invoices/list.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

File: app/controllers/account/billing/invoices/list.js [hunk 1]
```diff
@@ -133,6 +133,105 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
...
+          headerComponent : 'tables/headers/sort'
+        },
+        {
+          name            : 'Action',
+          valuePath       : 'identifier',
+          extraValuePaths : ['status'],
+          cellComponent   : 'ui-table/cell/events/cell-action'
+        }
+
+      ];
```
Comment (iamareebjamal) [inline app/controllers/account/billing/invoices/list.js:169]: I don't understand. It's the exact same code. Why are there else if statements everywhere?

Comment (maze-runnar) [reply app/controllers/account/billing/invoices/list.js:169]: > I don't understand. It's the exact same code. Why are there else if statements everywhere?

it will be changed, I don't know what would be the exact column name. Not mentioned in issue.

**Comment by iamareebjamal** [comment]
Are these statuses present in the server?

**Comment by maze-runnar** [comment]
created a PR, but only added option in  status like ` status = fields.Str(validate=validate.OneOf(choices=["paid", "due", "refunding", "refunded", "unpaid"]), allow_none=True)
   `

 https://github.com/fossasia/open-event-server/pull/7260

**Comment by maze-runnar** [comment]
What's next in this issue?

**Comment by iamareebjamal** [comment]
Please remove unpaid and overdue status

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
i haven't added overdue status

**Comment by iamareebjamal** [comment]
From server as well please

**Comment by iamareebjamal** [comment]
Then you need to make some dummy event invoices in the DB and check that they show up in the frontend under proper tabs

**Comment by maze-runnar** [comment]
> From server as well please

Done

**Comment by maze-runnar** [comment]
> Then you need to make some dummy event invoices in the DB and check that they show up in the frontend under proper tabs

ok

**Comment by iamareebjamal** [comment]
You can use this - http://localhost:5000/admin/eventinvoice/new/

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/routes/account/billing/invoices/list.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-11 13-28-56
Screenshot from 2020-09-11 13-28-53
Screenshot from 2020-09-11 13-28-50
Screenshot from 2020-09-11 13-28-39

**Comment by maze-runnar** [comment]
>  In invoice # column provide the invoices as downloadable PDF

is it invoicepdfurl, which I need to add in first column?

**Comment by maze-runnar** [comment]
And hot to do this - 
For the invoice use company data provided in payment info

**Comment by iamareebjamal** [comment]
> > In invoice # column provide the invoices as downloadable PDF
> 
> is it invoicepdfurl, which I need to add in first column?

Yes

**Comment by iamareebjamal** [comment]
> And how to do this -
> For the invoice use company data provided in payment info

This will be solved in other issue

File: app/routes/account/billing/invoices/list.js [hunk 2]
```diff
@@ -12,6 +12,12 @@ export default class extends Route.extend(EmberTableRouteMixin) {
         return this.l10n.t('Due');
       case 'upcoming':
         return this.l10n.t('Upcoming');
+      case 'unpaid':
+        return this.l10n.t('Unpaid');
+      case 'refunding':
+        return this.l10n.t('Refunding');
+      case 'refunded':
+        return this.l10n.t('Refunded');
```
Comment (iamareebjamal) [inline app/routes/account/billing/invoices/list.js:20]: Simply use capitalize function instead of switch case. Check out `admin/sessions/list` route. Use `All` in else

File: app/routes/account/billing/invoices/list.js [hunk 3]
```diff
@@ -21,7 +27,7 @@ export default class extends Route.extend(EmberTableRouteMixin) {
     this.set('params', params);
     const searchField = 'status';
     let filterOptions = [];
-    if (params.invoice_status === 'paid' || params.invoice_status === 'due') {
+    if (params.invoice_status === 'paid' || params.invoice_status === 'due' || params.invoice_status === 'refunding' || params.invoice_status === 'refunded') {
```
Comment (iamareebjamal) [inline app/routes/account/billing/invoices/list.js:30]: Use `['paid', ...].includes`

File: app/routes/account/billing/invoices/list.js (hunk 2 above)
Comment (maze-runnar) [reply app/routes/account/billing/invoices/list.js:20]: ok

**Comment by iamareebjamal** [comment]
Also, upcoming is not a valid state

**Comment by maze-runnar** [comment]
> Also, upcoming is not a valid state

it is calculated

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ app/routes/account/billing/invoices/list.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity decreasing per file
==============================
+ app/routes/account/billing/invoices/list.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

File: app/controllers/account/billing/invoices/list.js [hunk 4]
```diff
@@ -102,6 +102,82 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
 
       ];
     } else if (this.model.params.invoice_status === 'all') {
+      columns = [
+        {
+          name      : '#',
```
Comment (niranjan94) [inline app/controllers/account/billing/invoices/list.js:107]: Codacy found an issue: [Missing space after key 'name'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665)

File: app/controllers/account/billing/invoices/list.js [hunk 5]
```diff
@@ -102,6 +102,82 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
...
+          valuePath : 'invoicePdfUrl',
```
Comment (niranjan94) [inline app/controllers/account/billing/invoices/list.js:108]: Codacy found an issue: [Missing space after key 'valuePath'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665)

**Comment by iamareebjamal** [comment]
Invoice # means Invoice ID which was already there

**Comment by maze-runnar** [comment]
where to add the download url?

**Comment by iamareebjamal** [comment]
You need to add a download icon in the invoice number column

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity decreasing per file
==============================
+ app/routes/account/billing/invoices/list.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

File: app/controllers/account/billing/invoices/list.js [hunk 6]
```diff
@@ -102,6 +102,79 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
 
       ];
     } else if (this.model.params.invoice_status === 'all') {
+      columns = [
+        {
+          name           : 'Invoice ID',
+          valuePath      : 'identifier',
+          extraValuePaths : ['invoicePdfUrl'],
+          cellComponent  : 'ui-table/cell/events/cell-download-invoice'
```
Comment (niranjan94) [inline app/controllers/account/billing/invoices/list.js:110]: Codacy found an issue: [Missing space after key 'cellComponent'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665)

File: app/controllers/account/billing/invoices/list.js [hunk 7]
```diff
@@ -102,6 +102,79 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
 
       ];
     } else if (this.model.params.invoice_status === 'all') {
+      columns = [
+        {
+          name           : 'Invoice ID',
+          valuePath      : 'identifier',
```
Comment (niranjan94) [inline app/controllers/account/billing/invoices/list.js:108]: Codacy found an issue: [Missing space after key 'valuePath'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665)

File: app/controllers/account/billing/invoices/list.js [hunk 8]
```diff
@@ -102,6 +102,79 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
 
       ];
     } else if (this.model.params.invoice_status === 'all') {
+      columns = [
+        {
+          name           : 'Invoice ID',
```
Comment (niranjan94) [inline app/controllers/account/billing/invoices/list.js:107]: Codacy found an issue: [Missing space after key 'name'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665)

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-11 23-27-54

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ app/routes/account/billing/invoices/list.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-14 09-07-41

**Comment by maze-runnar** [comment]
how to connect it for payment?

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ app/routes/account/billing/invoices/list.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-14 18-54-42

**Comment by maze-runnar** [comment]
is it done for issue?

**Comment by iamareebjamal** [comment]
Since there is no way to pay for invoice right now, please hide the column. Also, have you checked that you cannot see other's invoice in the section?

**Comment by iamareebjamal** [comment]
Add invoices with different user IDs and check they don't show up under your account

**Comment by maze-runnar** [comment]
other user's invoice is also visible in this section

**Comment by iamareebjamal** [comment]
Fix that please

**Comment by iamareebjamal** [comment]
This is a server issue as well, but first fix this in frontend

**Comment by maze-runnar** [comment]
> This is a server issue as well, but first fix this in frontend

how to filter it, tried this` this.authManager.currentUser.email === this.user.email` not worked, tried filter in routes but nested filter is not supported, wrote a computed property and used this condition ` this.authManager.currentUser.email === this.user.email`  but it is giving error.

**Comment by maze-runnar** [comment]
> Fix that please

Done

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ app/routes/account/billing/invoices/list.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

**Comment by iamareebjamal** [comment]
Incorrect. the endpoint itself is incorrect. You don't get access to all invoices of people as a normal user. Only admin does. `user/:id/invoices` is the correct endpoint

**Comment by maze-runnar** [comment]
> Incorrect. the endpoint itself is incorrect. You don't get access to all invoices of people as a normal user. Only admin does. `user/:id/invoices` is the correct endpoint

account -> billing -> invoices, that's it is?

**Comment by iamareebjamal** [comment]
I don't understand. I am talking about the endpoint used to fetch invoices for the user

**Comment by maze-runnar** [comment]
where user will see all it's invoices actually? Not in invoice section? As admin can see that section..

**Comment by iamareebjamal** [comment]
> account -> billing -> invoices

This is for user, not admin

**Comment by maze-runnar** [comment]
> This is for user, not admin

I have made changes in this section. So where I am wrong? or I am again going in confusion. 
And if this section is for users then why it is not accessible by using api.eventyay.com ? Why I have to login as admin?

**Comment by iamareebjamal** [comment]
See `routes/events/list.js` for reference
You have to login because the API being used is only allowed for admins

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-16 16-38-05

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-16 16-40-53

**Comment by iamareebjamal** [comment]
See what's the error in console and network tab. Debug the error a bit

**Comment by iamareebjamal** [comment]
Check which API call failed. Check why did it fail. Check the API docs/code if it is the correct API, if the API is even present

**Comment by maze-runnar** [comment]
> Check which API call failed. Check why did it fail. Check the API docs/code if it is the correct API, if the API is even present

ok

**Comment by maze-runnar** [comment]
`Error while processing route: account.billing.invoices.list Assertion Failed: There is no belongsTo relationship named 'event-invoice' on a model of modelClass 'user'`

**Comment by iamareebjamal** [comment]
You'll have to add that

**Comment by maze-runnar** [comment]
this is present` /v1/event-invoices/{event_invoice_id}/user`

**Comment by iamareebjamal** [comment]
That's for finding the user of the invoice, not the invoice of the user. Besides, this is ember error, not API error

**Comment by maze-runnar** [comment]
event-invoice has this - 
  user  : belongsTo('user'),

Do i need to add this kind of in user

**Comment by maze-runnar** [comment]
`/v1/users/{user_id}/event-invoices`

**Comment by iamareebjamal** [comment]
> event-invoice has this -
> user : belongsTo('user'),
> 
> Do i need to add this kind of in user

Not this kind, but yes. Open user model and you'll get it

**Comment by maze-runnar** [comment]
there is  `invoice              : hasMany('event-invoice'), ` in user model

**Comment by iamareebjamal** [comment]
Change it to `invoices` and then use `.query('invoices', queryString)`

**Comment by maze-runnar** [comment]
`eventInvoices: this.asArray(this.authManager.currentUser.query('invoice', queryString))` invoice instead of event-invoice is working

**Comment by maze-runnar** [comment]
it's showing page correctly but not invoice data

**Comment by maze-runnar** [comment]
the page is showing correctly for the user now, accessible, not showing dummy data.Assertion Failed: Cannot call get with 'count' on an undefined object.

**Comment by iamareebjamal** [comment]
Check the API response in network tab

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-16 18-07-02

**Comment by iamareebjamal** [comment]
Checking

**Comment by iamareebjamal** [comment]
It's because of stupid ember data expecting relationship in user to be `event-invoices` and not `event-invoice`

Please create a PR on server fixing this relationship in user schema

**Comment by iamareebjamal** [comment]
Checked by doing that and still not working. Finding out why

**Comment by iamareebjamal** [comment]
It should be named `eventInvoices` exactly. Also changes are needed on backend. Sending a PR.

**Comment by iamareebjamal** [comment]
Pull the changes in https://github.com/fossasia/open-event-server/pull/7270 locally and change it to `eventInvoices`

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
not working
Screenshot from 2020-09-16 21-28-08

**Comment by iamareebjamal** [comment]
Show the error, not just screenshot

**Comment by maze-runnar** [comment]
`Uncaught (in promise) Error: Assertion Failed: Cannot call get with 'count' on an undefined object.`

**Comment by iamareebjamal** [comment]
You must not have changed `invoice` to `eventInvoices` in the user model. You have to try things out first intuitively at first. I have confirmed the changes and then commented. Already tested for 2-3 hours

**Comment by iamareebjamal** [comment]
That's the change I was asking you to make - https://github.com/fossasia/open-event-frontend/pull/5049/commits/3b7415dc07b5868d457de99a8718cfe860a5e6c1

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ app/routes/account/billing/invoices/list.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)

**Comment by maze-runnar** [comment]
on making all changes `this.model.eventInvoices.data` is giving undefined

**Comment by maze-runnar** [comment]
`{"data": [], "links": {"self": "/v1/users/1/event-invoices?include=event&filter=%5B%5D&page%5Bsize%5D=10&page%5Bnumber%5D=1"}, "meta": {"count": 0}, "jsonapi": {"version": "1.0"}}`
I have added dummy invoices , but data is null

**Comment by iamareebjamal** [comment]
Please work on other issues

**Comment by maze-runnar** [comment]
ok

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ app/routes/account/billing/invoices/list.js  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6161665&bid=20126751)
