### PR TITLE
fix: Seperate the admin/sales tab into 2 subtabs

### LINKED ISSUE #4954: Invoices/Sales Admin Overview: Implement subtabs and add info about invoice status
The admin overview on the system sales need to be improved to ensure a smooth sales and invoicing process that can be taken care of by sales staff. Therefore:

* [ ] Separate the admin/sales tab into 2 subtabs - Orders and Invoices
* [ ] Move the sidebar table "Invoices" (https://eventyay.com/admin/sales/invoices) to its dedicated tab
* [ ] Make table sortable according to each column
* [ ] Enhance the Invoice table and implement missing tabs as follows. Show:
  * [ ] Invoice # (show with download link of Invoice PDF)
  * [ ] Invoice Date
  * [ ] Event
  * [ ] Dates
  * [ ] Amount
  * [ ] Organizer/Email (Show Names and Emails here)
  * [ ] Invoice Sent (Show dates invoice was sent out and also the dates if it was sent out several times)
  * [ ] Status (Unpaid, Overdue, Paid, Failed, Refunding, Refunded, Request Cancelled - Enable Admin to change the state; "Request Cancelled" means there was no invoice paid and the platform cancelled the request to pay the invoice)
  * [ ] Notify button (opening a pop-up with email options depending on state)
  * [ ] Resend Invoice button

Compare https://eventyay.com/admin/sales

Screenshot from 2020-09-03 11-50-56

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4954 

Screenshot from 2020-09-14 13-55-39
Screenshot from 2020-09-14 13-55-34

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
once https://github.com/fossasia/open-event-frontend/pull/5049 will be merged then, I will add here the download option in invoice#

**Comment by maze-runnar** [comment]
> Notify button (opening a pop-up with email options depending on state)
>  Resend Invoice button

is there a feature available on server for sending mail for invoice?

File: app/controllers/admin/sales/invoices.js [hunk 1]
```diff
@@ -38,6 +37,11 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
+      },
+      {
+        name            : 'Action',
+        valuePath       : 'identifier',
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:43]: Codacy found an issue: [Extra space after key 'valuePath'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716&bid=20154821)

File: app/controllers/admin/sales/invoices.js [hunk 2]
```diff
@@ -38,6 +37,11 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
...
+        cellComponent   : 'ui-table/cell/admin/sales/cell-action'
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:44]: Codacy found an issue: [Extra space after key 'cellComponent'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 3]
```diff
@@ -38,6 +37,11 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
+      },
+      {
+        name            : 'Action',
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:42]: Codacy found an issue: [Extra space after key 'name'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

**Comment by maze-runnar** [comment]
Screenshot from 2020-09-14 17-36-08

**Comment by iamareebjamal** [comment]
Not right now. So, let's hide that column for now and merge the PR and when there is an API, we'll show the column again

File: app/controllers/admin/sales/invoices.js [hunk 4]
```diff
@@ -37,11 +37,6 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
-      },
-      {
-        name          : 'Action',
-        valuePath     : 'identifier',
-        cellComponent : 'ui-table/cell/admin/sales/cell-action'
```
Comment (iamareebjamal) [inline app/controllers/admin/sales/invoices.js]: Please comment it out since this is a part of current code.

File: app/controllers/admin/sales/invoices.js [hunk 5]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
-      }
+      },
+//       {
+//         name            : 'Action',
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:42]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716&bid=20154821)

File: app/controllers/admin/sales/invoices.js [hunk 6]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
-      }
+      },
+//       {
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:41]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 7]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
...
+//         name            : 'Action',
+//         valuePath       : 'identifier',
+//         cellComponent   : 'ui-table/cell/admin/sales/cell-action'
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:44]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 8]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
-      }
+      },
+//       {
+//         name            : 'Action',
+//         valuePath       : 'identifier',
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:43]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 9]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
-      }
+      },
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:40]: Codacy found an issue: [Unexpected trailing comma.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 10]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
...
+//       {
+//         name            : 'Action',
+//         valuePath       : 'identifier',
+//         cellComponent   : 'ui-table/cell/admin/sales/cell-action'
+//       }
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:45]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:45]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716&bid=20154821)

File: app/controllers/admin/sales/invoices.js [hunk 11]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
-      }
+      },
+//    {
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:41]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 12]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
...
+//      name            : 'Action',
+//      valuePath       : 'identifier',
+//      cellComponent   : 'ui-table/cell/admin/sales/cell-action'
+//    }
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:45]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 13]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
-      }
+      },
+//    {
+//      name            : 'Action',
+//      valuePath       : 'identifier',
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:43]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js (hunk 9 above)
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:40]: Codacy found an issue: [Unexpected trailing comma.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js (hunk 12 above)
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:45]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 14]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
...
+//      cellComponent   : 'ui-table/cell/admin/sales/cell-action'
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:44]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 15]
```diff
@@ -38,7 +37,12 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       {
         name      : 'Status',
         valuePath : 'status'
-      }
+      },
+//    {
+//      name            : 'Action',
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:42]: Codacy found an issue: [Expected indentation of 6 spaces but found 0.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716&bid=20154821)

File: app/controllers/admin/sales/invoices.js [hunk 16]
```diff
@@ -39,7 +38,11 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
         name      : 'Status',
         valuePath : 'status'
       }
+      //{
+      //  name            : 'Action',
+      //  valuePath       : 'identifier',
+      //  cellComponent   : 'ui-table/cell/admin/sales/cell-action'
+      //}
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:45]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:45]: Codacy found an issue: [Expected space or tab after '//' in comment.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

File: app/controllers/admin/sales/invoices.js [hunk 17]
```diff
@@ -39,7 +38,11 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
         name      : 'Status',
         valuePath : 'status'
       }
+      //{
```
Comment (niranjan94) [inline app/controllers/admin/sales/invoices.js:41]: Codacy found an issue: [Expected space or tab after '//' in comment.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6173716)

**Comment by maze-runnar** [comment]
what's next in this PR?

**Review by mariobehling — CHANGES_REQUESTED** [review]
Looks good to me, except for:
* Invoice # - I dont know where that number comes from, but I guess that can also be solved in another issue
* Dated - When looking at it it is unclear to me which date is meant (event date, invoice date, email sent date). We need to clarify this. The date should be "invoice date". Therefore please change "Dated" to "Invoice Date".

**Comment by maze-runnar** [comment]
>  I guess that can also be solved in another issue

ok

**Comment by mariobehling** [comment]
For invoice # please use:

**Comment by iamareebjamal** [comment]
Invoice number will be handled in another PR so merging this
