### PR TITLE
fix: Change default pre-selected fields in wizard step 4

### LINKED ISSUE #4586: Session and Speakers form in Wizard Step 4 have a few fields pre-selected which are not necessary to be pre-selected
Session and Speakers form have a few fields pre-selected even for new events (wizard step 4). Only pre-select the following by default (but let the organizer decide if they and how they want to change it except for the fields required by the system as below).

Speakers Form
- Name (Required)
- Email (Required)
- Position
- Organization
- Short Bio
- Photo 
- Website

Session Form
- Title (Required)
- Short Abstract
- Comments

Screenshot from 2020-07-20 20-08-37

### PR DESCRIPTION
**Pull request by Haider8**
Fixes #4586 

#### Short description of what this resolves:
Session and speaker custom forms have few fields pre-selected for new events in wizard step 4.

#### Changes proposed in this pull request:
Change default pre-selected fields

default-pre-selected-fields

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/mixins/custom-form.js [hunk 1]
```diff
@@ -50,17 +50,17 @@ export default Mixin.create(MutableArray, {
         fieldIdentifier : 'track',
         form            : 'session',
         type            : 'select',
-        isRequired      : true,
-        isIncluded      : true,
-        isFixed         : true,
+        isRequired      : false,
+        isIncluded      : false,
+        isFixed         : false,
```
Comment (iamareebjamal) [inline app/mixins/custom-form.js:55]: Track optional is not implemented on server yet. Revert to previous state
