### PR TITLE
fix: make some admin billing fields optional

### LINKED ISSUE #5106: Make contact name, phone and tax ID optional for invoice admin stetting
On admin billing info https://eventyay.com/admin/settings/billing change:
* make contact name optional
* make phone optional
* make tax ID optional

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #5106 
Screenshot from 2020-09-21 21-06-50

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
You still need to verify the validity of the phone number, but make it optional

File: app/components/forms/admin/settings/billing.js [hunk 1]
```diff
@@ -12,17 +12,22 @@ export default class Billing extends Component.extend(FormMixin) {
       delay  : false,
       on     : 'blur',
       fields : {
-        adminBillingContactName: {
-          identifier : 'adminBillingContactName',
+        adminBillingEmail: {
```
Comment (iamareebjamal) [inline app/components/forms/admin/settings/billing.js:15]: This was below phone rule. So please move it there. Try to make least amount of diff as possible to make it easy to review

**Review by iamareebjamal — APPROVED** [review]
