### PR TITLE
fix: creating events with same starting and ending time

### LINKED ISSUE #6117: Starting and Ending time of the event is same.
**Describe the bug**
I am able to create events with same starting and ending time, which should not happen because users can do spam by creating events.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/
2. Create Event by keeping starting and ending time same.
4. You will be able to create event and that's the error.

**Expected behaviour**
The ending time should be greater than starting time

**Screenshots**

see the Staring at and Ending at, they are both same.

Screenshot_2020-12-20 Live Events Open Event

### PR DESCRIPTION
**Pull request by Creatoon**
Fixes #6117 

#### Short description of what this resolves:
Previously we were able to create the events keeping the starting time and ending time same and this pr fixes that issue.

### Screenshot after changes
Screenshot_2020-12-25 Create an Event Open Event

#### Checklist 

- [YES ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ YES] My branch is up-to-date with the Upstream `development` branch.
- [ NOT CHECKED YET] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ NO] I have added tests that prove my fix is effective or that my feature works
- [ NOT REQUIRED] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Creatoon** [comment]
@iamareebjamal sir please review this pr.

File: app/components/forms/wizard/basic-details-step.js [hunk 1]
```diff
@@ -141,7 +141,14 @@ export default Component.extend(FormMixin, EventWizardMixin, {
     $.fn.form.settings.rules.checkMaxMinOrder = () => {
       return parseInt($('.ui.form').form('get value', 'ticket_min_order'), 10) <= parseInt($('.ui.form').form('get value', 'ticket_max_order'), 10);
     };
-
+    window.$.fn.form.settings.rules.checkValidTimeDifference = () => {
```
Comment (maze-runnar) [inline app/components/forms/wizard/basic-details-step.js:144]: remove window

File: app/components/forms/wizard/basic-details-step.js [hunk 2]
```diff
@@ -141,7 +141,14 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+      const STA = document.getElementsByName('start_time')[0].value.split(':');
+      const STIS = (parseInt(STA[0]) + parseInt(STA[1])) * 60;
+      const ETA = document.getElementsByName('end_time')[0].value.split(':');
+      const ETIS = (parseInt(ETA[0]) + parseInt(ETA[1])) * 60;
+      return STIS < ETIS;
```
Comment (maze-runnar) [inline app/components/forms/wizard/basic-details-step.js:149]: there should be an easy way for comparing times using moment.js . And please use varilable names as they are used rest of place.

Comment (Creatoon) [reply app/components/forms/wizard/basic-details-step.js]: @maze-runnar is it ok now?

File: app/components/forms/wizard/basic-details-step.js [hunk 3]
```diff
@@ -141,7 +141,10 @@ export default Component.extend(FormMixin, EventWizardMixin, {
     $.fn.form.settings.rules.checkMaxMinOrder = () => {
       return parseInt($('.ui.form').form('get value', 'ticket_min_order'), 10) <= parseInt($('.ui.form').form('get value', 'ticket_max_order'), 10);
     };
-
+    $.fn.form.settings.rules.checkValidTimeDifference = () => {
```
Comment (sachinchauhan2889) [inline app/components/forms/wizard/basic-details-step.js:144]: I am not sure but i think this can be done without using document. You can use ember for DOM. please try this.

**Review by sachinchauhan2889 — CHANGES_REQUESTED** [review]
1) remove codacy annotations.
2) It is not looking nice. make it looks same that in other validations example event name

**Comment by Creatoon** [comment]
@sachinchauhan2889 is this ok now.

Screenshot_2020-12-29 Create an Event Open Event

File: app/components/forms/wizard/basic-details-step.js [hunk 4]
```diff
@@ -141,7 +141,10 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+      return moment($("[name=start_time]")[0].value , 'HH:mm').isBefore(moment($("[name=end_time]")[0].value, 'HH:mm'));
```
Comment (sachinchauhan2889) [inline app/components/forms/wizard/basic-details-step.js:145]:
```suggestion
      return moment($('[name=start_time]')[0].value, 'HH:mm').isBefore(moment($("[name=end_time]")[0].value, 'HH:mm'));
```

File: app/components/forms/wizard/basic-details-step.js [hunk 5]
```diff
@@ -141,7 +141,10 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+    };
+
```
Comment (sachinchauhan2889) [inline app/components/forms/wizard/basic-details-step.js:147]:
```suggestion
```

File: app/components/widgets/forms/time-picker.js [hunk 6]
```diff
@@ -6,7 +6,7 @@ import { FORM_TIME_FORMAT } from 'open-event-frontend/utils/dictionary/date-time
 
 export default Component.extend({
 
-  classNames        : ['ui', 'calendar', 'time', 'picker', 'input', 'fluid', 'field'],
+  classNames        : ['ui', 'calendar', 'time', 'picker', 'input', 'fluid', 'field' , 'd-initial'],
```
Comment (sachinchauhan2889) [inline app/components/widgets/forms/time-picker.js:9]:
```suggestion
  classNames        : ['ui', 'calendar', 'time', 'picker', 'input', 'fluid', 'field', 'd-initial'],
```

**Review by sachinchauhan2889 — COMMENTED** [review]
working fine. and code also looks fine. please remove codacy errors. and resolve conflicts.

File: app/components/forms/wizard/basic-details-step.js (hunk 4 above)
Comment (Creatoon) [reply app/components/forms/wizard/basic-details-step.js:145]: @sachinchauhan2889  should i have to add a line break at the poin you sujjested?

**Comment by Creatoon** [comment]
@sachinchauhan2889 codancy conflicts has been resolved now , is there anything to improve.

**Comment by sachinchauhan2889** [comment]
still conflicts is there. you can check there is conflict in _helpers.scss.

**Comment by Creatoon** [comment]
@sachinchauhan2889  i am getting cors errors, i tried to solve this problem by adding proxies and installing the project itself more than 3 times. 
have you any way to resolve this issue.
Screenshot_2020-12-31 Screenshot

**Comment by Creatoon** [comment]
@sachinchauhan2889 please review.

**Review by sachinchauhan2889 — DISMISSED** [review]
works for me.

File: app/templates/components/widgets/forms/time-picker.hbs [hunk 7]
```diff
@@ -1,6 +1,3 @@
-{{#if this.icon}}
-  <i class="time icon"></i>
-{{/if}}
```
Comment (iamareebjamal) [inline app/templates/components/widgets/forms/time-picker.hbs:3]: Why

**Comment by Creatoon** [comment]
@iamareebjamal @sachinchauhan2889 previously icons were not showing on the website, that's why i thought to remove that , but now i fixed that and the icons are now showing. please review this and tell me so that i can improve.

Screenshot_2020-12-31 Create an Event Open Event

**Review by sachinchauhan2889 — APPROVED** [review]
@iamareebjamal sir, please review.

File: app/templates/components/widgets/forms/time-picker.hbs [hunk 8]
```diff
@@ -1,6 +1,4 @@
 {{#if this.icon}}
   <i class="time icon"></i>
 {{/if}}
-<div class="ui input">
```
Comment (iamareebjamal) [inline app/templates/components/widgets/forms/time-picker.hbs:4]: Why?

Comment (Creatoon) [reply app/templates/components/widgets/forms/time-picker.hbs:4]: Expected behaviour - Sir we can see that the "ui" amd "input" classes is being applied on the parent div of the input tag. Now we should put both the icon and the input field inside that div element.

Screenshot_2021-01-01 Input Semantic UI

Reality - but now what's happening is there is one div(having classes "ui" and "input") and inside that there is icon and input field (which is also nested in a div having classes "ui" and "input").

<div id="ember649" class="ui input calendar time picker fluid left icon ember-view"> 
     <i class="time icon"></i>
     <div class="ui input">
           <input name="start_time" placeholder="HH:MM" id="ember650" class="ember-text-field ember-view" type="text">
     </div>
</div>

And due to this the div containing input tag is overlapping the icon. and "THAT'S WHY TIME ICON IS HIDDEN FROM THE WEBSITE ITSELF"

The date picker is not having this issue because 

{{#if this.icon}}
  <i class="calendar icon"></i>
{{/if}}
<Input @type="text" @value={{value}} placeholder={{this.placeholder}} @name={{name}} @focus-out={{action "onChange"}} />

we can see that input tag is not inside the "ui input" div , the whole component have the class "ui input" ,
and that's why the date picker looks completely.

and sir that's why i removed the div because it was overlapping the icon which should not happen as we can see that from date picker.

Comment (Creatoon) [reply app/templates/components/widgets/forms/time-picker.hbs:4]: @sachinchauhan2889 please look at it , and correct me if i was unable to explain this behaviour.

File: app/templates/components/widgets/forms/time-picker.hbs [hunk 9]
```diff
@@ -1,6 +1,4 @@
 {{#if this.icon}}
   <i class="time icon"></i>
 {{/if}}
```
Comment (sachinchauhan2889) [inline app/templates/components/widgets/forms/time-picker.hbs:3]:
```suggestion

```

File: app/templates/components/widgets/forms/time-picker.hbs [hunk 10]
```diff
@@ -1,6 +1,4 @@
...
-<div class="ui input">
-  <Input @type="text" @value={{value}} placeholder={{this.placeholder}} @name={{name}} @focus-out={{action "onChange"}} />
-</div>
\ No newline at end of file
+<Input @type="text" @value={{value}} placeholder={{this.placeholder}} @name={{name}} @focus-out={{action "onChange"}} />
```
Comment (sachinchauhan2889) [inline app/templates/components/widgets/forms/time-picker.hbs:4]:
```suggestion
<div class="ui {{if this.icon 'left icon'}} input">
  {{#if this.icon}}
    <i class="time icon"></i>
  {{/if}}
  <Input @type="text" @value={{value}} placeholder={{this.placeholder}} @name={{name}} @focus-out={{action "onChange"}} />
</div>
```

**Review by sachinchauhan2889 — CHANGES_REQUESTED** [review]
commit my suggested changes.

**Comment by Creatoon** [comment]
@iamareebjamal sir , is there any issue with this pr, tell me so that i can improve
