### PR TITLE
fix: Fix the Date filters in explore route

### LINKED ISSUE #1296: Date filters don't work in Explore Events tab
**Describe the bug**
Date filters dont work in Explore Events tab

**To Reproduce**
1. Go to explore events
2. Try the date filters

**Expected behavior**
Filters should work

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

### PR DESCRIPTION
**Pull request by mayank8318**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixes the date filters in the explore route

#### Changes proposed in this pull request:

- Give the user option of selecting dates manually instead of providing options like Today, yesterday etc.

Fixes #1296

### CODE REVIEW

File: app/controllers/explore.js [hunk 1]
```diff
@@ -74,20 +70,32 @@ export default Controller.extend({
...
     }
 
-    return this.get('store').query('event', {
+    let filteredResults = [];
+
+    await this.get('store').query('event', {
       sort   : 'starts-at',
       filter : filterOptions
+    }).then(results => {
+      filteredResults = results.filter(event => {
```
Comment (niranjan94) [inline app/controllers/explore.js]: Please do this on the server side.

Comment (niranjan94) [inline app/controllers/explore.js]: To be done on the server-side.

https://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html

**Comment by mayank8318** [comment]
@niranjan94 made the changes :)

File: app/components/explore/side-bar.js [hunk 2]
```diff
@@ -1,13 +1,15 @@
...
+import { observer } from '@ember/object';
+import moment from 'moment';
 
 export default Component.extend({
 
   classNames: ['ui', 'fluid', 'explore', 'vertical', 'menu'],
 
-  dateRanges: computed(function() {
-    return getDateRanges.bind(this)();
+  dateChange: observer('start_date', 'end_date', function() {
```
Comment (niranjan94) [inline app/components/explore/side-bar.js]: Do not use an observer for this. Always use an observer only when there's really no other option.

In this case, you should be using a one way binding for the date picker and make it such that it can accept a call back action with the selected date value. (similar to how the ui-dropdown component works) In that action you can do whatever you do here.

This way the data also flows correctly and is easy to catch bugs.

Observers can easily cause weird issues  that there's even an eslint rule to prevent its usage :P https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-observers.md

Comment (mayank8318) [reply app/components/explore/side-bar.js]: @niranjan94 But I will still need an observer in the date-picker, right? I think I am not getting the required implementation here. I need something like this in the date-picker right -
```javascript
[observe for change in start_date] {
  this.sendAction('callback_name');
}
```

**Comment by mayank8318** [comment]
@niranjan94 changed the implementation, please review :)

File: app/templates/components/explore/side-bar.hbs [hunk 3]
```diff
@@ -54,37 +54,31 @@
...
+  <div class="content menu">
+    <div class="explore sub menu">
+      <div class="ui form">
+        <div class="grouped fields">
+          <div class="item field">
+            <label class="required" for="start_date">{{t 'Starts'}}</label>
+            {{widgets/forms/date-picker type='text'
+                                        rangePosition='start'
+                                        value=start_date
+                                        valueCheck=end_date
```
Comment (niranjan94) [inline app/templates/components/explore/side-bar.hbs]: Remove this property. date-picker does not need this.

File: app/templates/components/explore/side-bar.hbs [hunk 4]
```diff
@@ -54,37 +54,31 @@
...
+                                        valueCheckCallback=(action 'dateValidate')
```
Comment (niranjan94) [inline app/templates/components/explore/side-bar.hbs]: Call it it `onChange` to match with other components. The callback should receive the date selected in the datepicker.

**Comment by mayank8318** [comment]
@niranjan94 made the changes :)

File: app/controllers/explore.js [hunk 5]
```diff
@@ -37,6 +38,78 @@ export default Controller.extend({
     );
   }),
 
+  dateFilterWithEndDate: computed('start_date', 'end_date', function() {
+    return EmberObject.create(
```
Comment (niranjan94) [inline app/controllers/explore.js]: Why do you need this to be an `EmberObject` ? Just a plain object would do.

File: app/controllers/explore.js [hunk 6]
```diff
@@ -37,6 +38,78 @@ export default Controller.extend({
...
+              ]
+            }
+          ]
+      }
+
+    );
+  }),
+
+  dateFilterBasic: computed('start_date', function() {
+    return EmberObject.create(
```
Comment (niranjan94) [inline app/controllers/explore.js]: Why do you need this to be an `EmberObject` ? Just a plain object would do.

File: app/controllers/explore.js [hunk 7]
```diff
@@ -37,6 +38,78 @@ export default Controller.extend({
...
+            op   : 'ge',
+            val  : this.get('start_date')
+          }
+        ]
+      }
+    );
+  }),
+
   typeFilter: computed('event_type', function() {
     return EmberObject.create(
```
Comment (niranjan94) [inline app/controllers/explore.js]: Why do you need this to be an `EmberObject` ? Just a plain object would do.

File: app/controllers/explore.js [hunk 8]
```diff
@@ -52,42 +125,44 @@ export default Controller.extend({
...
     let eventType = this.get('event_type');
+    let endDate = this.get('end_date');
     let filterOptions = this.get('filterOptions').slice(0, 2);
 
     if (category) {
       filterOptions.pushObject(this.get('categoryFilter'));
 
       if (subCategory) {
-        this.get('filterOptions').pushObject(this.get('subCategoryFilter'));
+        filterOptions.pushObject(this.get('subCategoryFilter'));
```
Comment (niranjan94) [inline app/controllers/explore.js]: Use native `push`

**Comment by mayank8318** [comment]
@niranjan94 made the changes :)

**Comment by mayank8318** [comment]
@niranjan94 But I am forming the filters dynamically right? How will I handle that?

**Comment by niranjan94** [comment]
> @niranjan94 But I am forming the filters dynamically right? How will I handle that?

You can still do that based on the params inside the `model` fn in the route right?

**Comment by mayank8318** [comment]
@niranjan94 Oh okay so if `param` contains that string say category, for example, I know that the user has selected a particular category and then I can add it to the filter option. Is this right?

**Comment by niranjan94** [comment]
@mayank8318 `params` is an object. Its going to contain the values of all the query params that were defined. 

Example,

```
{
 	category: "whatever",
    sub_category: "whatever",
    event_type: "whatever",
    from_date: "whatever",
    to_date: "whatever"
}
```

You will be doing exactly what you're already doing within the computed properties, except, it'll be within the `model` fn. Make sure the `queryParams` array on the controller contains all of them and the the queryParams definiton on the route contains `refreshModel` as `true` for all the params. 

For reference: 
- https://guides.emberjs.com/release/routing/query-params/
- https://guides.emberjs.com/release/routing/query-params/#toc_opting-into-a-full-transition

**Comment by mayank8318** [comment]
@niranjan94 Yes, I am able to implement that but it refreshes the page every time some filter is changed. I don't think this is a good user experience. For eg, if I open the categories drop down and click on some category, the whole page is refreshed. I get the desired search results but I have to restart my searching process by re-clicking on the dropdown icon.

**Comment by mayank8318** [comment]
@niranjan94 No, the list isn't getting updated

**Comment by niranjan94** [comment]
Make sure you use `filteredEvents` and not `model.filteredEvents` in the template/controller.

**Comment by mayank8318** [comment]
@niranjan94 Oh ok now it is working. So, just out of curiosity - `controller.set('filteredEvents', model.filteredEvents);` just initialises the filteredEvents variable of the controller right?

**Comment by niranjan94** [comment]
@mayank8318 yes. Correct

File: app/templates/explore.hbs [hunk 9]
```diff
@@ -1,6 +1,6 @@
 <div class="ui stackable grid">
   <div class="four wide column">
-    {{explore/side-bar model=model category=category sub_category=sub_category event_type=event_type date_range=date_range}}
+    {{explore/side-bar model=model category=category sub_category=sub_category event_type=event_type start_date=start_date end_date=end_date}}
```
Comment (niranjan94) [inline app/templates/explore.hbs]: use camelCase

```hbs
{{explore/side-bar model=model category=category subCategory=sub_category eventType=event_type startDate=start_date endDate=end_date}}
```

Comment (mayank8318) [reply app/templates/explore.hbs]: Should I change it everywhere?

Comment (mayank8318) [reply app/templates/explore.hbs]: I mean even the query params?

Comment (mayank8318) [reply app/templates/explore.hbs]: @niranjan94 These are not in camel case because the template is already using the camel-case version for iterating - 
```javascript
 {{#if (eq category Category.name)}}
          {{#each Category.subTopics as |subCategory|}}
            <a href="#"
               class="link inner item {{if (eq sub_category subCategory.slug) 'active'}}"
              {{action 'selectCategory' Category.name subCategory.slug}}>
              {{subCategory.name}}
            </a>
          {{/each}}
        {{/if}}
```

Comment (niranjan94) [reply app/templates/explore.hbs]: All query params - snake_case
Every other js variable - camelCase

Comment (mayank8318) [reply app/templates/explore.hbs]: But what about the camel cased variables(same name) in the template?

Comment (niranjan94) [reply app/templates/explore.hbs]: Which template ? 
- If it is on the route's template, and it refers to the query param variable snake_case if fine since its the same variable.
- Anywhere else, camelCase

Comment (mayank8318) [reply app/templates/explore.hbs]: The `explore/side-bar` template, the one which contains all the filtering options(FE wise). We are passing the values of the query params to it in the highlighted line. The problem is that the name of the query params is same as the model property if written in camel case. That's why we are passing variables in snake_case only. I have already pointed out an example(variable `sub_category` and `subCategory`) I will have to rename that `subCategory` to something else maybe `subCategoryItem`. Is that okay?

Variables which have this problem -> `sub_category` and `event_type`. Rest can be converted to camel case without a problem.

**Comment by mayank8318** [comment]
@niranjan94 I have converted `start_date` and `end_date` to camel case

**Comment by mayank8318** [comment]
@CosmicCoder96 @niranjan94 @ritikamotwani @pradeepgangwar Please review

**Comment by mayank8318** [comment]
@ritikamotwani @srv-twry @pradeepgangwar @bhaveshAn @mishuvs Please test the functionality here - 
https://deploy-preview-1312--open-event-frontend.netlify.com/explore

**Comment by ritikamotwani** [comment]
@mayank8318 
image
This is the UI for the date filtering for the explore route and to filter according to the start and end date you have to click on the custom dates and the accordion appears
image
In this PR for the date filtering you have to enter the start and the end date none of the other things is there.

**Comment by mayank8318** [comment]
@ritikamotwani Yes correct. IMO this makes more sense since we were giving this option anyways.

**Comment by mayank8318** [comment]
That extra feature can be added in another PR. This implements the basic functionality.

**Comment by ritikamotwani** [comment]
@mayank8318 the current UI makes more sense as if some user wants to get tomorrow's event clicking on tomorrow will be more convenient for him than entering the start and end date! This basic filtering can be reviewed for now but an issue should be created for implementing it on the basis of the current UI

**Comment by mayank8318** [comment]
@ritikamotwani ok I will make an issue for that

**Comment by ritikamotwani** [comment]
@mayank8318 a doubt
I tried filtering events from 13th July to 14th July 
image
I am getting events of 14th June too 
image

**Comment by pradeepgangwar** [comment]
@ritikamotwani I had the same doubt. Actually the end date of that event should be between the filtered dates. So implementation is like this: If any portion of event timeline falls between the selected time period then event is displayed.

**Comment by ritikamotwani** [comment]
@pradeepgangwar okay!

**Comment by mayank8318** [comment]
@pradeepgangwar right! If any portion of the event timeline falls between the selected time period then that event is considered active and included in the list.

**Comment by srv-twry** [comment]
@niranjan94 Merged it. In case you find anything wrong, you can follow up by creating an issue or in the channel. Thanks.
