### PR TITLE
fix: Show social links as icon

### LINKED ISSUE #5785: Public Schedule Page: Make Social Links into Icons and Moce Date/Time, Social Icons and Links to Top Right Menu
Date/time, social links and web links are currently below the tracks and session filters, which is not perfect. Also design can be made more clearer. Please change this as follows:
1. Move date/time, social links, web links to top right side area (but not the twitter box itself) on schedule pages
2. Change social links into square boxes similar to sched (compare https://ocs2020.sched.com/). Also ensure it works if we have many social links, e.g. if there are too many that do not fit on one line it should go over two lines.
3. Keep website links as is 
4. Also test this works well on mobile

Current implementation, e.g. here https://eventyay.com/e/1f720482/schedule
Screenshot from 2020-11-27 17-57-01

Compare to sched
Screenshot from 2020-11-27 17-55-41

### LINKED ISSUE #5824: Public Schedule Social Links: Create a CSS icon for Event Site
As a follow up to PR https://github.com/fossasia/open-event-frontend/pull/5812 the event site link is the only link without an icon. 

Please create an icon using CSS. 

An example icon is below:

bitmap

It should be positioned with those other icons.

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #5785
Fixes #5824 

__screenshots__

aaaaaaaaaaaaaa njew sachin

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sachinchauhan2889** [comment]
confused about social links icons.
semantic ui provide only buttons for only few social links mentioned in our projects. example :- for twitter, facebook, linked etc. but not for github, gitter etc..
it looks like this. 

icons 1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

icons 2




__we can also use this icon buttons..__
icons 3


please suggest which icon buttons needed from above choices

**Comment by daretobedifferent18** [comment]
I think if UI-semantic does not have all the social link button then u should go with the one where all eh buttons are the same so that style is consistent for all buttons

**Comment by iamareebjamal** [comment]
You can always set the button color using CSS. For links present in `socialMediaIdentifier`, please use an icon, for others let them be as they are now. 

So, use this style



And set color using classes or CSS, for eg, GitHub black, GitLab orange, Gitter pink

For custom links, show them as they are shown already

**Comment by sachinchauhan2889** [comment]
@iamareebjamal sir, please review

**Review by daretobedifferent18 — COMMENTED** [review]
Screenshot from 2020-12-02 18-30-35
Pls make all the boxes to be of the same size

File: app/utils/dictionary/social-media.ts [hunk 1]
```diff
@@ -27,6 +27,19 @@ export const socialMediaSites: SocialMedia[] = socialMediaIdentifiers.map((ident
 
 export interface SocialMediaMap { [key: string]: SocialMedia }
 
+export const buttonColor: { [key: string]: string } = {
+  'github'        : 'black',
```
Comment (iamareebjamal) [inline app/utils/dictionary/social-media.ts:31]: No need of quotes in keys without space

File: app/templates/components/public/social-links.hbs [hunk 2]
```diff
@@ -1,25 +1,31 @@
...
-        <a href="{{socialLink.link}}" target="_blank" rel="noopener nofollow">{{socialLink.displayName}}</a>
+    {{#if (eq socialLink.normalizedName 'globe')}}
+      <div class="item">
+        <i class="fitted {{socialLink.normalizedName}} disabled icon"></i>
+        <div class="content">
+          <a href="{{socialLink.link}}" target="_blank" rel="noopener nofollow">{{socialLink.displayName}}</a>
+        </div>
       </div>
-    </div>
+    {{/if}}
```
Comment (iamareebjamal) [inline app/templates/components/public/social-links.hbs:29]: Why looping 2 times, use if else in a single loop

Comment (sachinchauhan2889) [reply app/templates/components/public/social-links.hbs:29]: @iamareebjamal sir, 
variable __socialLinks__ contains both links socialMedia links and custom URLs. 
i have made a flex-box for icon buttons.  first of all I inserted __event-site-URL__. then i traverse all __socialLinks__ and only select __SocialMedia links__ to put inside flex-box as icon buttons. then outside of flex-box i traverse all __socialLinks__ and only select __Custom-URLs__ and list them. how can i do this in one loop. 
we can store __custom-URLs__ in a variable while first loop and use them outside felx-box. this will be complex in hbs. thats why i use 2 loops.

**Comment by sachinchauhan2889** [comment]
new aaaaaaaaaaaa

File: app/templates/components/public/social-links.hbs (hunk 2 above)
Comment (iamareebjamal) [reply app/templates/components/public/social-links.hbs:29]: OK, I understand now

**Comment by iamareebjamal** [comment]
@mariobehling Shouldn't we show the custom links like we previously did?

Like if there are 4 custom links:
Page, Support, About, Contact

They all will show `Event Site`. The UI will be confusing and there will be no use of freeform input of site name

**Comment by iamareebjamal** [comment]
@sachinchauhan2889 Please just show social media links in this PR and continue showing custom links in previous form. We'll discuss the other issue in next PR

**Comment by sachinchauhan2889** [comment]
> @sachinchauhan2889 Please just show social media links in this PR and continue showing custom links in previous form. We'll discuss the other issue in next PR

@iamareebjamal sir, customs links are already in previous form. you can check

**Comment by iamareebjamal** [comment]
OK, I understand it completely now.

**Comment by mariobehling** [comment]
Very nice! Thank you.
