### PR TITLE
fix: Refactor login-form according to flask jwt extended changes

### LINKED ISSUE #3300: Flask JWT extended: Incorrect login test failing after refactor. Travis is failing
Error response structure has changed.

### PR DESCRIPTION
**Pull request by CosmicCoder96**
Fixes #3300 

Refactors the login form according to flask jwt extended related refactor on the server to fix the tests,
and update the syntax in general.

### CODE REVIEW

File: app/components/forms/login-form.js [hunk 1]
```diff
@@ -38,70 +39,73 @@ export default Component.extend(FormMixin, {
...
+  async auth(provider) {
+    if (provider === 'facebook') {
       try {
-        if (provider === 'facebook') {
-          this.loader.load('/auth/oauth/facebook')
-            .then(async response => {
-              window.location.replace(response.url);
-            });
+        let response = await this.loader.load('/auth/oauth/facebook');
+        window.location.replace(response.url);
```
Comment (kushthedude) [inline app/components/forms/login-form.js]: @CosmicCoder96 Do we need it for now, as O-auth is not implemented properly on server
