### PR TITLE
fix: remove continuous loading of create speaker page

### LINKED ISSUE #5883: Organizer is unable to Add/Create a Speaker
**Describe the bug**
This bug is related to an organizer feature. When the event organizer added a new speaker and saved. The page froze, kept loading. 

**To Reproduce**
1. Go to 'speaker create form' https://eventyay.com/events/ae73f280/speakers/create
2. Enter the details
3. Save

Screenshot from 2020-12-03 09-32-42

**Desktop (please complete the following information):**
 - Ubuntu 18.04, Chrome

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #5883 

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sachinchauhan2889** [comment]
deployment is slow. but working fine.
user able to add speakers with no email id. 
and continuous loading of page after speaker saved or after error is removed.


screebg

File: app/controllers/events/view/speakers/create.js [hunk 1]
```diff
@@ -24,9 +24,11 @@ export default class extends Controller {
       await this.model.speaker.save();
       this.notify.success(this.l10n.t('Your session has been saved'));
       this.transitionToRoute('events.view.speakers', this.model.event.id);
+      this.set('isLoading', false);
     } catch (e) {
       console.error('Error while saving session', e);
       this.notify.error(this.l10n.t('Oops something went wrong. Please try again'));
+      this.set('isLoading', false);
```
Comment (maze-runnar) [inline app/controllers/events/view/speakers/create.js:31]: don't add this.set('isLoading', false); in two places. Add a `finally` block

**Review by maze-runnar — APPROVED** [review]
