### PR TITLE
fix: AccessURL generated is fixed

### LINKED ISSUE #3827: Access Code: Ticket does not show up
The access code function is to enable ticket buyers to see hidden ticket (which is configured in the tickets wizard step 1). Currently adding an access code does not show the hidden ticket, when using the access code link.

Screenshot from 2020-01-21 07-57-37

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3827

### CODE REVIEW

File: app/components/forms/events/view/create-access-code.js [hunk 1]
```diff
@@ -102,7 +102,7 @@ export default Component.extend(FormMixin, {
   accessLink : computed('data.code', function() {
     const params = this.get('router._router.currentState.routerJsState.params');
     const origin = this.get('fastboot.isFastBoot') ? `${this.get('fastboot.request.protocol')}//${this.get('fastboot.request.host')}` : location.origin;
-    let link = origin + this.router.urlFor('public', params['events.view'].event_id, { queryParams: { access_code: this.get('data.code') } });
+    let link = origin + this.router.urlFor('public', params['events.view'].event_id, { queryParams: { code: this.get('data.code') } });
```
Comment (snitin315) [inline app/components/forms/events/view/create-access-code.js]: I guess we are using `code` for both `discount code` as well .

Comment (snitin315) [reply app/components/forms/events/view/create-access-code.js]: Screenshot from 2020-01-21 21-39-26
