### PR TITLE
fix: Remove awaits in loop

### LINKED ISSUE #3916: Remove awaits in loop
https://eslint.org/docs/rules/no-await-in-loop

### PR DESCRIPTION
**Pull request by gittysachin**
Fixes #3916 

#### Short description of what this resolves:

If we're performing an operation on each element of an iterable and ```await``` is a part of each operation then the program is not taking full advantage of parallelization benefits of ```async```/```await```. Each successive operation will not start until the previous one has completed.

Using ```Promise.all()``` to ```await``` all the requests that were kicked during the loop to finish will create all the promises at once.

This pull request fixes this issue.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           

Complexity increasing per file
==============================
- app/mixins/event-wizard.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)

File: app/mixins/event-wizard.js [hunk 1]
```diff
@@ -48,28 +48,29 @@ export default Mixin.create(MutableArray, CustomFormMixin, {
...
       } catch (e) {
         if (!(e.errors && e.errors.length && e.errors.length > 0 && e.errors[0].status === 404)) {
           // Lets just ignore any 404s that might occur. And throw the rest for the caller fn to catch
           throw e;
         }
       }
-    }
+    }));
+    propsToSave.map((property, index) => {
+      promises.then(promise => { data[property] = promise[index] });
```
Comment (iamareebjamal) [inline app/mixins/event-wizard.js]: These are already resolved promises. No need to then these promises

File: app/mixins/event-wizard.js [hunk 2]
```diff
@@ -48,28 +48,29 @@ export default Mixin.create(MutableArray, CustomFormMixin, {
...
+        return event.get(property);
       } catch (e) {
         if (!(e.errors && e.errors.length && e.errors.length > 0 && e.errors[0].status === 404)) {
           // Lets just ignore any 404s that might occur. And throw the rest for the caller fn to catch
           throw e;
         }
       }
-    }
+    }));
+    propsToSave.map((property, index) => {
```
Comment (iamareebjamal) [inline app/mixins/event-wizard.js]: Use for of loop

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           

Complexity increasing per file
==============================
- app/mixins/event-wizard.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)

**Comment by gittysachin** [comment]
Sorry for the inconvenience, I'm having problems while using rebase. I'm learning. I'll not make these mistakes in the future.

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           

Complexity increasing per file
==============================
- app/mixins/event-wizard.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)

**Comment by gittysachin** [comment]
@iamareebjamal I did everything right this time besides the force push. Then why it is showing that the codecov/patch was not successful?

File: app/mixins/event-wizard.js [hunk 3]
```diff
@@ -48,28 +48,29 @@ export default Mixin.create(MutableArray, CustomFormMixin, {
...
+        return event.get(property);
       } catch (e) {
         if (!(e.errors && e.errors.length && e.errors.length > 0 && e.errors[0].status === 404)) {
           // Lets just ignore any 404s that might occur. And throw the rest for the caller fn to catch
           throw e;
         }
       }
+    }));
+    for (const [index, property] of propsToSave.entries()) {
+      data[property] = promises[index];
```
Comment (iamareebjamal) [inline app/mixins/event-wizard.js]: You need to assign only if it was successful

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           

Complexity increasing per file
==============================
- app/mixins/event-wizard.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)

File: app/mixins/event-wizard.js [hunk 4]
```diff
@@ -48,28 +48,31 @@ export default Mixin.create(MutableArray, CustomFormMixin, {
   async saveEventData(propsToSave = []) {
     const event = this.get('model.event');
     const data = {};
-    for (const property of propsToSave) {
+    const promises = await Promise.all(propsToSave.map(property => {
```
Comment (iamareebjamal) [inline app/mixins/event-wizard.js]: Use Promise.allSettled

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           

Complexity increasing per file
==============================
- app/mixins/event-wizard.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)

File: app/mixins/event-wizard.js (hunk 4 above)
Comment (gittysachin) [reply app/mixins/event-wizard.js]: The last commit didn't pass. I replaced Promise.all with Promise.allSettled. What else should I do?

Comment (iamareebjamal) [reply app/mixins/event-wizard.js]: See what allSettled returns

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           

Complexity increasing per file
==============================
- app/mixins/event-wizard.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)

File: app/mixins/event-wizard.js [hunk 5]
```diff
@@ -48,28 +48,33 @@ export default Mixin.create(MutableArray, CustomFormMixin, {
...
       } catch (e) {
         if (!(e.errors && e.errors.length && e.errors.length > 0 && e.errors[0].status === 404)) {
           // Lets just ignore any 404s that might occur. And throw the rest for the caller fn to catch
           throw e;
         }
       }
-    }
+    }));
+    results.then(promises => {
+      for (const [index, property] of propsToSave.entries()) {
```
Comment (iamareebjamal) [inline app/mixins/event-wizard.js]: No need to extract index

Comment (gittysachin) [reply app/mixins/event-wizard.js]: Then how can I assign the value of ```event.get(property)``` without using the ```index```?

Comment (iamareebjamal) [reply app/mixins/event-wizard.js]: By using property

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929588&bid=16306241)
