### PR TITLE
fix: updates the status for  orders

### LINKED ISSUE #2951: Event Organizer Orders Page: Expired Orders Showing up as Placed Orders
Placed Orders are orders that are paid through offline methods. If an event has cheque payment for example an order can be made with a choice "placed order". The user can then pay it offline, at the event or transfer it outside of the system. 

Currently orders are showing up in events that are expired and are not placed. 

Pending orders should expire and just get move to the category "Expired" after 72 hours. Expired orders should not show up as finished "placed" orders.

Screenshot from 2019-05-18 18-39-05

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Fixes #2951 

#### Short description of what this resolves:
Tickets that are unpaid are showing up as placed. Expected: Should show up as "Pending" and Expire after 3 days

#### Changes proposed in this pull request:
 - Updates the status of offline paid orders to `Placed`
 - Updates the status of online paid orders to `Pending` till payment is made.

_Completed Order_
Screenshot_2019-05-21 Completed Order -bffa6fb2-f09d-4f0a-ba82-35bca3121f75 Orders Open Event

_Placed Order_
Screenshot_2019-05-21 Placed Order -6e862478-d1a2-40e3-9ea6-8621528d0c13 Orders Open Event

_Pending Order_
Screenshot_2019-05-21 Placed Order -6c7479a6-220c-4baa-8346-fbabfe74a973 Orders Open Event

_Expired Order_
Screenshot_2019-05-21 Expired Order -be57dbe6-ff3d-4e09-b7e5-99680868db5b Orders Open Event

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@uds5501 there will be a server side PR required just to make few changes -
 - update scheduler time constraint
 - ensure that `placed` order also gets similar `completed_at` updation, mailing and notification as it was getting earlier.

File: app/controllers/orders/new.js [hunk 1]
```diff
@@ -10,10 +10,12 @@ export default Controller.extend({
         for (const attendee of attendees ? attendees.toArray() : []) {
           await attendee.save();
         }
-        if (paymentMode === 'free' || paymentMode === 'bank' || paymentMode === 'cheque' || paymentMode === 'onsite') {
+        if (paymentMode === 'free') {
           order.set('status', 'completed');
-        } else {
+        } else if (paymentMode === 'bank' || paymentMode === 'cheque' || paymentMode === 'onsite') {
```
Comment (pradeepgangwar) [inline app/controllers/orders/new.js]: @shreyanshdwivedi What about the online payment orders? They should also come under placed. This code will push them to ending state and error will be generated.

Comment (shreyanshdwivedi) [reply app/controllers/orders/new.js]: @pradeepgangwar it is the demand of the issue to mark online payment orders as `Pending` till the payment is completed. I'm currently fixing the errors which are generated due to this change. Will push them in half an hour.

Comment (pradeepgangwar) [reply app/controllers/orders/new.js]: What I see in the code is 

```js
.catch(e => {
            order.set('status', 'pending');
            this.get('notify').error(this.get('l10n').t(` ${e} Oops something went wrong. Please try again`));
          })
          .finally(() => {
            this.set('isLoading', false);
});
```

How will you redirect user to payment page?

Comment (pradeepgangwar) [reply app/controllers/orders/new.js]: There is no code block that handles `pending` case.

Comment (shreyanshdwivedi) [reply app/controllers/orders/new.js]: @pradeepgangwar I've updated the files. Now you can see this condition - 
```js
await order.save()
          .then(order => {
            if (order.status === 'pending' || order.status === 'placed') {
              this.get('notify').success(this.get('l10n').t('Order details saved. Please fill the payment details'));
              this.transitionToRoute('orders.placed', order.identifier);
            }
```
There might be a number of bugs still present. I'll have to take a closer look

File: app/controllers/orders/new.js [hunk 2]
```diff
@@ -10,14 +10,16 @@ export default Controller.extend({
...
           order.set('status', 'placed');
+        } else {
+          order.set('status', 'pending');
         }
         await order.save()
           .then(order => {
-            if (order.status === 'placed') {
+            if (order.status === 'pending' || order.status === 'placed') {
```
Comment (CosmicCoder96) [inline app/controllers/orders/new.js]: @shreyanshdwivedi If the order status is placed, ergo it was an order via bank cheques or something, why would we ask t fill payment details?

File: app/components/orders/order-summary.js [hunk 3]
```diff
@@ -14,6 +14,10 @@ export default Component.extend(FormMixin, {
     );
   }),
 
+  orderStatus: computed('data.status', function() {
```
Comment (CosmicCoder96) [inline app/components/orders/order-summary.js]: just use this.data.status wherever this is required, this is redundant.

File: app/controllers/orders/new.js (hunk 2 above)
Comment (shreyanshdwivedi) [reply app/controllers/orders/new.js]: @CosmicCoder96 I agree. It was present earlier. I'll update it :)

File: app/components/orders/order-summary.js (hunk 3 above)
Comment (shreyanshdwivedi) [reply app/components/orders/order-summary.js]: Updating it now

File: app/controllers/orders/new.js [hunk 4]
```diff
@@ -15,23 +15,25 @@ export default Controller.extend({
...
         }
         await order.save()
           .then(order => {
-            if (order.status === 'placed') {
+            if (order.status === 'pending') {
               this.get('notify').success(this.get('l10n').t('Order details saved. Please fill the payment details'));
-              this.transitionToRoute('orders.placed', order.identifier);
-            } else if (order.status === 'completed') {
+              this.transitionToRoute('orders.pending', order.identifier);
+            } else if (order.status === 'completed' || order.status === 'placed') {
```
Comment (pradeepgangwar) [inline app/controllers/orders/new.js]: Since both of them go to same route, can we make some changes to template to differentiate between the `completed` and `placed` orders?

Comment (shreyanshdwivedi) [reply app/controllers/orders/new.js]: Currently, this is the UI for `orders.view` route. 
Screenshot_2019-05-20 Completed Order -e9ded88c-f393-4cb9-aeee-1d00471b69ff Orders Open Event

For Completed orders, we can leave it the same and for placed orders, we can replace `Your order completed successfully.` to `Your order placed successfully.`  and replace `SUCCESS` with `PLACED`. Your thought? @pradeepgangwar

Comment (pradeepgangwar) [reply app/controllers/orders/new.js]: Sounds good, but i guess we need more details.

- Since placed order contain one or more kind of payment method (bank, cheque, onsite etc.), what we can do is include a comopnent below that shows the payment details i.e. What is the payment mode and how to pay for that.
- We can use following details to make user aware about how he should be paying onsite or via bank. https://github.com/fossasia/open-event-frontend/blob/0cafcc2bcddf53de0358e70b6bfaaf2f469d7bd1/app/models/event.js#L64-L67

Comment (shreyanshdwivedi) [reply app/controllers/orders/new.js]: @pradeepgangwar it was already being displayed. I've attached images to PR description now. Please give it a look

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 @pradeepgangwar I've updated the color scheme like we decided
```
Expired -> red
Placed -> blue
Completed -> green 
Pending -> orange 
```
Please review

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 as corresponding server PR (https://github.com/fossasia/open-event-server/issues/5926) is merged, can you please review this asap, otherwise the changes applied on server might break on local without these changes :)

File: app/templates/components/orders/order-summary.hbs [hunk 5]
```diff
@@ -1,23 +1,31 @@
 <div class="ui segments">
   {{#if (eq session.currentRouteName 'orders.view')}}
-    <div class="ui green inverted segment center aligned">
+    <div class="ui {{if (eq data.status 'completed') 'green' 'blue'}} inverted segment center aligned">
       <div class="ui inverted mini statistic horizontal">
         <div class="value">
-          Success
+          {{#if (eq data.status 'completed')}}
+            Success
```
Comment (CosmicCoder96) [inline app/templates/components/orders/order-summary.hbs]: translation helpers.

File: app/templates/components/orders/order-summary.hbs [hunk 6]
```diff
@@ -1,23 +1,31 @@
...
+          {{else}}
+            Placed
```
Comment (CosmicCoder96) [inline app/templates/components/orders/order-summary.hbs]: translation helpers.

File: app/templates/components/orders/order-summary.hbs [hunk 7]
```diff
@@ -1,23 +1,31 @@
...
     </div>
   {{/if}}
-  {{#if (eq session.currentRouteName 'orders.placed')}}
-    <div class="ui blue inverted segment center aligned">
+  {{#if (eq session.currentRouteName 'orders.pending')}}
+    <div class="ui orange inverted segment center aligned">
       <div class="ui inverted mini statistic horizontal">
         <div class="value">
-          Placed
+          Pending
```
Comment (CosmicCoder96) [inline app/templates/components/orders/order-summary.hbs]: translation helpers.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I've added missing translation helpers. 
`Initializing` is just an intermediate status. Once the form is submitted, the status is updated to either Pending, Placed or Completed. Therefore the color isn't required for this status
Regarding ES6 getters, do you want me to update all the getters in all the file related to this PR itself, as I haven't added any?

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 you're absolutely right. I just checked, the status is getting updated to initializing. Pushing the changes
Also, I've added 3 new getters. Should I update it or will it be covered in the refactoring PR?

**Comment by CosmicCoder96** [comment]
Yeah please change only the new ones.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I've pushed changes. BTW what I thought to be getters are not exactly getters. They all are something like - `this.get('l10n').t(`Pending Order -${order}`)`. please review

File: app/routes/orders/view.js [hunk 8]
```diff
@@ -3,7 +3,11 @@ import Route from '@ember/routing/route';
 export default Route.extend({
   titleToken(model) {
     var order = model.order.get('identifier');
-    return this.get('l10n').t(`Completed Order -${order}`);
+    if (model.order.status === 'completed') {
+      return this.get('l10n').t(`Completed Order -${order}`);
```
Comment (CosmicCoder96) [inline app/routes/orders/view.js]: `return this.l10n.t(...)`

File: app/routes/orders/view.js [hunk 9]
```diff
@@ -3,7 +3,11 @@ import Route from '@ember/routing/route';
...
+    } else if (model.order.status === 'placed') {
+      return this.get('l10n').t(`Placed Order -${order}`);
```
Comment (CosmicCoder96) [inline app/routes/orders/view.js]: `return this.l10n.t(...)`

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I've fixed the merge conflicts. Please review

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar @ritikamotwani please review
