### PR TITLE
fix: don't jump to main page or step 3 in wizard

### LINKED ISSUE #5187: Create Event: After Step 1 it "Next" jumps to Step 3
When an organizer creates an event after the wizard step 1 the wizard jumps to step 3. Expected: After step 1 it should go to "Additional Information" step 2.

Screenshot from 2020-09-29 18-39-54

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #5187 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/routes/events/view/edit.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ export default class EditRoute extends Route.extend(AuthenticatedRouteMixin, Eve
 
     const event = this.modelFor('events.view');
     const { currentUser } = this.authManager;
-    if (!(currentUser.isAnAdmin || currentUser.email === event.owner.get('email') || event.organizers.includes(currentUser)
+    if (!(currentUser.isAnAdmin || (currentUser.email === event.owner.get('email') || !event.owner.get('email')) || event.organizers.includes(currentUser)
```
Comment (iamareebjamal) [inline app/routes/events/view/edit.js:20]: Why was this change necessary

Comment (maze-runnar) [reply app/routes/events/view/edit.js:20]: when initially creating an event the owner email is null

**Review by iamareebjamal — APPROVED** [review]
