### PR TITLE
fix: Wrap read only relationships deletion in try catch

### LINKED ISSUE #3994: Event Creation: Unable to set an event image
**Describe the bug**
When I created a new event, I tried to upload an event image, then clicked 'publish', the photo disappeared. I have tried several times. 

The image that I uploaded: 4096x1885px, 2.5MB

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Create Event' > 'Basic Details'
2. Click on 'Select Event Image'
3. Click 'Publish'
> Image disappears 

**Screenshots**
After successful upload, it showed 'confirm delete' instead of 'delete' in compared with the select logo option. 
Screenshot from 2020-02-03 22-31-43

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome and chromium

### LINKED ISSUE #3998: Deleting/Restoring an event hangs the frontend
Deleting/Restoring event makes the frontend hang and the request is not processed by the server. Ultimately, the Server needs to be restarted to fix the issue.

Screenshot 2020-02-04 at 12 09 20 PM

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3998
Fixes #3994

### CODE REVIEW

**Comment by kushthedude** [comment]
> This is not called fixing a bug, this is called reverting a "fix"

Try-Catch just catches this error 
```js
[Error] TypeError: undefined is not an object (evaluating 'delete json.data.relationships['general-statistics']') — event.js:17
	serialize (open-event-frontend.js:40073)
	superWrapper (vendor.js:54273)
```

**Comment by iamareebjamal** [comment]
If you put it around both of them, it is impossible that it won't catch both error, or, again as I said before, you may have found a bug in Google Chrome

File: app/serializers/event.js [hunk 1]
```diff
@@ -13,9 +13,15 @@ export default ApplicationSerializer.extend(CustomPrimaryKeyMixin, {
...
-
+    try {
+    delete json.data.relationships['general-statistics'];		
+     delete json.data.relationships['order-statistics'];
+ } catch(e){
+ 	console.error(e);
+ 	this.notify.error(this.l10n.t(e), {
+        id: 'err_down'
+      });
+ }
```
Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Expected indentation of 4 spaces but found 1.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 9
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023&bid=16455910)

File: app/serializers/event.js [hunk 2]
```diff
@@ -13,9 +13,15 @@ export default ApplicationSerializer.extend(CustomPrimaryKeyMixin, {
 
   serialize() {
     const json = this._super(...arguments);
-    delete json.data.relationships['general-statistics'];
-    delete json.data.relationships['order-statistics'];
-
+    try {
+    delete json.data.relationships['general-statistics'];		
+     delete json.data.relationships['order-statistics'];
+ } catch(e){
```
Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Expected space(s) after "catch".](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Expected indentation of 4 spaces but found 1.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

File: app/serializers/event.js [hunk 3]
```diff
@@ -13,9 +13,15 @@ export default ApplicationSerializer.extend(CustomPrimaryKeyMixin, {
...
+ 	console.error(e);
+ 	this.notify.error(this.l10n.t(e), {
```
Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Mixed spaces and tabs.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

File: app/serializers/event.js [hunk 4]
```diff
@@ -13,9 +13,15 @@ export default ApplicationSerializer.extend(CustomPrimaryKeyMixin, {
 
   serialize() {
     const json = this._super(...arguments);
-    delete json.data.relationships['general-statistics'];
-    delete json.data.relationships['order-statistics'];
-
+    try {
+    delete json.data.relationships['general-statistics'];
```
Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

File: app/serializers/event.js (hunk 2 above)
Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Missing space before opening brace.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

File: app/serializers/event.js (hunk 4 above)
Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Expected indentation of 6 spaces but found 4.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

File: app/serializers/event.js [hunk 5]
```diff
@@ -13,9 +13,15 @@ export default ApplicationSerializer.extend(CustomPrimaryKeyMixin, {
 
   serialize() {
     const json = this._super(...arguments);
-    delete json.data.relationships['general-statistics'];
-    delete json.data.relationships['order-statistics'];
-
+    try {
+    delete json.data.relationships['general-statistics'];		
+     delete json.data.relationships['order-statistics'];
```
Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Expected indentation of 6 spaces but found 5.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

File: app/serializers/event.js [hunk 6]
```diff
@@ -13,9 +13,15 @@ export default ApplicationSerializer.extend(CustomPrimaryKeyMixin, {
...
+ } catch(e){
+ 	console.error(e);
```
Comment (niranjan94) [inline app/serializers/event.js]: Codacy Issue found: [Mixed spaces and tabs.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4983023)

**Comment by kushthedude** [comment]
> If you put it around both of them, it is impossible that it won't catch both errors

How to do it then ? One in` try` and other `catch` and then return statement in `finally `?
`

**Comment by iamareebjamal** [comment]
Both will work:

```js
const relationships = json.data.relationships;
if ('general-statistics' in relationships)
	delete relationships['general-statistics'];
if ('order-statistics' in relationships)
	delete relationships['order-statistics'];
```

```js
const relationships = json.data.relationships;
	try {
		delete relationships['general-statistics'];
	} catch {}
	try {
		delete relationships['order-statistics'];
	} catch {}
```

First is better obviously

**Comment by kushthedude** [comment]
> ```js
> const relationships = json.data.relationships;
> 	try {
> 		delete relationships['general-statistics'];
> 	} catch {}
> 	try {
> 		delete relationships['order-statistics'];
> 	} catch {}
> ```

Isnt this a misuse of try-catch 😕 ?

**Comment by kushthedude** [comment]
> ```js
> const relationships = json.data.relationships;
> if ('general-statistics' in relationships)
> 	delete relationships['general-statistics'];
> if ('order-statistics' in relationships)
> 	delete relationships['order-statistics'];
> ```
> 

This one is still throwing the same error.

What about this 
```js
try {
     delete json.data.relationships['general-statistics'];		

       
  } catch(e){
  	console.error(e);
  	this.notify.error(this.l10n.t(e), {
         id: 'err_down'
       });
  }
  finally {
  	try{
  		delete json.data.relationships['order-statistics'];
  	}
  	catch(e){
  	console.error(e);
  	this.notify.error(this.l10n.t(e), {
         id: 'err_down'
       });}
  	finally{
  		    return json;
  	}
  }
```

**Comment by iamareebjamal** [comment]
Why would you notify an error of an internal dev operation?

**Comment by kushthedude** [comment]
> Why would you notify an error of an internal dev operation?

Empty catch block will throw Lint Error, Should that rule be disabled for the file then ?

**Comment by iamareebjamal** [comment]
Disable it for those lines only

File: app/serializers/event.js [hunk 7]
```diff
@@ -13,10 +13,17 @@ export default ApplicationSerializer.extend(CustomPrimaryKeyMixin, {
 
   serialize() {
     const json = this._super(...arguments);
-    delete json.data.relationships['general-statistics'];
-    delete json.data.relationships['order-statistics'];
+
+    const { relationships } = json.data;
```
Comment (iamareebjamal) [inline app/serializers/event.js]:
```suggestion
    const { relationships } = json.data;
    // We are deleting read only relationships so that they don't
    // break the server. Since these relationships are not always present,
    // we catch and ignore the error
```
