### PR TITLE
fix: sorting of logs in admin reports section

### LINKED ISSUE #2679: Admin: In the Logs show newest entries first and show 100 entries as standard
In the Admin Section in the Logs (https://next.eventyay.com/admin/reports/system-logs/activity-logs) show newest entries first and show 100 entries as standard. Currently it shows the oldest entries first.

Screenshot from 2019-04-16 15-05-30

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
In the Admin Section in the Logs, it shows the oldest entries first.

#### Changes proposed in this pull request:
 - fixed sorting of logs in admin reports section

Fixes #2679

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 @pradeepgangwar please review :)

File: app/routes/admin/reports/system-logs/activity-logs.js [hunk 1]
```diff
@@ -7,7 +7,8 @@ export default Route.extend({
 
   model() {
     return this.get('store').query('activity', {
-      'page[size]': 10
+      'page[size]' : 10,
```
Comment (uds5501) [inline app/routes/admin/reports/system-logs/activity-logs.js]: According to issue request, the page size should've been 100 by default. Please do that @shreyanshdwivedi

Comment (shreyanshdwivedi) [reply app/routes/admin/reports/system-logs/activity-logs.js]: @pradeepgangwar @uds5501 I've made the required changes. Please review :)
