### PR TITLE
fix: Hide payment options if disabled(Paypal and Stripe)

### LINKED ISSUE #1245: Payments accepted even though disabled
**Describe the bug**
Even if payments by **Stripe** and **Paypal** have been disabled from the admin settings, they are still displayed in the event creation wizard

**To Reproduce**
1. Make sure payment by Stripe and Paypal is disabled in the admin settings
2. Start creating an event
3. You can still see options in the frontend to link Stripe and Paypal

**Expected behavior**
These should be absent from the frontend.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

### PR DESCRIPTION
**Pull request by mayank8318**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Hide Stripe and Paypal payment options if they are disabled by the admin.

#### Changes proposed in this pull request:
- Check the settings if these payment options are enabled or disabled.

Fixes #1245

### CODE REVIEW

File: app/components/forms/wizard/basic-details-step.js [hunk 1]
```diff
@@ -182,11 +182,19 @@ export default Component.extend(FormMixin, {
...
+        this.rerender();
+      });
   }),
 
   canAcceptStripe: computed('data.event.paymentCurrency', function() {
-    return find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).stripe;
+    this.get('store').queryRecord('setting', {})
+      .then(setting => {
+        this.set('canAcceptStripe', setting.stripeClientId && find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).stripe);
+        this.rerender();
```
[the remark this answers is not in the document]
Comment (niranjan94) [reply app/components/forms/wizard/basic-details-step.js]: https://github.com/fossasia/open-event-frontend/pull/1258#discussion_r194000956

File: app/components/forms/wizard/basic-details-step.js [hunk 2]
```diff
@@ -182,11 +182,19 @@ export default Component.extend(FormMixin, {
   }),
 
   canAcceptPayPal: computed('data.event.paymentCurrency', function() {
-    return find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).paypal;
+    this.get('store').queryRecord('setting', {})
```
[the remark this answers is not in the document]
Comment (niranjan94) [reply app/components/forms/wizard/basic-details-step.js]: @mayank8318 lemme know if you don't understand how to go about this.

**Comment by niranjan94** [comment]
@mayank8318 I mean something like this 

```js
import Service, { inject as service } from '@ember/service';
import { computed, observer } from '@ember/object';

export default Service.extend({

  store       : service(),
  session     : service(),
  authManager : service(),

  _lastPromise: Promise.resolve(),

  /**
   * Reload settings when the authentication state changes.
   */
  _authenticationObserver: observer('session.isAuthenticated', function () {
    this.get('_lastPromise')
      .then(() => this.set('_lastPromise', this._loadSettings()))
      .catch(() => this.set('_lastPromise', this._loadSettings()));
  }),

  /**
   * Load the settings from the API and set the attributes as properties on the service
   *
   * @return {Promise<void>}
   * @private
   */
  async _loadSettings() {
    const settingsModel = await this.get('store').queryRecord('setting', {});
    this.get('store').modelFor('setting').eachAttribute(attributeName => {
      this.set(attributeName, settingsModel.get(attributeName));
    });
  },

  /**
   * Initialize the settings service
   * @return {*|Promise<void>}
   */
  initialize() {
    const promise = this._loadSettings();
    this.set('_lastPromise', promise);
    return promise;
  }
});
```

Here, you can access all the settings properties directly. Without having to worry about async/promises. 

- Make sure to add the above service
- Add it to `app/initializers/blanket.js` so that it is accessible globally. We'll need it. 
- Make sure to initialize it inside `beforeModel` of the application route. (similar to how we do for auth-manager.). So that the app waits for settings to load before rendering any other route.

File: app/components/forms/wizard/basic-details-step.js [hunk 3]
```diff
@@ -182,11 +182,11 @@ export default Component.extend(FormMixin, {
   }),
 
   canAcceptPayPal: computed('data.event.paymentCurrency', function() {
-    return find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).paypal;
+    return (this.get('settings.paypalSandboxUsername') || this.get('settings.paypalLiveUsername')) && find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).paypal;
```
Comment (niranjan94) [inline app/components/forms/wizard/basic-details-step.js]: Since this computed property depends on these, make sure you specify that in the computed property definition so that this updates when those change

File: app/components/forms/wizard/basic-details-step.js [hunk 4]
```diff
@@ -182,11 +182,11 @@ export default Component.extend(FormMixin, {
...
   }),
 
   canAcceptStripe: computed('data.event.paymentCurrency', function() {
-    return find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).stripe;
+    return this.get('settings.stripeClientId') && find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).stripe;
```
Comment (niranjan94) [inline app/components/forms/wizard/basic-details-step.js]: Since this computed property depends on these, make sure you specify that in the computed property definition so that this updates when those change

File: app/components/forms/wizard/basic-details-step.js [hunk 5]
```diff
@@ -181,12 +181,12 @@ export default Component.extend(FormMixin, {
     return orderBy(paymentCurrencies, 'name');
   }),
 
-  canAcceptPayPal: computed('data.event.paymentCurrency', function() {
-    return find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).paypal;
+  canAcceptPayPal: computed('data.event.paymentCurrency', this.get('settings.paypalSandboxUsername'), this.get('settings.paypalLiveUsername'), function() {
```
Comment (niranjan94) [inline app/components/forms/wizard/basic-details-step.js]: @mayank8318 incorrect syntax. Please check your code before pushing.

File: app/components/forms/wizard/basic-details-step.js [hunk 6]
```diff
@@ -181,12 +181,12 @@ export default Component.extend(FormMixin, {
...
+    return (this.get('settings.paypalSandboxUsername') || this.get('settings.paypalLiveUsername')) && find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).paypal;
   }),
 
-  canAcceptStripe: computed('data.event.paymentCurrency', function() {
-    return find(paymentCurrencies, ['code', this.get('data.event.paymentCurrency')]).stripe;
+  canAcceptStripe: computed('data.event.paymentCurrency', this.get('settings.stripeClientId'), function() {
```
Comment (niranjan94) [inline app/components/forms/wizard/basic-details-step.js]: @mayank8318 incorrect syntax. Please check your code before pushing.

File: app/services/settings.js [hunk 7]
```diff
@@ -0,0 +1,43 @@
...
+  store       : service(),
+  session     : service(),
+  authManager : service(),
+
+  _lastPromise: Promise.resolve(),
+
+  /**
+   * Reload settings when the authentication state changes.
+   */
+  _authenticationObserver: observer('session.isAuthenticated', function () {
```
Comment (CosmicCoder96) [inline app/services/settings.js]: There is a linting error at this line. Please fix it.

**Comment by mayank8318** [comment]
@niranjan94 @agbilotia1998 Sorry the eslint fix and rebasing dismissed your reviews. Please review again :)
