### PR TITLE
fix: Company field validation in form

### LINKED ISSUE #5602: Attendee Custom Form: No error message on some fields and changed order on live form
The attendee form has a few issues:
1. If a user does not enter required information some form fields do not show the red required field, e.g. Company, but also check all other fields, please.
Screenshot from 2020-11-13 12-11-17
2. The order of standard fields and custom form fields is changed, e.g. "Company" suddenly appears in between custom questions. (Please also test this with all other fields).
Screenshot from 2020-11-13 12-09-54

### PR DESCRIPTION
**Pull request by Saumyachitransh01**
Fixes #5602 
Before
Screenshot from 2020-11-13 18-33-33

After
Screenshot from 2020-11-13 18-23-32

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/components/forms/orders/order-form.js [hunk 1]
```diff
@@ -202,7 +202,6 @@ export default Component.extend(FormMixin, {
     };
 
     const companyValidation = {
-      identifier : 'company',
```
Comment (iamareebjamal) [inline app/components/forms/orders/order-form.js:205]: Why?

Comment (Saumyachitransh01) [reply app/components/forms/orders/order-form.js:205]: It's resolving the issue

Comment (iamareebjamal) [reply app/components/forms/orders/order-form.js:205]: But why was it creating it?

**Review by iamareebjamal — APPROVED** [review]
