### PR TITLE
fix: Hide search box on wizard pages

### LINKED ISSUE #6220: Top Menu Bar: Hide search box on wizard pages
The search box on the top menu should be hidden on wizard pages. Please change it.

Screenshot from 2021-01-03 01-53-20

### PR DESCRIPTION
**Pull request by progmatic-99**
Fixes #6220 

#### Short description of what this resolves:
Removed search box from all attendee, other-details, session-speakers, sponsors & basic-details page.

Screenshot from 2021-01-03 19-45-41

### CODE REVIEW

File: app/components/nav-bar.js [hunk 1]
```diff
@@ -9,6 +9,17 @@ export default class NavBar extends Component {
...
 
+    @computed('session.currentRouteName')
+  get isNotWizardPage() {
+    const wizardPages = String(this.session.currentRouteName).includes('events.view.edit.basic-details')
+    || String(this.session.currentRouteName).includes('events.view.edit.attendee')
+    || String(this.session.currentRouteName).includes('events.view.edit.sessions-speakers')
+    || String(this.session.currentRouteName).includes('events.view.edit.index')
+    || String(this.session.currentRouteName).includes('events.view.edit.sponsors')
+    || String(this.session.currentRouteName).includes('events.view.edit.other-details');
+    return !(wizardPages);
```
Comment (Creatoon) [inline app/components/nav-bar.js:20]: you can do everything in a single line.
 return String(this.session.currentRouteName).includes('events.view.edit')

File: app/components/nav-bar.js [hunk 2]
```diff
@@ -9,6 +9,17 @@ export default class NavBar extends Component {
...
   }
 
+    @computed('session.currentRouteName')
+  get isNotWizardPage() {
+    const wizardPages = String(this.session.currentRouteName).includes('events.view.edit.basic-details')
+    || String(this.session.currentRouteName).includes('events.view.edit.attendee')
+    || String(this.session.currentRouteName).includes('events.view.edit.sessions-speakers')
+    || String(this.session.currentRouteName).includes('events.view.edit.index')
+    || String(this.session.currentRouteName).includes('events.view.edit.sponsors')
+    || String(this.session.currentRouteName).includes('events.view.edit.other-details');
```
Comment (iamareebjamal) [inline app/components/nav-bar.js:19]: What all these strings have in common?

File: app/components/nav-bar.js (hunk 1 above)
Comment (Creatoon) [reply app/components/nav-bar.js:20]: also you should do the same thing for create page
return String(this.session.currentRouteName).includes('create')

File: app/components/nav-bar.js (hunk 2 above)
Comment (progmatic-99) [reply app/components/nav-bar.js:19]: so, if i do `events.view.edit`, the page that opens up after `Manage Events` also doesn't have search box. Do we want that??

Comment (iamareebjamal) [reply app/components/nav-bar.js]: Yes

File: app/components/nav-bar.js [hunk 3]
```diff
@@ -9,6 +9,12 @@ export default class NavBar extends Component {
     return !(String(this.session.currentRouteName).includes('public'));
   }
 
+  @computed('session.currentRouteName')
+  get isNotWizardPageRoute() {
+    return !(String(this.session.currentRouteName).includes('edit'))
+    && !(String(this.session.currentRouteName).includes('create'));
```
Comment (iamareebjamal) [inline app/components/nav-bar.js:15]: This will hide search bar on all routes which have create in their identifier

File: app/components/nav-bar.js [hunk 4]
```diff
@@ -9,6 +9,12 @@ export default class NavBar extends Component {
     return !(String(this.session.currentRouteName).includes('public'));
   }
 
+  @computed('session.currentRouteName')
+  get isNotWizardPageRoute() {
+    return !(String(this.session.currentRouteName).includes('edit'))
+    && !(String(this.session.currentRouteName) === 'create');
```
Comment (iamareebjamal) [inline app/components/nav-bar.js:15]:
```suggestion
    && String(this.session.currentRouteName) !== 'create';
```

Comment (progmatic-99) [reply app/components/nav-bar.js:15]: Both implementation are the same?? Then why this?? Coding standard/covention??

Comment (iamareebjamal) [reply app/components/nav-bar.js]: Yes

**Comment by mariobehling** [comment]
Thank you. 

And, actually "Create Event" on the top right should neither be there. I opened a follow up issue here https://github.com/fossasia/open-event-frontend/issues/6227
