### PR TITLE
fix: added company info block on the tickets view page

### LINKED ISSUE #6303: Order Process: Add Info Box "Organizer Information"
In wizard step 1 an organizer has an option to add company. If an organizer adds the info, then show the company info in a box during the ordering process on the right hand side.

1. Add the info box below "Where and When" during ordering
2. Add the info box above "Payee Information" on the order page
3. If the organizer has not added that info then do not show the box

Screenshot from 2021-01-11 00-29-05
Screenshot from 2021-01-11 00-30-20

### PR DESCRIPTION
**Pull request by Creatoon**
Fixes #6303 

#### Short description of what this resolves:
This pr adds a organizer info block on ticket orders page.

Screenshot_2021-01-11 Completed Order - cc28792b-662d-4c83-a703-90ec2aa966ba Orders Open Event(1)

@iamareebjamal sir i have added this organizer block on the order view page , the issue also mentioned to add this feature for view new page but that page already have this feature, please mark me if i miss anything here , thanks

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This is organizer info, not company info

**Comment by Creatoon** [comment]
> This is organizer info, not company info

Yes sir,  looking into this

**Comment by Creatoon** [comment]
@iamareebjamal  sir please review , i am adding screenshots, mark me if i am going wrong.

On creating orders

Screenshot_2021-01-12 New Order - f86796d8-c4b7-4b38-9c5f-ab4260638493 Orders Open Event


After created

Screenshot_2021-01-12 Placed Order - f86796d8-c4b7-4b38-9c5f-ab4260638493 Orders Open Event

**Comment by Creatoon** [comment]
after new changes 

Screenshot_2021-01-13 Placed Order - f86796d8-c4b7-4b38-9c5f-ab4260638493 Orders Open Event

**Comment by iamareebjamal** [comment]
test failing

**Comment by Creatoon** [comment]
@iamareebjamal sir tests are passing now.

**Comment by mariobehling** [comment]
Thanks, though I am confused by the example with a mixed Indian and US address.

Also fields are mixed up first address then again city and ZIP and then tax and then state. Country and tax ID is missing.

Could you please sort the fields in a more standard way and add the missing fields. Thanks!

**Comment by mariobehling** [comment]
Area for "Go to event page" disappeared in your last screenshots. Please ensure it is still there. Do not delete this area. Thanks.

**Comment by Creatoon** [comment]
> Thanks, though I am confused by the example with a mixed Indian and US address.
> 
> Also fields are mixed up first address then again city and ZIP and then tax and then state. Country and tax ID are missing.
> 
> Could you please sort the fields in a more standard way and add the missing fields. Thanks!

Yes sir, I am sorting it

**Comment by Creatoon** [comment]
@mariobehling Sir , i think it looks more organized now,  please tell me if it is not as expected, Thank you.

Screenshot_2021-01-13 Placed Order - 54c04a14-fcba-4dc7-8c46-b01d44bba3a3 Orders Open Event(2)

Screenshot_2021-01-13 Placed Order - 54c04a14-fcba-4dc7-8c46-b01d44bba3a3 Orders Open Event(1)

**Comment by Creatoon** [comment]
@iamareebjamal sir are will these changes gonna accepted or i have to correct more

**Comment by mariobehling** [comment]
Good job! Please change "Tax Id" -> "Tax ID" and merge it afterwards.

**Comment by mariobehling** [comment]
Was not able to test this: Please ensure the fields can be translated.

**Comment by Creatoon** [comment]
> Was not able to test this: Please ensure the fields can be translated.

Ok sir,  I am making it

File: app/components/orders/company-info.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import classic from 'ember-classic-decorator';
+import Component from '@ember/component';
+
+@classic
```
Comment (iamareebjamal) [inline app/components/orders/company-info.js:4]: No classic components

Comment (Creatoon) [reply app/components/orders/company-info.js:4]: i am using classic features here, i should add @classic here

Comment (iamareebjamal) [reply app/components/orders/company-info.js:4]: Use non classic features

Comment (Creatoon) [reply app/components/orders/company-info.js]: sir i removed the property , because banner [Company Information] is required on every page

**Comment by Creatoon** [comment]
> Was not able to test this: Please ensure the fields can be translated.

tested in french language , working just fine

Screenshot from 2021-01-14 22-16-42

File: app/components/orders/company-info.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+import Component from '@ember/component';
+
+export default Component.extend({});
```
Comment (iamareebjamal) [inline app/components/orders/company-info.js:3]: Empty component JS is not needed, delete

Comment (Creatoon) [reply app/components/orders/company-info.js]: done

Comment (Creatoon) [reply app/components/orders/company-info.js]: Sir, please test deployment one time,  because everything is Working well in my local machine,  but an error comes on deployment.

File: app/templates/components/orders/company-info.hbs [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+    <div class="ui inverted mini statistic horizontal">
+      <div class="value">
+        {{t 'Company Information'}}
+      </div>
+    </div>
+  </div>
+  <div class="ui padded segment">
+    <table class="ui very basic compact unstackable table company-info">
+      <tbody>
+        {{#if this.data.registeredCompany}}
```
Comment (iamareebjamal) [inline app/templates/components/orders/company-info.hbs:12]: Won't work, this is classical syntax. Use octane syntax, change data prop to tax

File: app/routes/orders/view.js [hunk 4]
```diff
@@ -13,15 +13,18 @@ export default class ViewRoute extends Route {
...
     });
     const eventDetails = await order.query('event', { include: 'tax' });
+
     return {
       order,
-      event : eventDetails,
-      form  : await eventDetails.query('customForms', {
+      event      : eventDetails,
+      taxDetails : await eventDetails.get('tax', { cache: true, public: true }),
+      form       : await eventDetails.query('customForms', {
```
Comment (iamareebjamal) [inline app/routes/orders/view.js:27]: Remove await and use hash function to wrap the return object

Comment (Creatoon) [reply app/routes/orders/view.js:27]: yes sir

Comment (Creatoon) [reply app/routes/orders/view.js:27]: if i will use hash , then i should remove every await statements

Comment (iamareebjamal) [reply app/routes/orders/view.js:27]: inside the return object, yes

**Comment by iamareebjamal** [comment]
Is it working now?

**Comment by Creatoon** [comment]
> Is it working now?

On my local machine,  but not on deployment.
Actually first error comes then after one reload it works also on deployment,  I am finding why this is happening

File: app/routes/orders/new.js [hunk 5]
```diff
@@ -35,7 +35,7 @@ export default class NewRoute extends Route {
       order,
       event      : eventDetails,
       tickets,
-      taxDetails : eventDetails.get('tax', { cache: true, public: true }),
+      taxDetails : order.event.get('tax', { cache: true, public: true }),
```
Comment (iamareebjamal) [inline app/routes/orders/new.js]: Why?

Comment (Creatoon) [reply app/routes/orders/new.js]: sir pr is not finalised now , i am just testing few things.

**Comment by Creatoon** [comment]
@iamareebjamal sir everything is resolved now , no error is coming, you can review this sir, thanks

File: app/routes/orders/new.js [hunk 6]
```diff
@@ -29,10 +29,18 @@ export default class NewRoute extends Route {
     });
 
     const eventDetails = await order.query('event', { include: 'tax' });
+
+    let taxDetails;
+
+    if (eventDetails.isTaxEnabled) {
+      taxDetails = await eventDetails.get('tax', { cache: true, public: true });
```
Comment (iamareebjamal) [inline app/routes/orders/new.js:36]: Multiple awaits

Comment (Creatoon) [reply app/routes/orders/new.js:36]: sir can i write taxdetails in return like this using hash, this will also reduce multiple awaits

```
taxDetails : eventDetails.isTaxEnabled ? eventDetails.get('tax', { cache: true, public: true }) : undefined;
```
because i think the 404 error will again generate if we try to get taxDetails for those events which do not have tax details

Comment (Creatoon) [reply app/routes/orders/new.js]: it is working sir

File: app/routes/orders/new.js [hunk 7]
```diff
@@ -29,11 +30,13 @@ export default class NewRoute extends Route {
...
     const eventDetails = await order.query('event', { include: 'tax' });
-    return {
+
+    return hash({
       order,
-      event : eventDetails,
+      event      : eventDetails,
       tickets,
-      form  : await eventDetails.query('customForms', {
+      taxDetails : eventDetails.isTaxEnabled && eventDetails.get('tax', { cache: true, public: true }) || undefined,
```
Comment (iamareebjamal) [inline app/routes/orders/new.js:38]: Why || undefined?

File: app/routes/orders/new.js [hunk 8]
```diff
@@ -29,11 +30,13 @@ export default class NewRoute extends Route {
...
+      form       : await eventDetails.query('customForms', {
```
Comment (iamareebjamal) [inline app/routes/orders/new.js:39]: Remove await

File: app/routes/orders/new.js (hunk 7 above)
Comment (Creatoon) [reply app/routes/orders/new.js:38]: Because , it throws 404 error if the result of getting taxDetails is not successful,  I can show that to you by removing undefined,  that's why I am returning undefined if there is no tax details.

File: app/routes/orders/new.js (hunk 8 above)
Comment (Creatoon) [reply app/routes/orders/new.js:39]: Yes sir removing this,  I forgot to do this

File: app/routes/orders/new.js (hunk 7 above)
Comment (Creatoon) [reply app/routes/orders/new.js:38]: We can also use null in place of undefined

Comment (Creatoon) [reply app/routes/orders/new.js]: thank you sir for pointing out this , i removed that

**Comment by iamareebjamal** [comment]
As it was one of your starting issues, good job, but try to reduce the amount of reviews required from next time on. Review your own work first, if you forget to remove things, they can be taken care of in self-reviews

**Comment by Creatoon** [comment]
> As it was one of your starting issues, good job, but try to reduce the amount of reviews required from next time on. Review your own work first, if you forget to remove things, they can be taken care of in self-reviews

Thank you sir for your valuable advice , i will take care of each point you mentioned.
