### PR TITLE
Fix bugs related to session details and a route to edit session for cfs

### LINKED ISSUE #1402: Fix the bugs for add and edit session details in cfs modal
**Describe the bug**

Currently the user cannot add multiple session proposals, there is no route to edit a session, if a session is added the user isn't set as the speaker of that session.

**To Reproduce**
1. Go to e/{event_identifier}/cfs
2. See error

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium

### PR DESCRIPTION
**Pull request by ritikamotwani**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This resolves the bugs related to session details in cfs and adds a route to edit session details for the public session proposals

#### Changes proposed in this pull request:

- Adds a route to edit session proposals entered through the cfs modal.
- Allows the user to enter multiple session proposals 
- Allows the user to edit the session proposals he has submitted
- Sets the user as the speaker for the session proposals he submits through the cfs modal.

Fixes #1402

### CODE REVIEW

**Comment by ritikamotwani** [comment]
@pradeepgangwar @srv-twry @mayank8318 please review

File: app/controllers/public/cfs/new-session.js [hunk 1]
```diff
@@ -1,20 +1,17 @@
...
-        })
-        .finally(() => {
-          this.set('isLoading', false);
-        });
+    async save(speakerDetails) {
+      try {
+        this.set('isLoading', true);
+        await this.get('model.session').save();
+        speakerDetails.sessions.pushObject(this.get('model.session'));
+        await this.get('model.session').save();
```
Comment (CosmicCoder96) [inline app/controllers/public/cfs/new-session.js]: why is this twice?

File: app/routes/public/cfs/index.js [hunk 2]
```diff
@@ -48,13 +48,26 @@ export default Route.extend({
...
+                  val  : eventDetails.id
+                }
+              },
+              {
+                name : 'speakers',
+                op   : 'any',
+                val  : {
+                  name : 'email',
+                  op   : 'eq',
+                  val  : this.get('authManager.currentUser').email
```
Comment (CosmicCoder96) [inline app/routes/public/cfs/index.js]:
```js
 this.get('authManager.currentUser')
```
has been used 3-4 times in the route, instead store it in a variable called `currentUser` instead of using `this.get` every time.

File: app/controllers/public/cfs/new-session.js (hunk 1 above)
Comment (ritikamotwani) [reply app/controllers/public/cfs/new-session.js]: @CosmicCoder96 once it stores the details of the form and then the speaker is pushed to its relationship and then saved again. If written once the speaker doesn't get added to the session.

**Comment by ritikamotwani** [comment]
@CosmicCoder96 did the changes please review.
