### PR TITLE
fix: require event location before publishing event

### LINKED ISSUE #1308: Publishing event without location shows error, but button changes to "Unpublish"
**Describe the bug**

Events can't be published without location. But the button "Publish" changes to "Unpublish" - even when no location is provided -  while also showing "An unexpected error occurred".

**To Reproduce**
1. Create an event without setting location
2. Fill necessary details and click on 'Publish'
3. The 'Publish' button will turn to 'Unpublish', while an "..unexpected error.." occurs.

**Expected behavior**

The button should not change to 'Unpublish'.

**Screenshots**

screenshot from 2018-06-21 22-02-05

### PR DESCRIPTION
**Pull request by mishuvs**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:

Now clicking 'Publish' with no event location won't turn the button to 'Unpublish', will show error message: "Your event must have a location before it can be published."

#### Changes proposed in this pull request:

- Adds a check for the location of an event before publishing

Fixes #1308 

#### Screenshot

screenshot from 2018-06-22 15-48-31

### CODE REVIEW

**Comment by mishuvs** [comment]
@srv-twry @ritikamotwani @bhaveshAn @mayank8318 @pradeepgangwar Please review.

File: app/controllers/events/view.js [hunk 1]
```diff
@@ -6,6 +6,10 @@ export default Controller.extend({
       this.set('isEventDeleteModalOpen', true);
     },
     togglePublishState() {
+      if (this.get('model.event.location') === undefined) {
```
Comment (srv-twry) [inline app/controllers/events/view.js]: Not sure whether we need to specifically check for undefined using ```===``` but I may be wrong.
@pradeepgangwar @mayank8318 Am i right ?

Comment (mishuvs) [reply app/controllers/events/view.js]: @srv-twry it was wrong to compare to undefined. I have corrected and now checking if empty.
Can you please review again?

**Comment by mishuvs** [comment]
Okay @ritikamotwani. @srv-twry Please review again.
