### PR TITLE
Translations download as zip(.po files) button fix

### LINKED ISSUE #2443: admin:Translations download button not functional
**Describe the bug**
The button in the admin panel for translations download must be functional

**To Reproduce**
1. Go to 'Admin Panel'
2. Click on 'Contents tab'
3. Click on Download Translations button
4. No action occurs

**Expected behavior**
The translations must be downloaded in a zipped format. 

**Additional context**
I'm working on it

### PR DESCRIPTION
**Pull request by mrsaicharan1**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Translations as zip can now be downloaded on the admin panel
Related server [PR](https://github.com/fossasia/open-event-server/pull/5624/)

Fixes #2443

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
Commit history is not related to this. Fixing the pr

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Can you confirm if the link reidrect is right here?

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 no - this link is supposed to be used for downloading actual .po files like you download pdfs for tickets. The URL has to come from the server where it will be stored.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 I've implemented the feature for downloading .po files here in this PR [](https://github.com/fossasia/open-event-server/pull/5624) on the server. Won't routing it to [/admin/content/translations/all](url) do it?

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 You created a namespace on the server - by specifying that the url_prefix is /admin/content/translations/all so you basically created an end point on the API. How will routing to that particular url-prefix on the frontend get the file -- that route doesn't exist. You are confusing ember FE routes with API endpoints. They are not interchangeable.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Please correct me if I'm wrong. I'll be creating a model for the translations route where it fetches the data from server. The I'll be setting the `sourceUrl` to `data.get('download_link')` for redirection. Am I right?

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Appended the url using the loader service.

File: app/routes/admin/content/translations.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ export default Route.extend({
     return [
       {
         code      : 'en',
-        sourceUrl : '#'
+        sourceUrl : this.get('loader').load('/admin/content/translations/all')
```
Comment (CosmicCoder96) [inline app/routes/admin/content/translations.js]: this will actually execute the loading of the file. You don't need to pass this in the model.. just execute this when the download button is pressed.

File: app/routes/admin/content/translations.js [hunk 2]
```diff
@@ -9,8 +9,20 @@ export default Route.extend({
...
     ];
+  },
+
+  actions: {
+    translationsDownload() {
+      this.set('isLoading', true);
+      this.get('loader')
+        .load('/admin/content/translations/all')
+        .catch(() => {
+          this.set('isLoading', false);
```
Comment (CosmicCoder96) [inline app/routes/admin/content/translations.js]: it will always be loading after success if you set `isLoading` false only when it fails.

Comment (mrsaicharan1) [reply app/routes/admin/content/translations.js]: yeah, jsut saw that. Initialised `isLoading` .

Comment (CosmicCoder96) [reply app/routes/admin/content/translations.js]: No, what I meant is: you set `isLoading` to true when the download begins. You never set it to false when it is successfully over. It remains true in perpetuity.

File: app/routes/admin/content/translations.js [hunk 3]
```diff
@@ -12,5 +14,17 @@ export default Route.extend({
         sourceUrl : '#'
       }
     ];
+  },
+
+  actions: {
+    translationsDownload() {
```
Comment (CosmicCoder96) [inline app/routes/admin/content/translations.js]: Also just noticed. Move this action to the controller -- all the controlling logic should reside there.

File: app/routes/admin/content/translations.js (hunk 2 above)
Comment (mrsaicharan1) [reply app/routes/admin/content/translations.js]: Oh right. I'll need to make it False `finally`.

File: app/routes/admin/content/translations.js (hunk 3 above)
Comment (mrsaicharan1) [reply app/routes/admin/content/translations.js]: yeah, I was doubtful about whether it should reside in the route or the controller. I'll create a new controller file and move the logic there.

File: app/routes/admin/content/translations.js [hunk 4]
```diff
@@ -12,5 +14,20 @@ export default Route.extend({
...
+      this.set('isLoading', true);
+      this.get('loader')
+        .load('/admin/content/translations/all')
+        .catch(() => {
+          this.set('isLoading', false);
```
Comment (CosmicCoder96) [inline app/routes/admin/content/translations.js]: you already specified this in finally. Remove it from here.

File: app/templates/admin/content/translations.hbs [hunk 5]
```diff
@@ -16,7 +16,7 @@
               {{get l10n.availableLocales language.code}}
             </div>
             <div class="column eight wide">
-              <a href="{{language.sourceUrl}}">{{t 'Download'}}</a>
+              <a href="{{language.sourceUrl}}" onclick={{action 'translationsDownload'}}>{{t 'Download' }}</a>
```
Comment (CosmicCoder96) [inline app/templates/admin/content/translations.hbs]: No need to use onclick. It will call it automatically. Also make it a button, not an anchor tag.

File: app/controllers/admin/content/translations.js [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+export default Controller.extend({
+  isLoading: false,
+
+  actions: {
+    translationsDownload() {
+      this.set('isLoading', true);
+      this.get('loader')
+        .load('/admin/content/translations/all')
+        .catch(() => {
+          this.set('isLoading', false);
```
Comment (CosmicCoder96) [inline app/controllers/admin/content/translations.js]: redundant. Remove this.

File: app/controllers/admin/content/translations.js [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+
+export default Controller.extend({
+  isLoading: false,
+
+  actions: {
+    translationsDownload() {
+      this.set('isLoading', true);
+      this.get('loader')
+        .load('/admin/content/translations/all')
+        .catch(() => {
```
Comment (CosmicCoder96) [inline app/controllers/admin/content/translations.js]: change the catch block to 
```js
.catch( e => {
console.warn(e);
this.get('notify').error(this.get('l10n').t('Unexpected error occurred.'));
}

File: app/templates/admin/content/translations.hbs [hunk 8]
```diff
@@ -16,7 +16,7 @@
               {{get l10n.availableLocales language.code}}
             </div>
             <div class="column eight wide">
-              <a href="{{language.sourceUrl}}">{{t 'Download'}}</a>
+              <button class="ui primary loading button" href="{{language.sourceUrl}}" {{action 'translationsDownload'}}>{{t 'Download' }}</button>
```
Comment (CosmicCoder96) [inline app/templates/admin/content/translations.hbs]: Try the functionality yourself and see if it works before pushing .. if you add the loading class directly button will always be in the loading state.
Make it 
```hbs
<button class="ui primary {{if isLoading 'loading'}} button" href="{{language.sourceUrl}}" {{action 'translationsDownload'}}>{{t 'Download' }}</button>
```

Comment (mrsaicharan1) [reply app/templates/admin/content/translations.hbs]: Yeah, made the requested changes. Also, for the downloads to work, made a PR to change the API endpoint to 'v1/admin/content/translations/all'

**Comment by mrsaicharan1** [comment]
@CosmicCoder96
I believe that the downloads should be working but there's a permanent redirect for the resource.
 `127.0.0.1 - - [09/Apr/2019 13:21:16] "OPTIONS /v1/admin/content/translations/all HTTP/1.1" 308 -`

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 what do you mean by permanent redirect?

**Comment by mrsaicharan1** [comment]
> @mrsaicharan1 what do you mean by permanent redirect?

HTTP 308

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 Not sure how it's showing on your side: on testing this PR for me it shows a 404
vendor-6d3d450f0fa475b013d3067764daa7a9.js:8357 OPTIONS https://open-event-api-dev.herokuapp.com/v1/admin/content/translations/all? 404 (NOT FOUND)

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 I've tried out the API request locally and the download works properly when I navigate to `https://localhost:5000/v1/admin/content/translations/all`

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 I have redeployed the server on heroku -- I guess the build of your merged PR is still under progress there. Will test it in a few mins.

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 I got this locally, any ideas?
image

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 I think it's due to the deletion of the zip file as a celery task. On the server side in `app/api/admin_translations.py`, if you comment out the lines for deletion as a celery task, the zip is being downloaded
Screenshot from 2019-04-09 14-26-44

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 I will push a pr to create a download file service.. try it after that.

File: app/controllers/admin/content/translations.js [hunk 9]
```diff
@@ -0,0 +1,20 @@
+import Controller from '@ember/controller';
+
+export default Controller.extend({
+  isLoading: false,
+
+  actions: {
+    translationsDownload() {
+      this.set('isLoading', true);
+      this.get('loader')
+        .load('/admin/content/translations/all')
```
Comment (CosmicCoder96) [inline app/controllers/admin/content/translations.js]: @mrsaicharan1 Use the service I defined in https://github.com/fossasia/open-event-frontend/pull/2540
here. 
```js
this.get('loader')
        .downloadFile('/admin/content/translations/all')
        .then(()=> {
         this.get('notify').success(this.get('l10n').t('Translations Zip generated successfully.'));
          })

Comment (mrsaicharan1) [reply app/controllers/admin/content/translations.js]: Screenshot from 2019-04-09 18-23-13
The Downloder service helped a lot! It's working perfectly now :)

Comment (mrsaicharan1) [reply app/controllers/admin/content/translations.js]: The downloader service helped a lot! It's working perfectly now :)
Screenshot from 2019-04-09 18-24-44

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 Open an issue on the server for the celery task of translation helpers. It is failing for the test deployment with the same error message which I posted a screenshot of before.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Fixed the translations donwload on the server https://github.com/fossasia/open-event-server/pull/5767

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Fixed the translations donwload on the server https://github.com/fossasia/open-event-server/pull/5767
