### PR TITLE
fix: Show error details on deleting event

### LINKED ISSUE #3508: Proper error message should be displayed when deleting an event
**Describe the bug**
When deleting an event associated with orders, it should show the correct error message as it gets from the server.

**Additional context**
On it.

### PR DESCRIPTION
**Pull request by blossom2017**
Fixes #3508

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/controllers/admin/events/list.js [hunk 1]
```diff
@@ -128,10 +128,16 @@ export default class extends Controller.extend(EmberTableControllerMixin) {
       this.refreshModel.bind(this)();
     } catch (e) {
       console.error('Error while deleting event', e);
-      this.notify.error(this.l10n.t('An unexpected error has occurred.'),
-        {
-          id: 'event_delete_error'
+      if ('errors' in e && e.errors.length > 0) {
```
Comment (iamareebjamal) [inline app/controllers/admin/events/list.js:131]: Can be reduced to `e.errors?[0]?.detail`

Comment (blossom2017) [reply app/controllers/admin/events/list.js]: Done.Thanks for the review.
