### PR TITLE
fix: Disallow publish event without tickets

### LINKED ISSUE #4525: Possible to publish events without ticket and minimum requirements through Event Dashboard
There are events that dont have a ticket, but they get published to the front page, e.g. https://eventyay.com/e/b303a673 (I added a ticket and unpublished it). I wonder how this happens as the wizard will show an error message, that an event cannot be published without a ticket.

However, there is a "Publish" option on the event dashboard. It is possible to publish an event here without a ticket or other minimum requirements.

Expected: It should not be possible to publish an event on the event dashboard, if minimum requirements are not met.

Screenshot from 2020-07-04 14-05-26

### PR DESCRIPTION
**Pull request by Haider8**
Fixes #4525 

#### Short description of what this resolves:
Possible to publish event from event manage overview page

#### Changes proposed in this pull request:
Don't publish event (show error) without tickets

without-ticket-publish

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/controllers/events/view.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=5937633&bid=19462997)

File: app/controllers/events/view.js [hunk 1]
```diff
@@ -11,15 +11,22 @@ export default class extends Controller {
...
-    if (isEmpty(this.model.locationName)) {
+    const { state } = this.model;
+    if (state === 'draft' && isEmpty(this.model.tickets)) {
+      this.notify.error(this.l10n.t('Your event must have tickets before it can be published.'),
+        {
+          id: 'event_tickets'
+        });
+      return;
+    }
+    if (state === 'draft' && isEmpty(this.model.locationName)) {
```
Comment (iamareebjamal) [inline app/controllers/events/view.js:22]: Both if statements can be nested in `state === 'draft'` if condition

**Comment by mariobehling** [comment]
Is it possible to make the "Publish" button gray instead of green, if an event cannot be published?

**Comment by snitin315** [comment]
Yes, shoud be possible.

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/controllers/events/view.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=5937633&bid=19462997)

**Comment by iamareebjamal** [comment]
@Haider8 Please check new comments as well

**Comment by mariobehling** [comment]
Thinking this further. Instead of showing a message "Do you want to publish...". As we already know that the event cannot be published, it would make more sense to show a message: "You need to add more details such as location and tickets to your event in order to be able to publish." [Ok].

**Comment by Haider8** [comment]
@iamareebjamal Please review

event-unpublishable

File: app/templates/components/modals/publish-unpublish-modal.hbs [hunk 2]
```diff
@@ -1,12 +1,20 @@
 <i class="black close icon"></i>
 <div class="header">
-  {{t 'Are you sure?'}}
+	{{#if (or (eq this.state 'published') this.isEventPublishable)}}
+		{{t 'Are you sure?'}}
+	{{else}}
+		{{t 'Incomplete event details'}}
+	{{/if}}
```
Comment (iamareebjamal) [inline app/templates/components/modals/publish-unpublish-modal.hbs:7]: You have used tabs instead of spaces. Please use spaces

File: app/templates/components/modals/publish-unpublish-modal.hbs [hunk 3]
```diff
@@ -1,12 +1,20 @@
...
 <div class="content">
   {{#if (eq this.state 'published')}}
     <p>{{t 'This will unpublish your event. It will not be accessible to the public on the Internet anymore if you continue. The data of the event will still be available on your dashboard, but tickets, call for speakers or any other features will no longer be available online. Do you want to unpublish your event now?'}}</p>
   {{else}}
-    <p>{{t 'This will publish the event and the event will be visible on the Internet. Please confirm you want to publish your event.'}}</p>
+		{{#if this.isEventPublishable}}
+			<p>{{t 'This will publish the event and the event will be visible on the Internet. Please confirm you want to publish your event.'}}</p>
+		{{else}}
+			<p>{{t 'You need to add more details such as location and tickets to your event in order to publish it.'}}</p>
+		{{/if}}
```
Comment (iamareebjamal) [inline app/templates/components/modals/publish-unpublish-modal.hbs:17]: You have used tabs instead of spaces. Please use spaces

File: app/templates/components/modals/publish-unpublish-modal.hbs [hunk 4]
```diff
@@ -18,11 +26,17 @@
...
+				{{t 'Yes'}}
+			</button>
+			<button type="button" class="ui button" {{action 'toggleView'}}>
+				{{t 'Cancel, Do Not Publish it Now'}}
+			</button>
+		{{else}}
+			<button type="button" class="ui button" {{action 'toggleView'}}>
+				{{t 'Okay'}}
+			</button>
+		{{/if}}
```
Comment (iamareebjamal) [inline app/templates/components/modals/publish-unpublish-modal.hbs:40]: You have used tabs instead of spaces. Please use spaces

**Comment by iamareebjamal** [comment]
Merging now, please follow up with changing tabs to spaces
