### PR TITLE
fix: show globe icon for general web links

### LINKED ISSUE #4802: Public Event Page missing web link icon, e.g. globe or similar
Each link on the right side bar of an event has an icon. If there is no social media icon an event should have a link icon or globe icon, e.g. check https://eventyay.com/e/16fa59c7

Screenshot from 2020-08-19 01-10-18

### PR DESCRIPTION
**Pull request by snitin315**
Fixes #4802

#### Short description of what this resolves:

Show `globe` icon if the URL is not a standard social media URL.

#### Changes proposed in this pull request:
Screenshot at 2020-08-19 07-32-22

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests, and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/models/social-link.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6036123&bid=19779722)

File: app/models/social-link.js [hunk 1]
```diff
@@ -17,7 +17,13 @@ export default ModelBase.extend({
     // and non-null name is being sent from API, for some reason, for certain events,
     // this throws an error, so we check first if name exists
     // https://github.com/fossasia/open-event-frontend/issues/4777
-    return this.name && this.name.trim().toLowerCase();
+
+    let normalizedName = this.name.trim().toLowerCase();
```
Comment (iamareebjamal) [inline app/models/social-link.js:21]: Boom goes the last change. Read the comment above

File: app/models/social-link.js [hunk 2]
```diff
@@ -17,7 +17,13 @@ export default ModelBase.extend({
...
+    const socialPlatforms = ['facebook', 'twitter', 'github', 'youtube', 'linkedin', 'google'];
+    if (!socialPlatforms.includes(normalizedName)) {
```
Comment (snitin315) [inline app/models/social-link.js:23]:
```suggestion
    if (this.name && !socialPlatforms.includes(normalizedName)) {
```

Comment (iamareebjamal) [reply app/models/social-link.js:23]: No, the line I commented on will throw

Comment (snitin315) [reply app/models/social-link.js:23]: `normalizedName` will be equal to `globe` only if name exists.

Comment (iamareebjamal) [reply app/models/social-link.js:23]: See the line where I commented. What'll happen if name is null?

Comment (snitin315) [reply app/models/social-link.js:23]: won't it return `this.name && this.name.trim().toLowerCase()` just like before ?

Comment (iamareebjamal) [reply app/models/social-link.js:23]: You're looking at wrong line. Look at the line I commented on

Comment (snitin315) [reply app/models/social-link.js:23]: Oh, you mean the review comment. I was confused with the code comment.

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/models/social-link.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6036123&bid=19779722)

File: app/models/social-link.js [hunk 3]
```diff
@@ -17,7 +17,13 @@ export default ModelBase.extend({
     // and non-null name is being sent from API, for some reason, for certain events,
     // this throws an error, so we check first if name exists
     // https://github.com/fossasia/open-event-frontend/issues/4777
-    return this.name && this.name.trim().toLowerCase();
+
+    let normalizedName = this.name && this.name.trim().toLowerCase();
```
Comment (iamareebjamal) [inline app/models/social-link.js:21]:
```suggestion
    const normalizedName = this.name?.trim().toLowerCase();
```

File: app/models/social-link.js [hunk 4]
```diff
@@ -17,7 +17,13 @@ export default ModelBase.extend({
...
+    const socialPlatforms = ['facebook', 'twitter', 'github', 'youtube', 'linkedin', 'google'];
+    if (normalizedName && !socialPlatforms.includes(normalizedName)) {
```
Comment (iamareebjamal) [inline app/models/social-link.js:23]:
```suggestion
    if (!socialPlatforms.includes(normalizedName)) {
```

File: app/models/social-link.js [hunk 5]
```diff
@@ -17,7 +17,13 @@ export default ModelBase.extend({
...
+      normalizedName = 'globe';
```
Comment (iamareebjamal) [inline app/models/social-link.js:24]: return 'globe';

**Review by iamareebjamal — APPROVED** [review]
