### PR TITLE
fix: Renaming room does not rename it on the video edit page

### LINKED ISSUE #6859: Video Edit Page: Renaming room via wizard does not rename the room in video edit page
**Describe the bug**

 Renaming room via wizard does not rename the room in video edit page 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create event
2. Add video rooms
3. Edit room name via wizard
3. Go to video tab 
4. Click edit
5. Old video room name appears

**Expected behaviour**
The room should be renamed to the new name

**Screenshots**
Expected name - Microlocation Name Please
Shown - Microlocation Name
Screenshot from 2021-02-28 16-21-37
Screenshot from 2021-02-28 16-21-27

**Device -** 
ALL

### PR DESCRIPTION
**Pull request by MeghalBisht**
as discussed in meeting

fixes #6859

https://user-images.githubusercontent.com/61330148/108891514-d2af1a80-7634-11eb-9849-cfcedd2b3f86.mp4

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/components/forms/events/view/videoroom-form.js [hunk 1]
```diff
@@ -20,6 +20,11 @@ export default class VideoroomForm extends Component.extend(FormMixin) {
     return this.data.stream.rooms.toArray()[0];
   }
 
+  @computed('data.stream')
+  get roomName() {
+    return this.data.stream.rooms.toArray()[0] ? this.data.stream.rooms.toArray()[0].name : this.data.stream.name;
```
Comment (iamareebjamal) [inline app/components/forms/events/view/videoroom-form.js:25]:
```suggestion
    return this.data.stream.rooms.toArray()[0]?.name || this.data.stream.name;
```

**Comment by hpdang** [comment]
@MeghalBisht each PR should reference an issue. Please create one if it does not exist.

**Review by mariobehling — APPROVED** [review]
Works for me. Thanks.
