### PR TITLE
fix: error "Could not fetch from the server"

### LINKED ISSUE #6436: Draft Event: Settings Tab: Error - Could not fetch from the server
**Describe the bug**

After creating an event and marking it as draft. When "Settings Tab" is navigated.
Error occurs : Could not fetch from the server

**To Reproduce**
Steps to reproduce the behaviour:
1. Create event and mark it as draft
2. Go to "Manage Event"
3. Go to "Draft Event"
4. Navigate to the "Settings Tab"
5. Error occurs

**Screenshots**

Capture

**Desktop & Smartphones (please complete the following information):**
ALL

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #6436

### CODE REVIEW

File: app/components/events/view/export/api-response.js [hunk 1]
```diff
@@ -32,20 +32,31 @@ export default Component.extend({
 
   makeRequest() {
     this.set('isLoading', true);
+    if (this.event.state === 'draft') {
```
Comment (maze-runnar) [inline app/components/events/view/export/api-response.js:35]: this.event?.state

**Review by MeghalBisht — APPROVED** [review]
