### PR TITLE
fix: Adjust table in Organizers Attendees Overview Page

### LINKED ISSUE #5669: Organizers Attendees Overview Page: Adjust first column and move date
Please change the organizer attendees overview page as follows:
* from the first column take out the emails "by someemail@gmailliosomething.com"
* move "Date and Time" from first column to its own column
* create a column for "Date and Time" between ticket name and ticket price
* take out the xx days ago

Screenshot from 2020-11-17 10-33-44

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #5669 

#### Changes proposed in this pull request:
- from the first column take out the emails
- move "Date and Time" from first column to its own column
- create a column for "Date and Time" between ticket name and ticket price
- take out the xx days ago

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

__screenshots__

g1

### CODE REVIEW

File: app/components/ui-table/cell/events/view/tickets/attendees/cell-time.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import classic from 'ember-classic-decorator';
+import Component from '@ember/component';
+
+@classic
+export default class CellTime extends Component {}
```
Comment (iamareebjamal) [inline app/components/ui-table/cell/events/view/tickets/attendees/cell-time.js:5]: No need of empty components in octane

File: app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-time.hbs [hunk 2]
```diff
@@ -0,0 +1,5 @@
+{{#if (eq this.record.status 'completed')}}
```
Comment (iamareebjamal) [inline app/templates/components/ui-table/cell/events/view/tickets/attendees/cell-time.hbs:1]: `@record`

**Review by daretobedifferent18 — CHANGES_REQUESTED** [review]
fix the indentation of ```:``` in various places in list.hbs file

**Review by iamareebjamal — APPROVED** [review]
