### PR TITLE
Fix generation of access code & discount code url

### LINKED ISSUE #1166: Uncaught TypeError: Cannot read property 'events.view' of undefined
**Describe the bug**
When creating the Discount code or Access code, we get the following error:

```javascript
Uncaught TypeError: Cannot read property 'events.view' of undefined
    at Class.<anonymous> (create-discount-code.js:92)
    at ComputedPropertyPrototype.get (ember-metal.js:4067)
    at get (ember-metal.js:3439)
    at RootPropertyReference.compute (ember-glimmer.js:325)
    at RootPropertyReference.value (ember-glimmer.js:202)
    at ConcatReference.compute (runtime.js:187)
    at ConcatReference.value (reference.js:306)
    at Object.evaluate (runtime.js:1308)
    at AppendOpcodes.evaluate (runtime.js:44)
    at LowLevelVM.evaluateSyscall (runtime.js:3249)
```

**To Reproduce**
1. Go to view event
2. Click on tickets and then discount code
3. Click on create discount code
4. See error in the console

**Expected behavior**
The error shouldn't occur

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Browser : chrome
 - Version 65.0.3325.181 (Official Build) (64-bit)

**Additional context**
It's due to a deprecated parameter used here:
```
accessUrl  : computed('data.code', function() {
    const params = this.get('routing.router.router.state.params');
    return location.origin + this.get('router').urlFor('public', params['events.view'].event_id, { queryParams: { access_code: this.get('data.code') } });
  }),
```

The solution has already been discussed in the channel.

### PR DESCRIPTION
**Pull request by CosmicCoder96**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:

Fixes access code and discount code URL

Fixes #1166

### CODE REVIEW

**Comment by CosmicCoder96** [comment]
@niranjan94 Could this be a possible fix?

File: app/components/forms/events/view/create-access-code.js [hunk 1]
```diff
@@ -137,8 +137,8 @@ export default Component.extend(FormMixin, {
   },
   accessCode : '',
   accessUrl  : computed('data.code', function() {
-    const params = this.get('routing.router.router.state.params');
-    return location.origin + this.get('router').urlFor('public', params['events.view'].event_id, { queryParams: { access_code: this.get('data.code') } });
+    var routeHandlers = this.get('router._router.currentState.routerJs.currentHandlerInfos');
```
Comment (niranjan94) [inline app/components/forms/events/view/create-access-code.js]: You could just use https://github.com/fossasia/open-event-frontend/issues/1166#issuecomment-391858568
