### PR TITLE
fix: edit event accessible to user with event roles only

### LINKED ISSUE #3498: Inviting a second "Owner" breaks ownership
**Describe the bug**

If you invite a second owner, you lose partial ownership

**To Reproduce**
- Invite a member as "Owner"
- The other member accepts the invite, and has full access
- Go back to manage event, you own event dissapeared from your listing
- Access by url, the edit is available

Meanwhile, access is not totally lost as through the URL you can access edit
https://eventyay.com/events/$ID/edit/basic-details

but settings/dashboard are 404
https://eventyay.com/events/$ID/settings

### PR DESCRIPTION
**Pull request by shreyanshdwivedi**
Fixes #3498 

#### Short description of what this resolves:
Currently, any user can access edit page of the event.

#### Changes proposed in this pull request:
- Edit event page accessible to users with event roles only
- Owner role not available in Manage roles section

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/routes/events/view/edit.js [hunk 1]
```diff
@@ -12,6 +12,14 @@ export default Route.extend(AuthenticatedRouteMixin, EventWizardMixin, {
     if (transition.targetName === 'events.view.edit.index') {
       this.transitionTo('events.view.edit.basic-details');
     }
+
+    let event = this.modelFor('events.view');
+    let { currentUser } = this.authManager;
+    if (!(currentUser.isAnAdmin || currentUser.email === event.owner.get('email') || event.organizers.includes(currentUser)
+        || event.coorganizers.includes(currentUser) || event.trackOrganizers.includes(currentUser)
```
Comment (kushthedude) [inline app/routes/events/view/edit.js]: @shreyanshdwivedi Just make sure if this hierarchy correct, I mean not every `event role` should have access to `Edit Page`. Confirm with @CosmicCoder96 or @mariobehling once, Else it is gtg.

Comment (shreyanshdwivedi) [reply app/routes/events/view/edit.js]: I think currently we are giving full access to all the event roles. @CosmicCoder96 is there any role which is needed to be removed?

**Comment by shreyanshdwivedi** [comment]
@kushthedude @uds5501 @mrsaicharan1 please review
