### PR TITLE
fix: dropdown menu stays on top

### LINKED ISSUE #6122: Mobile Views: Make Event Dropdown Menu Stay on Top When user Scrolls Down Further
Many pages have this feature where a special menu stays on top of the page when a user scrolls down. Please implement the same thing for the drop-down event menu on public event pages.

When the user scrolls down keep the menu on top of the screen. When the user reaches the area "Tickets" show the menu item "Tickets" in the menu and so forth. Implement this on all public event pages for the mobile view.

Screenshot from 2020-12-23 11-03-47

### PR DESCRIPTION
**Pull request by Deepak-032**
Fixes #6122

#### Short description of what this resolves:
Many pages have this feature where a special menu stays on top of the page when a user scrolls down. Please implement the same thing for the drop-down event menu on public event pages.

When the user scrolls down keep the menu on top of the screen. When the user reaches the area "Tickets" show the menu item "Tickets" in the menu and so forth. Implement this on all public event pages for the mobile view.

#### Changes proposed in this pull request:
Screenshot 2021-06-16 234834
- Now the menu sticks at the top when the user scrolls down for the mobile view.
- When the user reaches the area "Tickets", the menu sticked at the top shows the menu item "Tickets" from the menu for mobile view.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/components/side-bar.js [hunk 1]
```diff
@@ -58,3 +58,22 @@ export default class SideBar extends Component {
...
+    if ($(window).scrollTop() > menuPosition) {
+      $('#public-event-content').addClass('fixed');
+    } else {
+      $('#public-event-content').removeClass('fixed');
+    }
+    const ticketPosition = $('#tickets').offset().top;
+    if ($(window).scrollTop() > ticketPosition) {
+      $('#public-event-content .text').html('<i class="mr-4  ticket icon"></i>Tickets');
+    } else {
+      $('#public-event-content .text').html('<i class="mr-4  info icon"></i>Info');
```
Comment (maze-runnar) [inline app/components/side-bar.js:76]: above code is cool, but why you need to do this ?

**Review by maze-runnar — APPROVED** [review]

File: app/components/side-bar.js (hunk 1 above)
Comment (Deepak-032) [reply app/components/side-bar.js]: This is done to fix the position of the menu bar at the top on scroll and from line no 72 to 76 as above mentioned by using this I'm changing the default displayed text of the menu bar to "Tickets" when user scroll down and reaches to the ticket section, because this is what the need as described in the problem!

**Review by MeghalBisht — APPROVED** [review]

**Review by ranjitkshah — APPROVED** [review]
