### PR TITLE
fix: search via user email in order table

### LINKED ISSUE #4237: Organizer Event Ticket Order Overview: Search not working, Date Sorting according to day instead of day, month, year
On the Organizer Event Ticket Order Overview page:
* the search not working
* the Date Sorting according is according to day instead of day, month, year. This means currently e.g. 18th February is in front of 15th of March.

Screenshot from 2020-03-17 19-14-08

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4237 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/routes/events/view/tickets/orders/list.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6296910&bid=20481777)

File: app/routes/events/view/tickets/orders/list.js [hunk 1]
```diff
@@ -19,18 +19,49 @@ export default class extends Route.extend(EmberTableRouteMixin) {
...
+              op   : 'has',
+              val  : {
+                name : 'email',
+                op   : 'ilike',
+                val  : `%${params.search}%`
+              }
+            }
+          ]
+        }
+      ];
```
Comment (iamareebjamal) [inline app/routes/events/view/tickets/orders/list.js:43]: Just push in search options if search is present. No need to create 2 more conditions like this. See the implementation of applySearchFilters

File: app/routes/events/view/tickets/orders/list.js [hunk 2]
```diff
@@ -19,18 +19,35 @@ export default class extends Route.extend(EmberTableRouteMixin) {
...
+        name : 'user',
+        op   : 'has',
+        val  : {
+          name : 'email',
+          op   : 'ilike',
+          val  : `%${params.search}%`
         }
-      ];
+      });
+    }
```
Comment (iamareebjamal) [inline app/routes/events/view/tickets/orders/list.js:43]: No need of removing since this is a new array

**Review by iamareebjamal — APPROVED** [review]
