### PR TITLE
null type removed if sponsor type is not provided

### LINKED ISSUE #2337: Null should not be visible if sponsor type is not provided
**Describe the bug**
Null is written if sponsor type is not provided

**Screenshots**
sponsor

**Additional context**
I am working on it

### PR DESCRIPTION
**Pull request by shubham3211**
#### Short description of what this resolves:
null type removed if sponsor type is not provided

Fixes #2337

### CODE REVIEW

**Comment by shreyanshdwivedi** [comment]
@shubham3211 please extend this PR and add this check in `Sponsors` on Event overview page.

File: app/components/ui-table/cell/cell-sponsor-sanitize.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import Component from '@ember/component';
```
Comment (ritikamotwani) [inline app/components/ui-table/cell/cell-sponsor-sanitize.js]: Remove this file. It has no functions it is not needed.

File: app/templates/components/ui-table/cell/cell-sponsor-sanitize.hbs [hunk 2]
```diff
@@ -0,0 +1,3 @@
+{{#if (not-eq record.type 'null')}}
+  <span>{{record.type}}</span>
```
Comment (ritikamotwani) [inline app/templates/components/ui-table/cell/cell-sponsor-sanitize.hbs]: Instead of hard-coding a property within the template, use the propertyName to retrieve it.

With something like (get record column.propertyName) in the template

**Comment by shubham3211** [comment]
@CosmicCoder96 @ritikamotwani  please review.

File: app/templates/components/ui-table/cell/cell-sponsor-sanitize.hbs [hunk 3]
```diff
@@ -0,0 +1,3 @@
+{{#if (not-eq (get record column.propertyName) null)}}
```
Comment (CosmicCoder96) [inline app/templates/components/ui-table/cell/cell-sponsor-sanitize.hbs]: if a property is null, you don't need to compare it with null to make this if condition true. the `not-eq` is redundant.
