### PR TITLE
 fix: Registration deadline not working

### LINKED ISSUE #5692: Registration deadline not working
**Describe the bug**

Registration deadline not working
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to eventyay.com
2. Click on any event and place order
3. After 15 minutes of registration process, the clock shows 59:59 

**Expected behaviour**
It should show an alert message that order is cancelled
**Screenshots**

Screenshot from 2020-11-19 12-43-20

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5692 

#### Short description of what this resolves:
Registration deadline not working

#### Changes proposed in this pull request:

- Set status to expired

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
Screenshot from 2020-11-19 18-05-32
---
Screenshot from 2020-11-19 18-08-24
@iamareebjamal Please see the changes

File: app/components/forms/orders/order-form.js [hunk 1]
```diff
@@ -53,10 +53,12 @@ export default Component.extend(FormMixin, {
     run.later(() => {
       const currentTime = moment();
       const diff = moment.duration(willExpireAt.diff(currentTime));
-      this.set('getRemainingTime', moment.utc(diff.asMilliseconds()).format('mm:ss'));
       if (diff > 0) {
+        this.set('getRemainingTime', moment.utc(diff.asMilliseconds()).format('mm:ss'));
         this.timer(willExpireAt, orderIdentifier);
       } else {
+        this.set('getRemainingTime', '00:00');
```
Comment (iamareebjamal) [inline app/components/forms/orders/order-form.js:60]: Why?

Comment (daretobedifferent18) [reply app/components/forms/orders/order-form.js:60]: bcz if we go to order/new page again after order is expired, timer again set 'getRemainingTime which is different value and show this value for a sec and should show 00.00, and then transition to order/expired page so instead of showing diff value , should show 00.00

Comment (iamareebjamal) [reply app/components/forms/orders/order-form.js:60]: Correct

**Review by iamareebjamal — APPROVED** [review]
