### PR TITLE
fix: cfs on public route does not show up on fresh reload

### LINKED ISSUE #1297: CFS side menu does not load sometimes
**Describe the bug**
Sometimes CFS side menu does not appear for events page.

**To Reproduce**
1. Go to any event that has CFS enabled.
2. Hard Refresh
3. CFS may not be seen.

**Expected behavior**
We should see CFS everytime if it is enabled.

### PR DESCRIPTION
**Pull request by pradeepgangwar**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Sometimes CFS does not show up specially on fresh reload.

#### Changes proposed in this pull request:
- use asynchronous call.

Fixes #1297

### CODE REVIEW

File: app/components/public/side-menu.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ import Component from '@ember/component';
 import { computed } from '@ember/object';
 
 export default Component.extend({
-  shouldShowCallforSpeakers: computed(function() {
-    return this.get('event.isSessionsSpeakersEnabled') && (this.get('event.speakersCall.privacy') === 'public');
+  shouldShowCallforSpeakers: computed(async function() {
```
Comment (niranjan94) [inline app/components/public/side-menu.js]: This is incorrect. Don't perform async tasks within computed properties. Instead, do this on `didInsertElement` and set `shouldShowCallforSpeakers`

**Comment by pradeepgangwar** [comment]
@niranjan94 did the changes. Please review. I am not sure about placing async for `didInsertElement()` method

**Comment by srv-twry** [comment]
@niranjan94 @pradeepgangwar I have merged this PR since it was stalled. @niranjan94 You can follow up on this if you want something wrong.
