### PR TITLE
fix: save wizard as draft on each step

### LINKED ISSUE #4712: Wizard Step 3 and Step 4: Not possible to save draft
The wizard in step 3 and 4 cannot save the event as expected.

In step 3 e.g. https://eventyay.com/events/921345bd/edit/sponsors is shows "Fill in required fields", whereas the option to use the form is switched off (but it was switched on and off before).

In step 4 there is not event an error message, but pressing "Save Draft" does not result in any action, e.g. at https://eventyay.com/events/921345bd/edit/sessions-speakers

Topic related to https://github.com/fossasia/open-event-frontend/issues/4673

Screenshot from 2020-08-05 12-19-04

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #4712 

#### Short description of what this resolves:
Wizard Step 3 and Step 4: Not possible to save draft

#### Changes proposed in this pull request:

Allow saving as draft on each step..
ezgif com-optimize

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by maze-runnar** [comment]
@iamareebjamal, please review.

File: app/components/forms/wizard/sponsors-step.js [hunk 1]
```diff
@@ -54,19 +54,8 @@ export default Component.extend(FormMixin, {
...
-        });
-        if (incorrect_sponsors.length > 0) {
-          this.notify.error(this.l10n.t('Please fill the required fields.'), {
-            id: 'req_field_spon'
-          });
-          this.set('isLoading', false);
-        } else {
-          this.set('data.event.state', 'draft');
-          this.sendAction('save');
-        }
```
Comment (iamareebjamal) [inline app/components/forms/wizard/sponsors-step.js:69]: Why remove this?

Comment (maze-runnar) [reply app/components/forms/wizard/sponsors-step.js:69]: when the data is validated then there is no need for rest. This part is supposed to be in addSponser function only.

Comment (iamareebjamal) [reply app/components/forms/wizard/sponsors-step.js:69]: So is it present there?

Comment (maze-runnar) [reply app/components/forms/wizard/sponsors-step.js:69]: yes it is present there.
