### PR TITLE
fix: Issues with Modal and Image Cropper position

### LINKED ISSUE #4505: Tax information pop up in Wizard step 1 showing up towards bottom of screen
The tax pop up in the wizard step on should show up more towards the top of the screen and it should have a "close" x icon on its top right.

Screenshot from 2020-06-29 23-39-21

### LINKED ISSUE #4716: Cropper modal in event-create wizard is not correctly positioned
**Describe the bug**
Cropper modal in event-create wizard is not correctly positioned

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/create
2. Click on select event image
3. See error

Screenshot from 2020-08-05 23-19-24
Screenshot from 2020-08-05 23-19-29

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I will work on it.

### LINKED ISSUE #4837: Organizer Session Notifications: Message Box if Off-Screen
When an organizer tries to send a notification email to a speaker the message is off-screen in some resolutions and cannot be accessed fully or scrolled to the right position.

Screenshot from 2020-08-21 16-40-35

### LINKED ISSUE #4917: Interface error when organizer uploads speaker's image
**Describe the bug**
Interface error when organizer uploads speaker's image

**To Reproduce**
- Event organizer goes to an existing session and adds additional speakers into the session e.g. https://eventyay.com/events/8fa7fd14/sessions/6275/edit
- Upload the speaker's photo

**Screenshots**
Screenshot from 2020-08-29 15-50-23

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome

### LINKED ISSUE #5308: Speaker Notification: HTML code in message and pop up not entirely visible
The pop up notification box has some issues:
1. There is html code on the bottom of the message
2. The pop up is partly hidden
* behind an area that should be below on top and bottom
* buttons are hidden
* top area is hidden

Compare https://eventyay.com/events/5ac8e4d9/sessions/all
Screenshot from 2020-10-14 08-22-29

### PR DESCRIPTION
**Pull request by sachinchauhan2889**
Fixes #4837, #4917, #4716, #4505, #5308

#### Short description of what this resolves:

this PR can solve issue #5308 #4917 #4837 #4716 #4505 .

__changes__
- fix #4837 now session notify modal is perfectly placed.
- fix #4917 Cropper modal(for speaker image) is positioned right.
- fix #4716 image cropper(for event creation) is positioned right.
- fix #4505 Tax information modal is positioned well. It have close icon on right top. It can open and close multiple times.
- fix #5308 session notify modal is perfectly visible.

I have tested all modals and croppers mentioned above from all scroll positions and get modal at center.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

__screenshots__

#4505 
final 4505

#4716 
final 4716

#4837 #5308 
final 4837 5308

#4917 
final 4917

### CODE REVIEW

File: app/components/modals/modal-base.js [hunk 1]
```diff
@@ -7,12 +7,18 @@ import { isTesting } from 'open-event-frontend/utils/testing';
...
 
-  openObserver: observer('isOpen', function() {
+  openObserver: observer('isOpen', 'noCroppper', function() {
     const $element = $(this.element);
     if (this.isOpen) {
-      $element.modal('show');
+      if (this.noCropper) {
+        $element.modal({
+          centered: false
+        }).modal('show');
```
Comment (iamareebjamal) [inline app/components/modals/modal-base.js:18]: This will ignore all the settings done in the modal below. As evident by the dark dimmer in the modal. Make this change in the settings below

File: app/components/modals/session-notify-modal.js [hunk 2]
```diff
@@ -16,6 +16,7 @@ export default class SessionNotifyModal extends ModalBase {
 
   constructor() {
     super(...arguments);
+    this.noCropper = true;
```
Comment (iamareebjamal) [inline app/components/modals/session-notify-modal.js:19]: Pass this as a prop rather than setting here

**Comment by sachinchauhan2889** [comment]
@iamareebjamal thank you for your reviews. i am working on changes suggested by you.

**Comment by iamareebjamal** [comment]
Like my review explained why changing it this way is not good enough, @mariobehling  has said

Thank you!

* [ ] Could you keep the overlay background semitransparent white, please for consistency?
* [ ] Please make the X button black (on white background).
* [ ] When a user closes the pop up using the X button and then clicks add tax information again nothing happens. Expected: It should open the pop up again.

**Comment by sachinchauhan2889** [comment]
> This will ignore all the settings done in the modal below. As evident by the dark dimmer in the modal. Make this change in the settings below

@iamareebjamal i try to make changes to settings in _willInitSemantic(settings){...}_ function.
But _centered_ property of modal not assigned with false. I think Settings of semantic ui modal not have any property named _centered_. https://semantic-ui.com/modules/modal.html#/settings

**Comment by sachinchauhan2889** [comment]
@iamareebjamal can i assign all properties here.
>$element.modal({
          centered: false
        }).

**Comment by iamareebjamal** [comment]
It should have the same interface of settings, but if it is not working, you can try that

File: app/components/modals/modal-base.js [hunk 3]
```diff
@@ -7,12 +7,50 @@ import { isTesting } from 'open-event-frontend/utils/testing';
...
+          }
+          return true;
+        },
+        onApprove: () => {
+          if (this.onApprove) {
+            this.onApprove();
+          }
+          return true;
+        },
+
```
Comment (niranjan94) [inline app/components/modals/modal-base.js:41]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563&bid=20732298)

**Comment by sachinchauhan2889** [comment]
@iamareebjamal please have a look at this. 
Now this PR can solve issue #5308 #4917 #4837 #4716 #4505 .

__changes__
- fix #4837 now session notify modal is perfectly placed.
- fix #4917 Cropper modal(for speaker image) is positioned right.
- fix #4716 image cropper(for event creation) is positioned right.
- fix #4505 Tax information modal is positioned well. It have close icon on right top. It can open and close multiple times.
- fix #5308 session notify modal is perfectly visible.

I have tested all modals and croppers mentioned above from all scroll positions and get modal at center.

__screenshots__

#4505 
final 4505

#4716 
final 4716

#4837 #5308 
final 4837 5308

#4917 
final 4917

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563&bid=20732298)

File: app/components/modals/modal-base.js (hunk 3 above)
Comment (niranjan94) [inline app/components/modals/modal-base.js:41]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563&bid=20732298)

File: app/components/modals/modal-base.js (hunk 3 above)
Comment (niranjan94) [inline app/components/modals/modal-base.js:41]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

File: app/components/modals/modal-base.js [hunk 4]
```diff
@@ -7,12 +7,50 @@ import { isTesting } from 'open-event-frontend/utils/testing';
...
 export default UiModal.extend({
   tagName           : 'div',
+  classNames        : ['centered-modal'],
   classNameBindings : ['isFullScreen:fullscreen', 'isSmall:small', 'isLarge:large'],
 
   openObserver: observer('isOpen', function() {
     const $element = $(this.element);
     if (this.isOpen) {
-      $element.modal('show');
+      $element.modal({
```
Comment (iamareebjamal) [inline app/components/modals/modal-base.js:16]: Copied code. Move to a single function

File: app/components/modals/modal-base.js [hunk 5]
```diff
@@ -91,7 +129,44 @@ export default UiModal.extend({
 
   didInitSemantic() {
     if (this.isOpen) {
-      $(this.element).modal('show');
+      $(this.element).modal({
```
Comment (iamareebjamal) [inline app/components/modals/modal-base.js:132]: Duplicate code. Remove any duplicate code

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563&bid=20732298)

File: app/components/modals/modal-base.js (hunk 3 above)
Comment (niranjan94) [inline app/components/modals/modal-base.js:41]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

File: app/templates/components/modals/tax-info-modal.hbs [hunk 6]
```diff
@@ -1,3 +1,4 @@
+<i class="black close icon"></i>
```
Comment (iamareebjamal) [inline app/templates/components/modals/tax-info-modal.hbs:1]: There is already a closable icon in the modal I believe?

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563&bid=20732298)

File: app/components/modals/modal-base.js [hunk 7]
```diff
@@ -85,13 +87,13 @@ export default UiModal.extend({
...
 
-    const options = this.options ? merge(defaultOptions, this.options) : defaultOptions;
+    const options = this.options ? merge(this.defaultOptions, this.options) : this.defaultOptions;
     assign(settings, options);
   },
 
   didInitSemantic() {
     if (this.isOpen) {
-      $(this.element).modal('show');
+      $(this.element).modal({...this.defaultOptions}).modal('show');
```
Comment (niranjan94) [inline app/components/modals/modal-base.js:96]: Codacy found an issue: [A space is required after '{'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

File: app/components/modals/modal-base.js [hunk 8]
```diff
@@ -7,12 +7,14 @@ import { isTesting } from 'open-event-frontend/utils/testing';
...
 export default UiModal.extend({
   tagName           : 'div',
+  classNames        : ['centered-modal'],
   classNameBindings : ['isFullScreen:fullscreen', 'isSmall:small', 'isLarge:large'],
 
   openObserver: observer('isOpen', function() {
     const $element = $(this.element);
     if (this.isOpen) {
-      $element.modal('show');
+      console.log(this.defaultOptions);
```
Comment (niranjan94) [inline app/components/modals/modal-base.js:16]: Codacy found an issue: [Unexpected console statement.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

File: app/components/modals/modal-base.js [hunk 9]
```diff
@@ -7,12 +7,14 @@ import { isTesting } from 'open-event-frontend/utils/testing';
...
+      $element.modal({...this.defaultOptions}).modal('show');
```
Comment (niranjan94) [inline app/components/modals/modal-base.js:17]: Codacy found an issue: [A space is required after '{'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

File: app/templates/components/modals/tax-info-modal.hbs (hunk 6 above)
Comment (sachinchauhan2889) [reply app/templates/components/modals/tax-info-modal.hbs:1]: @iamareebjamal not present earlier. please see #4505

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563&bid=20732298)

File: app/components/modals/modal-base.js [hunk 10]
```diff
@@ -85,13 +86,13 @@ export default UiModal.extend({
...
 
-    const options = this.options ? merge(defaultOptions, this.options) : defaultOptions;
+    const options = this.options ? merge(this.defaultOptions, this.options) : this.defaultOptions;
     assign(settings, options);
   },
 
   didInitSemantic() {
     if (this.isOpen) {
-      $(this.element).modal('show');
+      $(this.element).modal({...this.defaultOptions}).modal('show');
```
Comment (niranjan94) [inline app/components/modals/modal-base.js:95]: Codacy found an issue: [A space is required after '{'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

File: app/components/modals/modal-base.js [hunk 11]
```diff
@@ -7,12 +7,13 @@ import { isTesting } from 'open-event-frontend/utils/testing';
...
 export default UiModal.extend({
   tagName           : 'div',
+  classNames        : ['centered-modal'],
   classNameBindings : ['isFullScreen:fullscreen', 'isSmall:small', 'isLarge:large'],
 
   openObserver: observer('isOpen', function() {
     const $element = $(this.element);
     if (this.isOpen) {
-      $element.modal('show');
+      $element.modal({...this.defaultOptions}).modal('show');
```
Comment (niranjan94) [inline app/components/modals/modal-base.js:16]: Codacy found an issue: [A space is required after '{'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6392563)

**Comment by sachinchauhan2889** [comment]
@iamareebjamal  please have a look at this PR. i have removed Duplicacy of code.

File: app/components/modals/modal-base.js (hunk 11 above)
Comment (iamareebjamal) [inline app/components/modals/modal-base.js:16]:
```suggestion
      $element.modal(this.defaultOptions).modal('show');
```

File: app/components/modals/modal-base.js (hunk 10 above)
Comment (iamareebjamal) [inline app/components/modals/modal-base.js:95]:
```suggestion
      $(this.element).modal(this.defaultOptions).modal('show');
```

**Comment by iamareebjamal** [comment]
Since now you're only using the default options of the modal, what's the need for passing them in the `modal(this.defaultOptions)` call? Try removing them and try again, it should work without passing the settings

**Comment by sachinchauhan2889** [comment]
> Since now you're only using the default options of the modal, what's the need for passing them in the `modal(this.defaultOptions)` call? Try removing them and try again, it should work without passing the settings


@iamareebjamal sir i have tried this but modal is not appearing at center. All properties are present in settiings of modal but _centered: false_ is not present in settings. For this _centered: false_ property i have used defaultOptions object and pass it here.

I think this is because the settings of semantic ui modal not contain _centered_ as property. This is why i have make _defaultOptions_ object in init() function and use this object in _$(this.element).modal(defaultOptions).modal('show')_.

_$(this.element).modal('show')_ is not working.

i have done all changes suggested by you. have a look at this.

**Comment by iamareebjamal** [comment]
Checking

**Comment by iamareebjamal** [comment]
Good job. But there are still some issues. I am mentioning them one by one.

#4837: If you decrease the height of the screen a little bit, the modal shifts to right
image

Test on heights < 825px

**Comment by iamareebjamal** [comment]
I think your styles are being overriden in a media query

**Comment by iamareebjamal** [comment]
When the screen is smaller in height than 825px, semantic adds `left: 50%` which shifts the dialog further to the right. You need to add `left:auto !important` in your CSS style to make sure it stays in center at any height

**Review by iamareebjamal — APPROVED** [review]

**Comment by iamareebjamal** [comment]
Thanks a lot for solving a complex and long standing issue with little code changes elegantly

**Comment by sachinchauhan2889** [comment]
> Thanks a lot for solving a complex and long standing issue with little code changes elegantly


@iamareebjamal my pleasure sir
