### PR TITLE
fix: Show more readable error msg on duplicate role invite

### LINKED ISSUE #7229: User Cannot Change "Owner" of Event
Users who try to change the owner of an event receive the following error:

> Ember Data Request POST https://api.eventyay.com/v1/role-invites returned a 409 Payload (application/vnd.api+json) [object Object]

### PR DESCRIPTION
**Pull request by MeghalBisht**
Fixes #7229

#### Short description of what this resolves:
Screenshot from 2021-05-05 20-38-59

Additional Info -
This is happening when
A sent an invite to B - Works
Invitation is in pending state as B has not accepted
A sends invitation again to B - Error msg as invite is already sent

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/controllers/events/view/settings/options.js [hunk 1]
```diff
@@ -73,7 +73,11 @@ export default class OptionsController extends Controller {
       this.notify.success(this.l10n.t('Owner Role Invite sent successfully.'));
     } catch (error) {
       console.error('Error while sending role Invite', error, error.message);
-      this.notify.error(error.message);
+      if (error.errors[0]?.status === 409) {
+        this.notify.error(error.errors[0]?.detail);
+      } else {
+        this.notify.error(error.message);
+      }
```
Comment (maze-runnar) [inline app/controllers/events/view/settings/options.js:80]: @MeghalBisht can we use errorHandler service here?

Comment (MeghalBisht) [reply app/controllers/events/view/settings/options.js:80]: Yes, thanks

**Review by maze-runnar — APPROVED** [review]

**Review by sachinchauhan2889 — APPROVED** [review]
