### PR TITLE
Fix bugs in Basic Details

### LINKED ISSUE #2222: Fix Bugs in Edit Basic Details
**Describe the bug**
1.Organiser name is not required if Add Organiser details is checked. This allows the user to save organiser description without organiser name.
2.Max number of tickets that can be purchased can be assigned a value 0 in ticketing section. 

**To Reproduce**
1. Go to 'Overview'
2. Click on 'Basic Details'
3. Scroll down to 'Add organiser info and use ticketing system'

**Expected behavior**
1.Organiser name should be required if Add Organiser details is checked.
2.Max number of tickets that can be purchased should show error on assigning a value 0 in ticketing section. 

**Screenshots**

**Additional context**

I'm working on it.

### PR DESCRIPTION
**Pull request by harsh-jindal**
#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [X] My branch is up-to-date with the Upstream `development` branch.
- [X] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fix bugs in Basic Details
#### Changes proposed in this pull request:
screenshot 2019-02-23 at 2 59 48 am

Fixes #2222

### CODE REVIEW

File: app/components/forms/wizard/basic-details-step.js [hunk 1]
```diff
@@ -307,6 +311,15 @@ export default Component.extend(FormMixin, EventWizardMixin, {
               prompt : this.get('l10n').t('Please enter a valid url')
             }
           ]
+        },
+        organizerName: {
```
Comment (CosmicCoder96) [inline app/components/forms/wizard/basic-details-step.js]: we don't need organizer name to be mandatory.

**Comment by harsh-jindal** [comment]
@CosmicCoder96 Made the changes.
