### PR TITLE
fix: Session times in public session list

### LINKED ISSUE #4238: Public Schedule: Times of sessions are displayed wrongly
The session times are displayed wrongly even though I am in the same time zone of the event.

Screenshot from 2020-03-18 10-30-03

### PR DESCRIPTION
**Pull request by Haider8**
Fixes #4238 

#### Short description of what this resolves:
Session time was wrong

#### Changes proposed in this pull request:
Show session time after converting to that event's timezone

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@Haider8 Travis Build is failing

**Comment by Haider8** [comment]
@iamareebjamal Couldn't fix, need help. It says `Cannot read property 'get' of undefined`

**Comment by iamareebjamal** [comment]
See the code you have added and the test which is failing. Should be clear why the test fails

**Comment by Haider8** [comment]
I am using this line to get the event timezone, `this.session.event.get('timezone')`.

**Comment by iamareebjamal** [comment]
Yes, and see the test which is failing

**Comment by iamareebjamal** [comment]
Still failing

File: app/components/public/session-item.js [hunk 1]
```diff
@@ -15,4 +16,9 @@ export default class SessionItem extends Component {
       this.set('hideImage', false);
     }
   }
+
+  @computed('session.event', 'session.startsAt')
+  get sessionStartsAtInEventTimezone() {
+    return moment.tz(this.session.startsAt, this.session.event.get('timezone'));
```
Comment (iamareebjamal) [inline app/components/public/session-item.js:22]: What happens if you use `session.event.timezone`?

Comment (Haider8) [reply app/components/public/session-item.js:22]: It tells that since `session.event` is a proxy, it will be better that I use `.get()` rather than directly accessing that property.

Comment (iamareebjamal) [reply app/components/public/session-item.js:22]: Then wrap event in EmberObject in the test

**Comment by iamareebjamal** [comment]
Like this https://github.com/fossasia/open-event-frontend/blob/c1572e612397709182437b2858798b57c8bb76cd/tests/integration/components/order-card-test.js#L11

File: app/components/public/session-item.js (hunk 1 above)
Comment (Haider8) [reply app/components/public/session-item.js:22]: Like this ?
```js
`event: EmberObject.create({ timezone: 'Asia/Kolkata' })
```

Comment (iamareebjamal) [reply app/components/public/session-item.js:22]: Yes
