### PR TITLE
fix: add a popup for new cfs speakers as a message

### LINKED ISSUE #2973: After adding Personal Details to Call for Speakers Pop up for Session Details does not show up
Users are left clueless what to do after they add their personal details in a call for speakers. Expected is, that the pop up opens with the info "Please add your session details".

At least the below pop up should open, but it does not.

Screenshot from 2019-05-20 14-47-36

### PR DESCRIPTION
**Pull request by uds5501**
Fixes #2973

#### Short description of what this resolves:
Adds an instructional message for new cfs speakers

#### Changes proposed in this pull request:

- Show a modal which instructs them to click submit proposal button for adding session details

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by uds5501** [comment]
image
This is the message being displayed right now for a new Speaker with no session yet. 
@mariobehling I hope you wanted the implementation to be something like this.

**Comment by kushthedude** [comment]
@uds5501 Can you provide `Submit Proposal` button in the `Modal` too, It would be better I think

File: app/components/public/call-for-speakers.js [hunk 1]
```diff
@@ -2,6 +2,10 @@ import Component from '@ember/component';
 import { computed } from '@ember/object';
 
 export default Component.extend({
+  isCfsModalOpen: computed('isNewSpeaker', 'isnewSession', function() {
+    this.set('showSessionMessage', true);
+    return (this.get('session.isAuthenticated') && !this.isNewSpeaker && this.isNewSession);
+  }),
   actions: {
     openModal() {
       if (this.get('session.isAuthenticated')) {
```
Comment (mrsaicharan1) [inline app/components/public/call-for-speakers.js]: Add a similar action for closeModal()

File: app/templates/components/modals/cfs-proposal-modal.hbs [hunk 2]
```diff
@@ -1,3 +1,4 @@
+{{isOpen}}
 <i class="black close icon"></i>
```
Comment (shreyanshdwivedi) [inline app/templates/components/modals/cfs-proposal-modal.hbs]: This may be the root that your modal is not closing. Please use `{{action 'close'}}` just like in this line - https://github.com/fossasia/open-event-frontend/blob/2d4031f83d1e797515e6fd79ecdb5570f9192edb/app/templates/components/modals/confirm-user-delete-modal.hbs#L13

File: app/components/modals/cfs-proposal-modal.js [hunk 3]
```diff
@@ -3,7 +3,9 @@ import ModalBase from 'open-event-frontend/components/modals/modal-base';
 export default ModalBase.extend({
   actions: {
     toggleView() {
+      console.log('hitting close, currently', this.isOpen);
```
[the remark this answers is not in the document]
Comment (kushthedude) [reply app/components/modals/cfs-proposal-modal.js]: @uds5501 Why you are using console.log or is it for testing purpose?

**Comment by uds5501** [comment]
@CosmicCoder96 I am having trouble in closing the modal, can you please take a look?

**Comment by kushthedude** [comment]
> @CosmicCoder96 I am having trouble in closing the modal, can you please take a look?

Did you try, what @shreyanshdwivedi told you?

**Comment by uds5501** [comment]
@kushthedude , yes, still failed . @shreyanshdwivedi also tried debugging the issue on his local but no luck, maybe you could give it a try too?? 😅

**Comment by kushthedude** [comment]
@uds5501 Pulling on local

**Comment by kushthedude** [comment]
@uds5501 I pulled your changes local and to your notice No Pop-Up appeared for me when i added a speaker

**Comment by uds5501** [comment]
That's weird, @shreyanshdwivedi @mrsaicharan1 did you face the same error?

**Comment by mrsaicharan1** [comment]
> That's weird, @shreyanshdwivedi @mrsaicharan1 did you face the same error?

Checking it

**Comment by mrsaicharan1** [comment]
@uds5501 Are you able to open a new cfs for an event? 
Screenshot 2019-05-22 at 8 37 26 AM

**Comment by mrsaicharan1** [comment]
> > That's weird, @shreyanshdwivedi @mrsaicharan1 did you face the same error?
> 
> Checking it

@uds5501 @kushthedude Works fine. There seems to be no issue.

**Comment by uds5501** [comment]
@shreyanshdwivedi @mrsaicharan1 since I could not take down this modal closing issue, I decided to take this implementation like that of Unverified User Message. Please take a look.
image

File: app/templates/components/create-session-message.hbs [hunk 4]
```diff
@@ -0,0 +1,9 @@
+{{#if shouldShowMessage}}
+  <div class="ui icon info message eight wide column center aligned">
+    <i class="close icon" onclick={{action (mut isMessageVisible) false}} role="button"></i>
+    <i class="info icon"></i>
+    <div class="content">
+      {{t 'Your Speaker Details have been saved, you can now submit a proposal by clicking Submit proposal!'}}
```
Comment (shreyanshdwivedi) [inline app/templates/components/create-session-message.hbs]: @uds5501 the issue asks for a different approach. But in my opinion, this is a better way as we are not forcing the speaker to fill in the session details as soon as he/she fills up speaker data.
However @CosmicCoder96 can decide which approach to follow

**Comment by CosmicCoder96** [comment]
This looks good, solved the purpose of the issue. We have a different kind
of refactor planned for somewhere around second phase. Until then this
seems like a good choice.

File: app/components/create-session-message.js [hunk 5]
```diff
@@ -0,0 +1,15 @@
+import Component from '@ember/component';
+import { computed } from '@ember/object';
+
+export default Component.extend({
+
+  isMessageVisible  : true,
+  shouldShowMessage : computed('session.isAuthenticated', 'isMessageVisible', 'isNewSpeaker', 'isNewSession', function() {
+    let speakerIDlength = this.data.userSpeaker.toArray().length;
```
Comment (CosmicCoder96) [inline app/components/create-session-message.js]: what's this for, I don't get the logic?

Comment (kushthedude) [reply app/components/create-session-message.js]: @CosmicCoder96 I think its to check if the speaker is added or not

Comment (uds5501) [reply app/components/create-session-message.js]: @CosmicCoder96 Just a moment, letting you where I picked it up from. Essentially it is for making sure that user has saved his/her speaker details in that particular cfs. If i must have opened any other event's cfs, I could get the popup already opened without any submission of speaker details. This basically avoids that faulty popup (see this : https://github.com/fossasia/open-event-frontend/blob/f35372d9cb5a208a93ee3fe3ceb125b9a1c42da0/app/templates/components/modals/cfs-proposal-modal.hbs#L34 )
