### PR TITLE
Fix minor bugs with cfs speaker and session creation

### LINKED ISSUE #1410: Fix minor bugs with CFS
**Describe the bug**
- Most of the time if we create a from speaker and then go to /events/view/session or speaker without saving the cfs speaker it shows a blank entry.
- If user has not filled his first name and last name it comes as `null null` in text field.
- For the same route we have two create record the second on present in session-speaker-form component is not required.

### PR DESCRIPTION
**Pull request by pradeepgangwar**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
- Most of the time if we create a from speaker and then go to /events/view/session or speaker without saving the cfs speaker it shows a blank entry.
- If user has not filled his first name and last name it comes as `null null` in text field.
- For the same route we have two `createRecord` instances the second on present in session-speaker-form component is not required.

#### Changes proposed in this pull request:
- Add necessary code to fix above issues.

Fixes #1410

### CODE REVIEW

File: app/routes/public/cfs/new-speaker.js [hunk 1]
```diff
@@ -7,16 +7,30 @@ export default Route.extend({
...
         'page[size]' : 50
       }),
       speaker: await this.get('store').createRecord('speaker', {
-        event : eventDetails,
-        user  : this.get('authManager.currentUser')
+        email    : this.get('authManager.currentUser.email'),
+        name     : userName,
+        photoUrl : this.get('authManager.currentUser.avatarUrl'),
+        event    : eventDetails,
+        user     : this.get('authManager.currentUser')
```
Comment (srv-twry) [inline app/routes/public/cfs/new-speaker.js]: Save `this.get('authManager...)` as a local variable and use it.

**Comment by pradeepgangwar** [comment]
@srv-twry @CosmicCoder96 Did the changes. Please review.
