### PR TITLE
fix: Allow organizer to add speaker without email

### LINKED ISSUE #5342: Organizer: Adding speaker without email results in sessions added to "my sessions" from organizer him/herself
If an organizer adds a speaker "without email" the overview page shows the email of the organizer and sessions show up under "my sessions".

Screenshot from 2020-10-21 14-26-34

### PR DESCRIPTION
**Pull request by maze-runnar**
Fixes #5342

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/controllers/events/view/speakers/create.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6389111&bid=20718574)

File: app/controllers/events/view/speakers/create.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ export default class extends Controller {
       }
       const newSpeaker = this.model.speaker;
       if (newSpeaker.isEmailOverridden) {
-        newSpeaker.set('email', this.authManager.currentUser.email);
+        newSpeaker.set('email', 'Not Provided');
```
Comment (iamareebjamal) [inline app/controllers/events/view/speakers/create.js:14]: No, that is wrong data

Comment (maze-runnar) [reply app/controllers/events/view/speakers/create.js:14]: what should be put here?

Comment (iamareebjamal) [reply app/controllers/events/view/speakers/create.js:14]: null

Comment (maze-runnar) [reply app/controllers/events/view/speakers/create.js:14]: When I am setting it to null it throws err -` the server responded with a status of 422 ()`

Comment (iamareebjamal) [reply app/controllers/events/view/speakers/create.js:14]: Server needs to allow null emails in case organizers or admin create the speaker

Comment (maze-runnar) [reply app/controllers/events/view/speakers/create.js:14]: > Server needs to allow null emails in case organizers or admin create the speaker

how to do this :worried:

Comment (iamareebjamal) [reply app/controllers/events/view/speakers/create.js:14]: Need to change speaker schema to allow null and then add a check that email is not null if a not organizer/admin user is submitting/editing the email

Comment (maze-runnar) [reply app/controllers/events/view/speakers/create.js:14]: after allowing null from server and adding null here, it is not being null, It sets to `user email` on writing `newSpeaker.set('email', null); .` But on writing` newSpeaker.set('email', ' any text'); `the email is set to that text.

Comment (maze-runnar) [reply app/controllers/events/view/speakers/create.js:14]: Adding null it is setting it to owner email , but if it's not null then setting to that text
scrnli_10_23_2020_8-44-05 PM

Comment (maze-runnar) [reply app/controllers/events/view/speakers/create.js:14]: this is happening because of this on server side : 
```
elif (
            data.get('is_email_overridden')
            and has_access('is_organizer', event_id=data['event'])
            and not data.get('email')
        ):
            data['email'] = current_user.email
```

Comment (maze-runnar) [reply app/controllers/events/view/speakers/create.js:14]: What to do here?

Comment (iamareebjamal) [reply app/controllers/events/view/speakers/create.js:14]: Will check why this code was added.

**Comment by iamareebjamal** [comment]
@maze-runnar One condition is still left. If a non-organizer user sets email to null, it should be denied

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/controllers/events/view/speakers/create.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=6389111&bid=20718574)

**Review by iamareebjamal — APPROVED** [review]
