### PR TITLE
fix: Showing `Payment Options` for `Donations` 

### LINKED ISSUE #3254: Event Wizard: Show Payment Options when only Donation Tickets are there.
**Describe the bug**

Show Payment Options when only Donation Tickets are there.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Basic Detail Wizard'
2. Click on 'Donation Ticket'
3. See error

**Expected behaviour**

Show Payment Options .

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 24

### PR DESCRIPTION
**Pull request by kushthedude**
Fixes #3254 

#### Short description of what this resolves:

- Showing `Payment Information` in case for `Donation Tickets` too.

#### Screenshot 

image

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kushthedude** [comment]
@niranjan94 @CosmicCoder96 Please REview

File: app/components/forms/wizard/basic-details-step.js [hunk 1]
```diff
@@ -102,8 +102,9 @@ export default Component.extend(FormMixin, EventWizardMixin, {
     return this.data.event.state !== 'published';
   }),
 
-  hasPaidTickets: computed('data.event.tickets.[]', function() {
-    return filter(this.get('data.event.tickets').toArray(), ticket => ticket.get('type') === 'paid').length > 0;
+  hasPaidTickets: computed('data.event.tickets.@each.type', function() {
+
```
Comment (mrsaicharan1) [inline app/components/forms/wizard/basic-details-step.js]: Extra line. Otherwise, Okay.

Comment (kushthedude) [reply app/components/forms/wizard/basic-details-step.js]: @mrsaicharan1
