### PR TITLE
fix: profile picture link to null when removed

### LINKED ISSUE #3360: Removing profile picture doesn't work
**Describe the bug**
The profile picture remains as it is when we click on to confirm delete for the profile picture.
related issue server: https://github.com/fossasia/open-event-server/issues/6171
**To Reproduce**
Steps to reproduce the behaviour:
Try removing a pre-set profile picture.

### PR DESCRIPTION
**Pull request by mrsaicharan1**
profile

Fixes #3360 

#### Short description of what this resolves:
Fixes profile picture removal

#### Changes proposed in this pull request:

- Update avatarUrl to None on the model level when the picture gets deleted.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
I’m attempting a patch request through the frontend to update the avatar_url. This gives me a 415 error but it works when I use an API client. What might be the problem? @cosmiccoder96 @uds5501 @shreyanshdwivedi

File: app/components/widgets/forms/image-upload.js [hunk 1]
```diff
@@ -78,6 +78,23 @@ export default Component.extend({
       if (!this.needsConfirmation) {
         this.set('selectedImage', null);
         this.set('imageUrl', null);
+        let payload = {
```
Comment (CosmicCoder96) [inline app/components/widgets/forms/image-upload.js]: what is this?

user.set(propertyamen, null);
user.save();

Comment (mrsaicharan1) [reply app/components/widgets/forms/image-upload.js]: @CosmicCoder96 I was trying to send a PATCH request to the user API but I believe this is more feasible. Updating it.
