### PR TITLE
fix: Linking Order Invoice Download to server route

### LINKED ISSUE #2925: Link Print Invoice to server route
**Describe the bug**
The `Print Invoice` button must be linked to the the server route which handles invoice serving as a PDF.

**Expected behaviour**
Should not give a screenshot of the window. Serve as a PDF similar to tickets

**Additional context**
Working on this. Waiting for corresponding serve PR to be merged https://github.com/fossasia/open-event-server/pull/5886

### PR DESCRIPTION
**Pull request by mrsaicharan1**
order-invoice

Fixes #2925

#### Short description of what this resolves:

Downloads Order Invoice as PDF(Similar to tickets). Links the button to the server route.

#### Changes proposed in this pull request:

- `downloadFile` for order invoice downloads
-  Created an anchor `href` on-the-fly & supported pdf download
- Linked the order generation server route to frontend button
- Created separate `isLoadingTickets` & `isLoadingInvoice` for loader.
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/controllers/orders/view.js [hunk 1]
```diff
@@ -1,17 +1,28 @@
...
+        .then(res => {
+          const anchor = document.createElement('a');
+          anchor.style.display = 'none';
+          anchor.href = URL.createObjectURL(new Blob([res], { type: 'application/pdf' }));
+          anchor.download = 'Invoice.pdf';
+          anchor.click();
+          this.get('notify').success(this.get('l10n').t('Here is your Order Invoice'));
+        })
+        .catch(e => {
+          console.warn(e);
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: don't disable the print thing for now, put it inside the catch block, if for some reason the above fails, it will be a fallback invoice.

**Comment by mrsaicharan1** [comment]
Yeah I'll take care of that.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 @uds5501 @shreyanshdwivedi I've made the necessary changes. Also, added a GIF for the order invoice downloads.
Also, the `isLoading` seems to be ambiguous because when one action triggers the isLoading, it shows a change in the other button. I segregated them using `isLoadingTickets` and `isLoadingInvoice`.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 @uds5501 @shreyanshdwivedi I've made the necessary changes. Also, added a GIF in the description for the order invoice downloads.
Also, the `isLoading` seems to be ambiguous because when one action triggers the isLoading, it shows a change in the other button. I segregated them using `isLoadingTickets` and `isLoadingInvoice`.

File: app/controllers/orders/view.js [hunk 2]
```diff
@@ -2,21 +2,39 @@ import Controller from '@ember/controller';
...
-      };
-      this.get('printThis').print(selector, options);
+      this.set('isLoading', true);
+      this.get('loader')
+        .downloadFile(`/orders/invoices/${this.model.order.identifier}`)
+        .then(res => {
+          const anchor = document.createElement('a');
+          anchor.style.display = 'none';
+          anchor.href = URL.createObjectURL(new Blob([res], { type: 'application/pdf' }));
+          anchor.download = 'Invoice.pdf';
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: Name it similar to how tickets are named.

File: app/controllers/orders/view.js [hunk 3]
```diff
@@ -2,21 +2,39 @@ import Controller from '@ember/controller';
...
+          anchor.click();
+          this.get('notify').success(this.get('l10n').t('Here is your Order Invoice'));
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: this.notify....this.l10n

File: app/controllers/orders/view.js [hunk 4]
```diff
@@ -2,21 +2,39 @@ import Controller from '@ember/controller';
...
+  actions          : {
     downloadInvoice() {
-      const selector = '.print';
-      const options = {
-        header     : 'Order Invoice',
-        printDelay : 800
-      };
-      this.get('printThis').print(selector, options);
+      this.set('isLoading', true);
+      this.get('loader')
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: this.loader

File: app/controllers/orders/view.js [hunk 5]
```diff
@@ -2,21 +2,39 @@ import Controller from '@ember/controller';
...
+          this.get('notify').success(this.get('l10n').t('Here is your Order Invoice'));
+        })
+        .catch(e => {
+          console.warn(e);
+          const selector = '.print';
+          const options = {
+            header     : 'Order Invoice',
+            printDelay : 800
+          };
+          this.get('printThis').print(selector, options);
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: this.printThis

File: app/controllers/orders/view.js [hunk 6]
```diff
@@ -2,21 +2,39 @@ import Controller from '@ember/controller';
...
-        printDelay : 800
-      };
-      this.get('printThis').print(selector, options);
+      this.set('isLoading', true);
+      this.get('loader')
+        .downloadFile(`/orders/invoices/${this.model.order.identifier}`)
+        .then(res => {
+          const anchor = document.createElement('a');
+          anchor.style.display = 'none';
+          anchor.href = URL.createObjectURL(new Blob([res], { type: 'application/pdf' }));
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: make it firefox compatible, see the PR @pradeepgangwar made to do that.

File: app/controllers/orders/view.js (hunk 2 above)
Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: Done

**Comment by mrsaicharan1** [comment]
@pradeepgangwar @CosmicCoder96 @shreyanshdwivedi Please have a look.
