### PR TITLE
filter added to separate upcoming and past events on user ticket route

### LINKED ISSUE #2257: Tickets of a user are not visible properly
**Describe the bug**
Tickets of upcoming and past events is not visible.
**To Reproduce**
Follow the gif.
eventticket1

**Expected behavior**
Upcoming events and past events should show different results.

**Additional context**
I am working on it.

### PR DESCRIPTION
**Pull request by shubham3211**
#### Short description of what this resolves:
Upcoming and past events are now visible. 

Fixes #2257

### CODE REVIEW

File: app/routes/admin/users/view/tickets/list.js [hunk 1]
```diff
@@ -12,10 +13,75 @@ export default Route.extend(AuthenticatedRouteMixin, {
...
-  model() {
+  async model(params) {
     const userDetails = this.modelFor('admin.users.view');
-    return this.store.findRecord('user', userDetails.id, {
-      include: 'orders,events'
-    });
+    this.set('params', params);
+    let filterOptions = [];
+    if (params.tickets_status === 'upcoming') {
+      filterOptions.push(
```
Comment (CosmicCoder96) [inline app/routes/admin/users/view/tickets/list.js]: don't push. set `filterOptions=...`

File: app/routes/admin/users/view/tickets/list.js [hunk 2]
```diff
@@ -12,10 +13,75 @@ export default Route.extend(AuthenticatedRouteMixin, {
...
+                  op   : 'eq',
+                  val  : 'placed'
+                }
+              ]
+            }
+          ]
+        }
+      );
+    } else if (params.tickets_status === 'past') {
+      filterOptions.push(
```
Comment (CosmicCoder96) [inline app/routes/admin/users/view/tickets/list.js]: don't push. set filterOptions=...

**Comment by shubham3211** [comment]
@CosmicCoder96 done :+1:
