### PR TITLE
fix: resolve whack-a-mole behavior of time/date pickers & add validations to date-time

### LINKED ISSUE #2077: Not able to set event start time
**Describe the bug**

When creating a new event and filling up start time, the time doesn't set properly. For example a time of 09:35 is not being set instead 00:35 is getting set.
**To Reproduce**
1. Go to event creation page
2. set start time to hours and minutes
3. you will see hours get reset

**Expected behavior**

The time should be set properly
**Screenshots**

ezgif com-video-to-gif

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I would like to work on this issue

### LINKED ISSUE #2366: Event end time error
**Describe the bug**

Not able to set end time prior to start time

**To Reproduce**

1. Go to 'http://127.0.0.1:4200/create'
2. Set a start time and date
3. Change the end date.
4. Try to set end time before start time.
5. See error

**Expected behavior**

User should be able to set end time as per his flexibility.

**Screenshots**

Screenshot 2019-03-23 at 12 52 35 AM

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 72.0.36

**Additional Context:**

Would like to work on it.

### LINKED ISSUE #2972: Call for Speakers does not store text and dates correctly
Creating a call for speakers does not work properly. The text and the dates are not stored correctly. Trying several times will finally store the correct value, but it does not always work right away.

Screenshot from 2019-05-20 14-44-32

### LINKED ISSUE #3020: endsAtDate attribute defined in Event Models is buggy
**Describe the bug**

My event start and end date were June 27,2019 and June 30,2019 respectively
Data stored in startsAtDate and endsAtDate were 6/27/2019 and 07/01/2019 respectively

**To Reproduce**

Steps to reproduce the behaviour:

Check the `event.endsAtDate` it would give a result greater than one day .

**Expected behaviour**

Find the cause of the bug and Fix it.

### LINKED ISSUE #3382: Discount codes experiencing similar date-time-picker bug as event wizard

### PR DESCRIPTION
**Pull request by CosmicCoder96**
Fixes #3020
Fixes #3382 
Fixes #2077
Fixes #2366 
Fixes #2972

### CODE REVIEW

**Comment by kushthedude** [comment]
Also #2366

File: app/components/widgets/forms/time-picker.js [hunk 1]
```diff
@@ -28,16 +28,23 @@ export default Component.extend({
...
-        defaultOptions.startCalendar = this.$().closest('.fields').find('.ui.calendar.time.picker');
-        break;
-    }
+    // switch (this.rangePosition) {
+    //   case 'start':
+    //     defaultOptions.endCalendar = this.$().closest('.fields').find('.ui.calendar.time.picker');
+    //     break;
+    //   case 'end':
+    //     defaultOptions.startCalendar = this.$().closest('.fields').find('.ui.calendar.time.picker');
+    //     break;
```
Comment (kushthedude) [inline app/components/widgets/forms/time-picker.js]: @CosmicCoder96 Remove the comments, Else tested every widget works well 🎉

**Comment by kushthedude** [comment]
> * time

Not reproducible on my local, Any specific steps?

File: app/components/widgets/forms/time-picker.js (hunk 1 above)
Comment (CosmicCoder96) [reply app/components/widgets/forms/time-picker.js]: leaving these comments.. because someday we might want the time validation to change it's values according to its start counterpart, removed it for now because jquery ui calendar does not compare time while matching fields.

**Comment by shreyanshdwivedi** [comment]
@kushthedude just edit the time and date while creating the discount code. You'll see it
@uds5501 can you reproduce it?

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi @kushthedude The behavior shreyansh noted might be for some discount codes who previously had a null value. I can't recreate it while creating new ones or existing valid ones. Though I did was able to recreate that when I forced a false value for the start time inside DB.

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi 
> just edit the time and date while creating the discount code.
you mean edit using backspace?

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 there was a weird behavior. When I followed links to create discount code and edited it, I was able to reproduce it.
But once I refreshed the URL directly, I couldn't. I'm still getting when I create it using `Create Dicount Code` button and then editing the start date to a greater value than end date and then updating start time

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi Caught the source, thanks for the review 👍 fixed now.

File: app/routes/events/view/tickets/discount-codes/create.js [hunk 2]
```diff
@@ -33,7 +33,6 @@ export default Route.extend({
     });
     let currentDiscountCode = model.discountCode;
     let event = this.modelFor('events.view');
-    currentDiscountCode.set('validFrom', moment().toISOString());
```
Comment (CosmicCoder96) [inline app/routes/events/view/tickets/discount-codes/create.js]: this was the problem 😈 
@shreyanshdwivedi @kushthedude
