### PR TITLE
fix: No error shown when image upload fails

### LINKED ISSUE #4222: No error shown when image upload fails
No error is shown to the user when image upload fails and it also shows new image instead of old image, which is really confusing

### PR DESCRIPTION
**Pull request by akash2408**
Fixes #4222

#### Short description of what this resolves:
ezgif com-gif-maker (3)

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/components/widgets/forms/image-upload.js [hunk 1]
```diff
@@ -41,8 +41,9 @@ export default class ImageUpload extends Component {
       })
       .catch(e => {
         console.error('Error while uploading and setting image URL', e);
+        this.notify.error(this.l10n.t('Error while uploading and setting image URL'));
         this.set('uploadingImage', false);
-        this.set('errorMessage', this.i18n.t('An unexpected error has occurred.'));
+        this.set('selectedImage', null);
```
Comment (iamareebjamal) [inline app/components/widgets/forms/image-upload.js:46]: Why

**Comment by akash2408** [comment]
as after showing the error image is till showing there and it could be
confusing that image is uploaded or not this will remove the image

**Review by iamareebjamal — DISMISSED** [review]

File: app/components/widgets/forms/image-upload.js [hunk 2]
```diff
@@ -41,8 +41,9 @@ export default class ImageUpload extends Component {
       })
       .catch(e => {
         console.error('Error while uploading and setting image URL', e);
+        this.notify.error(this.l10n.t('Error while uploading and setting image URL'));
```
Comment (iamareebjamal) [inline app/components/widgets/forms/image-upload.js:44]:
```suggestion
        this.notify.error(this.l10n.t('An unexpected error has occurred.'));
```
