### PR TITLE
Ticket refactoring: Download Tickets Request Change

### LINKED ISSUE #2652: Download Tickets Button should send JWT Auth Headers
**Describe the bug**
Related  Discussion: https://github.com/fossasia/open-event-server/pull/5790
Currently, the tickets are prone to a vulnerability issue where any person with the tickets link is able to access it. Thereby, we're refactoring the ticket flow to prevent this. We have implemented the access-control check on the server. In addition, the `Download Tickets` button must route to the ticket-url and  send JWT authorization headers so that the route can handle the request properly.
 
**Expected behaviour**
Needs to send JWT auth headers along with the request.

**Additional context**
Working on it.

### PR DESCRIPTION
**Pull request by mrsaicharan1**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
- using loader service to load the tickets route to download tickets

#### Changes proposed in this pull request:

Fixes #2652

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Any idea about how JWT headers are sent to the server? Do they need to be manually attached as headers?

File: app/controllers/orders/view.js [hunk 1]
```diff
@@ -4,6 +4,11 @@ export default Controller.extend({
   actions: {
     downloadInvoice() {
       window.print();
+    },
+    downloadTickets() {
+      return this.get('ajax').request(`${this.get('model.order.ticketsPdfUrl')}`, {
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: why are you using this? why not the loader service. Headers are attached automatically attached to this.

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: There was an unexpected error when I used the loader service. 
`    downloadTickets() {
      this.get('loader')
        .post(`${this.get('model.order.ticketsPdfUrl')}`)
        .catch(() => {
          this.get('notify').error(this.get('l10n').t('An unexpected Error occurred'));
        });
    }`

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: There was an unexpected error when I used it. Maybe because the ticket url was stored in its full form? Will see again.

Comment (CosmicCoder96) [reply app/controllers/orders/view.js]: The existing code has used the loader service at 100+ instances in the app, and what you did nowhere. There is a strong reason for that. Read what the service does.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 While using the loader service, I've passed the config as `{ 'withoutPrefix': true }` to disable the prefix, but I think the host still gets attached, which we don't want(ticketPdfUrl is stored along with the namespace and host beforehand). Any workaround for this?

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 think about this: what I am trying to ask on server is — that
you make an end point with dynamic parameters which returns the ticket of
the order corresponding to the value passed for those parameters. The
ticketUrl field will become obsolete once an end point is there for an
order. It will always be the same end point url along with dynamic
parameters. Like /v1/<order-identifier>/tickets.
You just make a request to it like you do for translations. Why would we be
using the ticketUrl field then?

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 That was my first approach to the issue. But the problem here is, the order-identifier stored in the Order Model and the order-identifier generated in the `ticketUrl` (by `uuid`)is different.
But yeah, I got your point. I'll try to make the stored identifier in the Order Model the dynamic parameter in the URL. This is what you meant right?

**Comment by CosmicCoder96** [comment]
Yup

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Updated the PR.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Do we need anything else here?

File: app/controllers/orders/view.js [hunk 2]
```diff
@@ -1,9 +1,26 @@
...
+  isLoading: false,
+
   actions: {
     downloadInvoice() {
       window.print();
+    },
+    downloadTickets() {
+      this.set('isLoading', true);
+      this.get('loader')
+        .load(`/tickets/${this.get('model.order.identifier')}`, { withoutPrefix: true })
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: `{ withoutPrefix: true }` 
Why?
Also, have you tested this locally?

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: Yup. It works locally. I've actually routed the tickets to `/tickets/<order_identifier>`. Do you want me to route it to `v1/tickets/<order_identifier>`?

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: Wait did you mean the ticket routing or `isLoading`?

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: Wait, did you mean `isLoading` or the ticket routing? I actually have a problem loading the PDF in the browser. For some reason, it loads for a very long time and it throws an exception. But half of the times, the PDF is loaded. Can you check this?

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 I'm able to get a 200 on accessing the route `tickets/44ea48b7-d9de-4b7b-ac8f-a10fecd747d7` but it doesn't download the tickets/route the HTML page containing the PDF. Also, I've submitted a file-path-fix PR. Please consider that.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 @uds5501 @shreyanshdwivedi I'm able to get a 200 on clicking the `Download Tickets` button which accesses the route `tickets/44ea48b7-d9de-4b7b-ac8f-a10fecd747d7`. But, it doesn't download the tickets/route to the HTML page containing the PDF. Could you confirm this?

**Comment by mrsaicharan1** [comment]
> @mrsaicharan1 Is this endpoint for tickets returning a PDF file directly, like for the translation downloads? If yes, then why are you not using the downloadFile service. And if not, then I will debug it locally, confirm firtst.
I presumed that we had to show the pdf on another page so I didn't use it. But yeah, I think downloading it would be a better option. WIll be using the `downloadFile` service.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 The downloadFile service is automatically attaching the headers, right? I'm stll getting the following error
 `{
  "description": "Request does not contain an access token", 
  "error": "Authorization Required", 
  "status_code": 401
}`. What's happening here?

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 Is the server expecting a post request or get?

**Comment by mrsaicharan1** [comment]
It's expecting a GET request

File: app/controllers/orders/view.js [hunk 3]
```diff
@@ -1,9 +1,26 @@
...
+  isLoading: false,
+
   actions: {
     downloadInvoice() {
       window.print();
+    },
+    downloadTickets() {
+      this.set('isLoading', true);
+      this.get('loader')
+        .downloadFile(`/tickets/${this.get('model.order.identifier')}`, null, { withoutPrefix: true })
```
Comment (CosmicCoder96) [inline app/controllers/orders/view.js]: Why is your URL without prefix?

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: The server-side endpoint is without the prefix.

File: app/controllers/orders/view.js (hunk 2 above)
Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: @CosmicCoder96

File: app/controllers/orders/view.js (hunk 3 above)
Comment (CosmicCoder96) [reply app/controllers/orders/view.js]: Why?

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: @CosmicCoder96 There's nothing specific actually.  I've routed the tickets to `/tickets/<order_identifier>`. Do you want me to route it to `/v1/tickets/<order_identifier>` on the server side?

Comment (CosmicCoder96) [reply app/controllers/orders/view.js]: Yes, why would we change the namespace for just one endpoint?

Comment (CosmicCoder96) [reply app/controllers/orders/view.js]: First change it on the server, then I will debug it.

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: Yeah. I'll send a PR asap.

Comment (CosmicCoder96) [reply app/controllers/orders/view.js]: @mrsaicharan1 can you post the headers of the request generated by downloadFile helper?

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: `ERROR:flask_jwt:Authorization Required. Request does not contain an access token`. the headers show nothing when I print them on to the console.

Comment (CosmicCoder96) [reply app/controllers/orders/view.js]: I meant on the Frontend (through chrome dev console or something similar) @mrsaicharan1

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: `Host: 127.0.0.1:5000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:4200/orders/44ea48b7-d9de-4b7b-ac8f-a10fecd747d7/view
Origin: http://127.0.0.1:4200
Connection: keep-alive`

Comment (mrsaicharan1) [reply app/controllers/orders/view.js]: `Host: 127.0.0.1:5000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:4200/orders/44ea48b7-d9de-4b7b-ac8f-a10fecd747d7/view
Origin: http://127.0.0.1:4200
Connection: keep-alive``Host: 127.0.0.1:5000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:4200/orders/44ea48b7-d9de-4b7b-ac8f-a10fecd747d7/view
Origin: http://127.0.0.1:4200
Connection: keep-alive`

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 Can you resolve conflicts, I have found a fix I will push it after this is merged.  Will you be able to do it today?

**Comment by mrsaicharan1** [comment]
Yeah, will push it within a few hours(IST)

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Fixed the conflicts.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Can you push the fix for

> @mrsaicharan1 Can you resolve conflicts, I have found a fix I will push it after this is merged. Will you be able to do it today?

Can you do this asap please? There is an issue with new users wanting to download they tickets.

**Comment by CosmicCoder96** [comment]
The users are not able to place order as of now. Downloading tickets comes
later. There is an object creation error for new users trying to register
on the go. That needs to be resolved first. After that I’ll fix this too.

**Comment by CosmicCoder96** [comment]
I had a fix which solved the tickets download issue, but for some reason it
doesn’t work on production. The server returns the entire response in the
OPTIONS request. It should have returned it only on the GET request. As a
result of which two files get downloaded and chrome blocks them as an
attempt to download multiple files.
