### PR TITLE
fix: Only show country dropdown without autocomplete

### LINKED ISSUE #5438: Country Field in Billing Information: Only show country dropdown, do not automatically fill in random info - only country
* [ ] Fix Country dropdown. It automatically shows data saved in the browsers instead of using the dropdown country option

Expected: Only show country options. Do not show other possible data saved in the browser.

Screenshot from 2020-07-30 10-25-29

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5438 

#### Short description of what this resolves:
The problem was that all the countries which are defined in demography were showing. Now showing only payment countries

#### Changes proposed in this pull request:

- Instead of showing all countries showing payment countries.

#### Before
Screenshot from 2020-11-16 04-38-46
---
#### After
Screenshot from 2020-11-16 04-37-54

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@iamareebjamal Please see the changes I have made.

File: app/components/forms/user-payment-info-form.js [hunk 1]
```diff
@@ -96,6 +97,10 @@ export default class UserPaymentInfoForm extends Component.extend(FormMixin) {
     return orderBy(countries, 'name');
   }
 
+  get paymentCountries() {
+    return orderBy(filter(countries, country => paymentCountries.includes(country.code)), 'name');
```
Comment (iamareebjamal) [inline app/components/forms/user-payment-info-form.js:101]: Use js native filter

**Comment by iamareebjamal** [comment]
This does not solve the issue. Read the issue again

**Comment by daretobedifferent18** [comment]
@iamareebjamal the issue what I think is that while for eg searching for India they are lots of countries coming, so do I have to not show other unnecessary countries in drop down o and not change anything with no of countries that are already there in it.

Bcz like for eg in wizard step 1 during choosing country there are only 44 countries in the dropdown but here there are 200+ so if we search India for eg here it will be showing more no. of countries bcz here in UiDropwdown we are using ```fullTextSearch={{true}}```
and what I found is this 
Screenshot from 2020-11-16 04-04-00
so either the best option could be instead of using false use true and not changes the list of countries

**Comment by iamareebjamal** [comment]
That's not the issue. Please read it again, carefully. See the closed PR and the PR I have mentioned there

**Comment by daretobedifferent18** [comment]
> That's not the issue. Please read it again, carefully. See the linked PR and the PR I have mentioned there

@iamareebjamal I understood the issue, pls clear me out do I have to  turn ```autocomplete='off'``` for entire form or just for country dowpdown bcz as you mentioned in tax-info-modal ```autocomplete='off'``` is for entire form.

**Comment by iamareebjamal** [comment]
The issue mentions in the title - only country

And I have mentioned it in the linked PR as well

**Comment by daretobedifferent18** [comment]
@iamareebjamal Please see the changes made.

File: app/templates/components/forms/user-payment-info-form.hbs [hunk 2]
```diff
@@ -65,11 +65,12 @@
         @type="hidden"
         @autocomplete="no"
```
Comment (iamareebjamal) [inline app/templates/components/forms/user-payment-info-form.hbs:66]: autocomplete is already present here

File: app/components/forms/user-payment-info-form.js [hunk 3]
```diff
@@ -96,6 +97,10 @@ export default class UserPaymentInfoForm extends Component.extend(FormMixin) {
     return orderBy(countries, 'name');
   }
 
+  get paymentCountries() {
```
Comment (iamareebjamal) [inline app/components/forms/user-payment-info-form.js:100]: Revert

File: app/templates/components/forms/user-payment-info-form.hbs (hunk 2 above)
Comment (iamareebjamal) [reply app/templates/components/forms/user-payment-info-form.hbs:66]: Still here

**Comment by iamareebjamal** [comment]
Still getting autocomplete

**Comment by daretobedifferent18** [comment]
> Still getting autocomplete

@iamareebjamal can u pls share the screenshot

**Comment by iamareebjamal** [comment]
image

**Comment by daretobedifferent18** [comment]
@iamareebjamal as I see u r using chrome browser, but I was using Mozilla Firefox and now I have fully tried on both the browsers doing different tests and what I found is that on Mozilla it is working correct but on chrome autocomplete='on'/'off' is ignored and even by chrome officials they also said that they ignore autocomplete='on'/'off'.
And as u mentioned to look at tax-info-modal, there also it is working fine on Mozilla but in chrome browser there also the same problem is coming.

So what I think is that unless there is not update of fix from chrome it will be like this only.
Please let me know if its is working fine on Mozilla Firefox

**Comment by iamareebjamal** [comment]
I only merged the tax info PR after verifying that it worked on chrome

**Comment by daretobedifferent18** [comment]
But is still shows
Screenshot from 2020-11-17 18-25-15

**Comment by iamareebjamal** [comment]
Then it must be someplace else. Use autocomplete="disable" and extract country dropdown to a separate component and replace from everywhere

**Comment by daretobedifferent18** [comment]
> Then it must be someplace else. Use autocomplete="disable" and extract country dropdown to a separate component and replace from everywhere

u r saying make a new component and put all the code for country dropdown there?

**Comment by daretobedifferent18** [comment]
@iamareebjamal  I found the solution to it, we won't be requiring separate component to it.

File: app/templates/components/modals/tax-info-modal.hbs [hunk 4]
```diff
@@ -19,7 +19,7 @@
           {{/each}}
         </div>
       </UiDropdown>
-    </div>
+    </form>
```
Comment (iamareebjamal) [inline app/templates/components/modals/tax-info-modal.hbs:22]: Repeated. Put in another component

Comment (daretobedifferent18) [reply app/templates/components/modals/tax-info-modal.hbs:22]: ok and is it working now?

Comment (iamareebjamal) [reply app/templates/components/modals/tax-info-modal.hbs:22]: autocomplete="disable" was working as well. This is a workaround. Now it is not showing error when country is required

Comment (daretobedifferent18) [reply app/templates/components/modals/tax-info-modal.hbs:22]: inside input tag? ```autocomplete="disable"```

Comment (daretobedifferent18) [reply app/templates/components/modals/tax-info-modal.hbs:22]: @iamareebjamal ```autocomplete="disable"``` is not working when I am using it on input tag

Comment (iamareebjamal) [reply app/templates/components/modals/tax-info-modal.hbs:22]: Then just move this in a component

**Comment by daretobedifferent18** [comment]
@iamareebjamal please see the changes made and now everywhere is working correct

File: app/templates/components/forms/admin/settings/billing.hbs [hunk 5]
```diff
@@ -45,22 +45,10 @@
...
-          <div class="item" data-value="{{country.name}}">
-            <i class="{{lowercase country.code}} flag"></i>
-            {{country.name}}
-          </div>
-        {{/each}}
-      </div>
-    </UiDropdown>
-  </form>
+  <CountryDropdown
+    @options={{this.countries}}
```
Comment (iamareebjamal) [inline app/templates/components/forms/admin/settings/billing.hbs:50]: Should automatically use countries instead of passing here

Comment (daretobedifferent18) [reply app/templates/components/forms/admin/settings/billing.hbs:50]: @iamareebjamal but in someplaces they are using countries and in someplace payment countries?

Comment (iamareebjamal) [reply app/templates/components/forms/admin/settings/billing.hbs:50]: If you set prop use that, otherwise all countries

Comment (daretobedifferent18) [reply app/templates/components/forms/admin/settings/billing.hbs:50]: @iamareebjamal What I think would be better is passing ```@paymentCountries={{true}}``` if paymentCountries are using as an option otherwise byDefault countries and not passing countries or paymentCountries at all, using them automatically

Comment (iamareebjamal) [reply app/templates/components/forms/admin/settings/billing.hbs:50]: OK

File: app/templates/components/country-dropdown.hbs [hunk 6]
```diff
@@ -12,12 +12,21 @@
...
+            </div>
+        {{/each}}
+    {{else}}
+        {{#each this.countries as |country|}}
+            <div class="item" data-value="{{country.name}}">
+            <i class="{{lowercase country.code}} flag"></i>
+            {{country.name}}
+            </div>
+        {{/each}}
+    {{/if}}
```
Comment (iamareebjamal) [inline app/templates/components/country-dropdown.hbs:29]: Duplication

Comment (daretobedifferent18) [reply app/templates/components/country-dropdown.hbs]: Done

File: app/components/country-dropdown.ts [hunk 7]
```diff
@@ -0,0 +1,14 @@
+import Component from '@glimmer/component';
+import { orderBy, filter } from 'lodash-es';
+import { paymentCountries } from 'open-event-frontend/utils/dictionary/payment';
+import { countries } from 'open-event-frontend/utils/dictionary/demography';
+
+export default class CountryDropdown extends Component {
+  get countries() { // eslint-disable-line @typescript-eslint/explicit-module-boundary-types
```
Comment (iamareebjamal) [inline app/components/country-dropdown.ts:7]: Remove the eslint rule

File: app/templates/components/country-dropdown.hbs [hunk 8]
```diff
@@ -0,0 +1,23 @@
...
+    @selected={{@val}}
+    @forceSelection={{false}}
+    @fullTextSearch={{true}}>
+    <Input
+    @type="hidden"
+    @autocomplete="no"
+    @value={{@val}} />
+    <i class="dropdown icon"></i>
+    <div class="default text">{{t 'Select country'}}</div>
+    <div class="menu">
```
Comment (iamareebjamal) [inline app/templates/components/country-dropdown.hbs:14]: Indentation is wrong

File: app/templates/components/forms/wizard/basic-details-step.hbs [hunk 9]
```diff
@@ -315,30 +315,11 @@
...
-                  {{paymentCountry.name}}
-                </div>
-              {{/each}}
-            </div>
-          </UiDropdown>
-        </div>
+      <CountryDropdown
+        @required={{true}}
+        @paymentCountries={{true}}
+        @placeholder={{'Select country'}}
```
Comment (iamareebjamal) [inline app/templates/components/forms/wizard/basic-details-step.hbs:321]: t missing

Comment (daretobedifferent18) [reply app/templates/components/forms/wizard/basic-details-step.hbs:321]: used in countryDropdown only

Comment (iamareebjamal) [reply app/templates/components/forms/wizard/basic-details-step.hbs:321]: It has to be used with static strings, not dynamic

Comment (daretobedifferent18) [reply app/templates/components/forms/wizard/basic-details-step.hbs:321]: so I should like this ??
```handlebars
<label class={{if @required 'required'}}>{{@placeholder}}</label>
```
and 
```handlebars
@placeholder={{t 'Select Country'}}
```

File: app/components/country-dropdown.ts [hunk 10]
```diff
@@ -0,0 +1,14 @@
+import Component from '@glimmer/component';
+import { orderBy, filter } from 'lodash-es';
+import { paymentCountries } from 'open-event-frontend/utils/dictionary/payment';
+import { countries } from 'open-event-frontend/utils/dictionary/demography';
+
+export default class CountryDropdown extends Component {
+  get countries() {
```
Comment (iamareebjamal) [inline app/components/country-dropdown.ts:7]:
```suggestion
  get countries(): { name: string, code: string }[] {
```

File: app/components/country-dropdown.ts [hunk 11]
```diff
@@ -0,0 +1,14 @@
...
+    return orderBy(countries, 'name');
+  }
+
+  get paymentCountries() {
```
Comment (iamareebjamal) [inline app/components/country-dropdown.ts:11]:
```suggestion
  get paymentCountries(): { name: string, code: string }[] {
```
