### PR TITLE
fix: Remove serialization of computed statistics

### LINKED ISSUE #3890: Wizard Step 1: Editing Description results in Unexpected Error
When the user tries to edit the "Description" area in step 1 of the wizard an "Unexpected Error" appears. If the user refreshes the wizard and copy/pastes the info it works, but initially it always shows the error.

Screenshot from 2020-01-29 10-46-58

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #3890

Related: https://github.com/fossasia/open-event-server/issues/6776

### CODE REVIEW

File: app/models/event.js [hunk 1]
```diff
@@ -111,7 +111,7 @@ export default ModelBase.extend(CustomPrimaryKeyMixin, {
   invoice                : hasMany('event-invoice'),
   speakersCall           : belongsTo('speakers-call'),
   stripeAuthorization    : belongsTo('stripe-authorization'),
-  eventStatisticsGeneral : belongsTo('event-statistics-general'),
+  generalStatistics : belongsTo('event-statistics-general'),
```
Comment (niranjan94) [inline app/models/event.js]: Codacy Issue found: [Missing space after key 'generalStatistics'.](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929773)

**Comment by niranjan94** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fossasia/open-event-frontend/pullRequest?prid=4929773&bid=16306831)
