### PR TITLE
fix: Show pending orders in my tickets section

### LINKED ISSUE #3001: Pending and initialising orders don't show up in open orders of my-tickets
Only placed orders are visible.

### PR DESCRIPTION
**Pull request by CosmicCoder96**
Fixes #3001 

#### Short description of what this resolves:
Adds pending and initializing orders to open orders tab of my-tickets route

### CODE REVIEW

File: app/routes/my-tickets/upcoming/list.js [hunk 1]
```diff
@@ -56,11 +56,23 @@ export default Route.extend({
...
-            {
-              name : 'status',
-              op   : 'eq',
-              val  : 'placed'
-            },
+            { or: [
+              {
+                name : 'status',
+                op   : 'eq',
+                val  : 'placed'
```
Comment (shreyanshdwivedi) [inline app/routes/my-tickets/upcoming/list.js]: @CosmicCoder96 should we show `placed` orders in `Completed Orders` as we cannot pay for it via our portal? Or we can have a `Placed Orders` tab for it. Your views?

Comment (CosmicCoder96) [reply app/routes/my-tickets/upcoming/list.js]: @shreyanshdwivedi Let's move it to completed.
