### PR TITLE
fix: minOrder-maxOrder & minPrice-maxPrice validation in basic-details-step

### LINKED ISSUE #3521: Frontend check for min order and max order in ticketing system
**Describe the bug**
Their should be a frontend side check of minimum order and maximum order in ticketing system while creating any event

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create an event'
2. fill the info
3. Add a ticketing system 
4. Minimum order value has no check of less than 1 and max order doesn't has check of greater than min order

**Expected behaviour**
it should be corrected

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [ safari]

**Additional context**
I am taking this issue

### PR DESCRIPTION
**Pull request by snitin315**
Fixes #3521 

#### Short description of what this resolves:

Added minOrder-maxOrder & minPrice-maxPrice validation in ticket-input.
**(Server checks are already present.)**

#### Changes proposed in this pull request:
Screenshot from 2020-01-25 22-36-23

Screenshot from 2020-01-25 22-37-11

### CODE REVIEW

File: app/components/forms/wizard/basic-details-step.js [hunk 1]
```diff
@@ -128,6 +128,15 @@ export default Component.extend(FormMixin, EventWizardMixin, {
 
   // TODO: Removing the Event Time Validations due to the weird and buggy behaviour. Will be restored once a perfect solution is found. Please check issue: https://github.com/fossasia/open-event-frontend/issues/3667
   getValidationRules() {
+    window.$.fn.form.settings.rules.checkMaxMinPrice = () => {
+      return this.$('.ui.form').form('get value', 'min_price') <= this.$('.ui.form').form('get value', 'max_price');
+    };
+    window.$.fn.form.settings.rules.checkMaxMinOrder = () => {
+      return this.$('.ui.form').form('get value', 'ticket_min_order') <= this.$('.ui.form').form('get value', 'ticket_max_order');
+    };
+    window.$.fn.form.settings.rules.checkMaxTotal = () => {
```
Comment (kushthedude) [inline app/components/forms/wizard/basic-details-step.js]: Check if server validations are present for them or not.
 If not then first server validations need to be added then the FE

Comment (snitin315) [reply app/components/forms/wizard/basic-details-step.js]: @kushthedude Yes the server validation are already added.

Comment (snitin315) [reply app/components/forms/wizard/basic-details-step.js]: Screenshot from 2020-01-29 15-56-54

Screenshot from 2020-01-29 15-57-14
