### PR TITLE
fix: Added quantity, min/max price validations & fixed donations bugs

### LINKED ISSUE #3184: Order Quantity for Donation Tickets Missing and Donation Ticket of 0 USD should not be possible / minimum amount not working
1. Order Quantity for Donation Tickets is missing. Expected: Donation tickets could also be limited if e.g. the venue has limited space.

Screenshot from 2019-06-24 18-17-52

2. Donation ticket of 0 USD is possible even though minimum amount of 1 USD is defined in the ticket settings. In any case 0 should not be possible for a donation ticket ever.

Screenshot from 2019-06-24 18-15-16

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #3184 

**When organizer tries to add tickets worth of 0 value**
Screenshot 2019-06-24 at 11 45 37 PM
_________________

**Min max validation checks**
Screenshot 2019-07-02 at 9 00 44 AM
________________

**When the ticket buyer tries to add zero valued donation tickets**
Screenshot 2019-06-26 at 7 04 39 AM

#### Short description of what this resolves:
Does not allow donation tickets worth of 0 value to be purchased & adds quantity support

#### Changes proposed in this pull request:

- Added quantity support for donation tickets
- Removed duplicate code segment to prevent price repitition
- Added check to allow donations to be limited to a pre-specified price range (`minPrice` and `maxPrice`)
- Fixed the price update bug by adding price to watchable properties

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
Lost the changes due to a force push on this https://github.com/fossasia/open-event-frontend/pull/3194. Will keep it in mind to use it only when needed.

**Comment by mrsaicharan1** [comment]
https://github.com/fossasia/open-event-frontend/pull/3194#pullrequestreview-255407976 I've changed the validation according by looping through `this.tickets` instead of storing it in a variable.

**Comment by mrsaicharan1** [comment]
Lost the changes due to a force push on the https://github.com/fossasia/open-event-frontend/pull/3194. Will keep in mind to use it only when needed. Restored here using `reflog`

**Comment by mrsaicharan1** [comment]
@niranjan94 I've used `this.tickets` to loop through the tickets to avoid any redundant variable storages. https://github.com/fossasia/open-event-frontend/pull/3194#discussion_r298314641

File: app/components/forms/wizard/basic-details-step.js [hunk 1]
```diff
@@ -114,13 +114,26 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+  donationTickets: computed.filterBy('tickets', 'type', 'donation'),
+
   didInsertElement() {
     if (!this.isCreate && this.get('data.event.copyright') && !this.get('data.event.copyright.content')) {
       this.set('data.event.copyright', this.store.createRecord('event-copyright'));
     }
   },
 
   getValidationRules() {
+    window.$.fn.form.settings.rules.checkMaxMin = () => {
```
Comment (niranjan94) [inline app/components/forms/wizard/basic-details-step.js]: This should check for a single ticket. Not all tickets.

**Comment by mrsaicharan1** [comment]
@niranjan94 @CosmicCoder96 I read up the docs & the appropriate form validations. Is this fine? It's working locally.

File: app/components/forms/wizard/basic-details-step.js (hunk 1 above)
Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: Yes, for a single donation ticket, wouldn't want to check the validations of all other donation tickets

File: app/components/public/ticket-list.js [hunk 2]
```diff
@@ -190,6 +206,19 @@ export default Component.extend(FormMixin, {
...
+        },
+        price: {
+          identifier : 'price',
+          rules      : [
+            {
+              type   : 'number',
+              prompt : this.l10n.t('Invalid number')
+            },
+            {
+              type   : 'integer[1..]',
```
Comment (kushthedude) [inline app/components/public/ticket-list.js]: Change the minimum value validation to min price,

File: app/components/forms/wizard/basic-details-step.js [hunk 3]
```diff
@@ -269,6 +283,44 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+              type   : 'empty',
+              prompt : this.l10n.t('Minimum price for donation tickets required')
+            },
+            {
+              type   : 'number',
+              prompt : this.l10n.t('Invalid number')
+            },
+            {
+              type   : 'checkZero',
+              prompt : this.l10n.t('Ticket Price should be greater than zero')
```
Comment (kushthedude) [inline app/components/forms/wizard/basic-details-step.js]: For this, you may just use a check for type `integer[1..n]`, No need for two tests.

File: app/components/public/ticket-list.js (hunk 2 above)
Comment (mrsaicharan1) [reply app/components/public/ticket-list.js]: @kushthedude Couldn't get you. Are you referring to this line?

Comment (kushthedude) [reply app/components/public/ticket-list.js]: Here the validation you are using is just to check for zero price, Change this to Minimum Value of Donation Ticket Price set up?

Comment (mrsaicharan1) [reply app/components/public/ticket-list.js]: @kushthedude I've added the logic for minimum price here `app/components/public/ticket-list.js`. We needed the validation there for disabling the order button. :)

Comment (kushthedude) [reply app/components/public/ticket-list.js]: How will the random buyer know, What's the minimum amount to enable the order button? That's why I asked you to include `Validation for Min Value`, Or else you can write a minimum price in the subscript of the Donation Ticket, Whichever method suits you well.


> @kushthedude I've added the logic for minimum price here `app/components/public/ticket-list.js`. We needed the validation there for disabling the order button. :)

**Comment by mrsaicharan1** [comment]
Yeah I had this question. We could have an icon popup specifying it.

File: app/components/forms/wizard/basic-details-step.js [hunk 4]
```diff
@@ -121,6 +121,13 @@ export default Component.extend(FormMixin, EventWizardMixin, {
   },
 
   getValidationRules() {
+    window.$.fn.form.settings.rules.checkMaxMin = () => {
+      let returnValue = false;
+      if (this.$('.ui.form').form('get value', 'min_price')[0] < this.$('.ui.form').form('get value', 'max_price')[0]) {
```
Comment (niranjan94) [inline app/components/forms/wizard/basic-details-step.js]: @mrsaicharan1 could you explain the reasoning behind this ?

Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: This is just to validate that the min_price is lesser than max_price. `this.$('.ui.form').form('get value', 'min_price')` gave me access to the array object where the first element was the value.

**Comment by kushthedude** [comment]
> Yeah I had this question. We could have an icon popup specifying it.

Whatever looks well can be done 👍

**Comment by mrsaicharan1** [comment]
Screenshot 2019-06-29 at 8 05 51 AM
Here's the helper info

**Comment by mrsaicharan1** [comment]
@niranjan94 @CosmicCoder96 There was a bug related to the donation price. The subtotal was getting updated but the total wasn't as the price of the donation is now variable. I fixed that by adding the ticket price to the watchable property
**Before**
Screenshot 2019-06-29 at 8 16 45 AM

**After
Screenshot 2019-06-29 at 8 19 07 AM
**

File: app/components/forms/wizard/basic-details-step.js [hunk 5]
```diff
@@ -269,6 +276,44 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+              prompt : this.l10n.t('Minimum price for donation tickets required')
+            },
+            {
+              type   : 'number',
+              prompt : this.l10n.t('Invalid number')
+            },
+            {
+              type   : 'integer[1..]',
+              prompt : this.l10n.t('Ticket price needs to be greater than zero')
+            },
```
Comment (kushthedude) [inline app/components/forms/wizard/basic-details-step.js]:
```js
{
              type   : 'number',
              prompt : this.l10n.t('Invalid number')
            },
            {
              type   : 'integer[1..]',
              prompt : this.l10n.t('Ticket price needs to be greater than zero')
            },
```
No need for two validations here too , Integer can be only used

File: app/components/forms/wizard/basic-details-step.js [hunk 6]
```diff
@@ -269,6 +276,44 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+          identifier : 'max_price',
+          rules      : [
+            {
+              type   : 'empty',
+              prompt : this.l10n.t('Maximum price for donation tickets required')
+            },
+            {
+              type   : 'number',
+              prompt : this.l10n.t('Invalid number')
+            },
```
Comment (kushthedude) [inline app/components/forms/wizard/basic-details-step.js]:
```js
{
              type   : 'empty',
              prompt : this.l10n.t('Maximum price for donation tickets required')
            },
            {
              type   : 'number',
              prompt : this.l10n.t('Invalid number')
            },
```
Same here rather than `number` and `empty` , Just use `Integer` .

File: app/components/forms/wizard/basic-details-step.js (hunk 5 above)
Comment (kushthedude) [inline app/components/forms/wizard/basic-details-step.js]:
```js
{
              type   : 'number',
              prompt : this.l10n.t('Invalid number')
            },
            {
              type   : 'integer[1..]',
              prompt : this.l10n.t('Ticket price needs to be greater than zero')
            },
```
No need for two validations here too , Integer can be only used

File: app/components/forms/wizard/basic-details-step.js (hunk 6 above)
Comment (kushthedude) [inline app/components/forms/wizard/basic-details-step.js]:
```js
{
              type   : 'empty',
              prompt : this.l10n.t('Maximum price for donation tickets required')
            },
            {
              type   : 'number',
              prompt : this.l10n.t('Invalid number')
            },
```
Same here rather than `number` and `empty` , Just use `Integer` .

Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: @kushthedude I think that the empty field validator is required to indicate that it is necessary for the organizer to specify the max. price for a donation. On the other hand, I agree with the removal  of the number validator.

File: app/components/forms/wizard/basic-details-step.js (hunk 5 above)
Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: Removed the number validator.

File: app/components/public/ticket-list.js (hunk 2 above)
Comment (mrsaicharan1) [reply app/components/public/ticket-list.js]: @kushthedude Added the info circle icon as a pop-up for this.

File: app/components/forms/wizard/basic-details-step.js (hunk 4 above)
Comment (niranjan94) [reply app/components/forms/wizard/basic-details-step.js]: @mrsaicharan1 `checkMaxMin` should validate the min and max price of that specific ticket. In this I do not know which donation ticket (of a list of multiple) you are validating

Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: @niranjan94 I'm a little stuck in implementing this check for a specific donation ticket. How should I be doing this?

Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: @niranjan94 should be adding an` id` attribute to the div tag for min and max price, like here?
`div id="{{ticket.id}}_price"` & validate it by using `if (this.$('.ui.form').form('get value', '{{ticket.id}}_min_price')[0] < this.$('.ui.form').form('get value', '{{ticket.id}}_max_price')[0]) `

Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: But the problem here is that the ticket won't have an id till we add it. What do you suggest?

**Comment by mrsaicharan1** [comment]
I’ve written 2 validation rules checkMax and checkMin as multiple paramters are not supported by validation rules.
Reference:https://github.com/Semantic-Org/Semantic-UI/issues/3682#issuecomment-184583162

It’s getting validated but it always returns false. Always prompts Ticket max price should be greater than min price

File: app/components/forms/wizard/basic-details-step.js [hunk 7]
```diff
@@ -121,6 +121,20 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+      }
+      return returnValue;
+    };
+    window.$.fn.form.settings.rules.checkMin = (value, max_price) => {
+      let returnValue = false;
+      if (max_price > value) {
+        returnValue = true;
+      }
+      return returnValue;
+    };
```
Comment (mrsaicharan1) [inline app/components/forms/wizard/basic-details-step.js]: @niranjan94 @CosmicCoder96 @uds5501 @shreyanshdwivedi I’ve written 2 validation rules checkMax and checkMin as multiple paramters are not supported by validation rules.
Reference:https://github.com/Semantic-Org/Semantic-UI/issues/3682#issuecomment-184583162

It’s getting validated but it always returns false. Always prompts Ticket max price should be greater than min price.

Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: @niranjan94 I'm a little stuck in implementing this check for a specific donation ticket. How should I be doing this?

File: app/components/public/ticket-list.js [hunk 8]
```diff
@@ -40,7 +40,23 @@ export default Component.extend(FormMixin, {
...
+        if (donationTicket.price >= donationTicket.minPrice) {
+          returnValue = true;
+        } else {
+          returnValue = false;
+        }
+      }
+    });
+    return returnValue;
+  }),
+
```
Comment (kushthedude) [inline app/components/public/ticket-list.js]: @mrsaicharan1 Include Validation For `Max Price` too

File: app/templates/components/public/ticket-list.hbs [hunk 9]
```diff
@@ -16,6 +16,9 @@
             <td>
               <div class="ui small">
                 {{ticket.name}}
+                {{#if (eq ticket.type 'donation')}}
+                  {{ui-popup tagName="i" class="info icon" content=(concat "Donation value should be greater than " ticket.minPrice " " eventCurrency)}}
```
Comment (kushthedude) [inline app/templates/components/public/ticket-list.hbs]: @mrsaicharan1 Make it `Value should be between x & y`

File: app/components/forms/wizard/basic-details-step.js (hunk 7 above)
Comment (kushthedude) [reply app/components/forms/wizard/basic-details-step.js]: @mrsaicharan1 If you are not able to do this with `Semantic UI` , I just you remove the FE validations and throw a server error when `Max Price` is less than `Min Price` , Similar to what we have done in case of `Date & Time` , `Min and Max Number of Tickets orderable at one time`

Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: @kushthedude https://github.com/fossasia/open-event-frontend/pull/3194#issuecomment-505288106

Comment (mrsaicharan1) [reply app/components/forms/wizard/basic-details-step.js]: @kushthedude I had already written a validation check for max and min price! I had completely forgotten about it! Thanks for that. There was a naming convention error in the FE. That was the main reason the validation wasn't able to detect the data attributes going in properly.
Screenshot 2019-07-02 at 9 00 44 AM

**Comment by mrsaicharan1** [comment]
@niranjan94 @CosmicCoder96 I had already written a validation check for min/max price on the server. I feel that the FE validation isn't required as Max/min tickets per order also follows the same practice. Please have a look.

**Comment by mrsaicharan1** [comment]
Screenshot 2019-07-02 at 9 00 44 AM

**Comment by mrsaicharan1** [comment]
@niranjan94 I've added checks via an action in the input. Is this okay ?

File: app/templates/components/widgets/forms/ticket-input.hbs [hunk 10]
```diff
@@ -12,10 +12,10 @@
     {{else if (eq ticket.type 'donation')}}
       <div class="two fields">
         <div class="field">
-          {{input type='number' name='min_price' placeholder=(t 'Min') value=ticket.minOrder}}
+          {{input type='number' name='min_price' onChange=(action 'minMaxCheck' ticket) placeholder=(t 'Min') value=ticket.minPrice min=1}}
```
Comment (niranjan94) [inline app/templates/components/widgets/forms/ticket-input.hbs]: No action needed. Add a computed property on ticket-input component that looks at ticket.minPrice and ticket.minPrice to see if it is valid or not.

File: app/templates/components/public/ticket-list.hbs [hunk 11]
```diff
@@ -16,6 +16,9 @@
             <td>
               <div class="ui small">
                 {{ticket.name}}
+                {{#if (eq ticket.type 'donation')}}
+                  {{ui-popup tagName="i" class="info icon" content=(concat "Donation value should be between than " ticket.minPrice " " eventCurrency " and " ticket.maxPrice " " eventCurrency)}}
```
Comment (niranjan94) [inline app/templates/components/public/ticket-list.hbs]: The error message must come as a part of the input using the input error classes supported by semantic-ui

File: app/components/widgets/forms/ticket-input.js [hunk 12]
```diff
@@ -6,6 +6,11 @@ export default Component.extend({
   actions: {
     toggleSettings() {
       this.toggleProperty('isExpanded');
+    },
+    minMaxCheck(ticket) {
+      if (ticket.minPrice > ticket.maxPrice) {
+        this.notify.error(this.l10n.t('Minimum price should be less than maximum price'));
```
Comment (niranjan94) [inline app/components/widgets/forms/ticket-input.js]: Nope. No notification. Instead error message should be shown with the element itself

File: app/templates/components/widgets/forms/ticket-input.hbs (hunk 10 above)
Comment (mrsaicharan1) [reply app/templates/components/widgets/forms/ticket-input.hbs]: @niranjan94 Can ember helpers be used instead of it? Because I'm facing a problem of checking for a specific ticket. If I use a helper, I think it would be possible to pass parameters into it as given below. 
`{{#if (donation-valid ticket.minPrice ticket.maxPrice) }}`

Comment (mrsaicharan1) [reply app/templates/components/widgets/forms/ticket-input.hbs]: Screenshot 2019-07-03 at 6 13 02 PM
I was able to achieve this via ember helpers.

File: app/templates/components/public/ticket-list.hbs (hunk 11 above)
Comment (mrsaicharan1) [reply app/templates/components/public/ticket-list.hbs]: @niranjan94 Done. But I've left the  `{{ui-popup}}` for information purposes. Is that alright?

File: app/templates/components/public/ticket-list.hbs [hunk 13]
```diff
@@ -47,7 +50,13 @@
               </td>
             {{else}}
               <td id="{{ticket.id}}_price">
-                {{currency-symbol eventCurrency}} {{format-number ticket.price}}
+                {{#if (eq ticket.type 'donation') }}
+                  <div class="field {{if (eq (donation-valid ticket.price ticket.minPrice ticket.maxPrice) false) 'error'}}" >
```
Comment (niranjan94) [inline app/templates/components/public/ticket-list.hbs]: Validation for the public page can still be achieved with semantic-ui validator. So why have you not used it ?

File: app/templates/components/widgets/forms/ticket-input.hbs [hunk 14]
```diff
@@ -11,11 +11,11 @@
       </div>
     {{else if (eq ticket.type 'donation')}}
       <div class="two fields">
-        <div class="field">
-          {{input type='number' name='min_price' placeholder=(t 'Min') value=ticket.minOrder}}
+        <div class="field {{if (eq (donation-valid ticket.minPrice ticket.maxPrice) false) 'error'}}" >
```
Comment (niranjan94) [inline app/templates/components/widgets/forms/ticket-input.hbs]: No helper needed for this. Define a computed property inside the ticket-input component to do the validation on `ticket.minPrice` and `ticket.maxPrice`

File: app/templates/components/public/ticket-list.hbs (hunk 13 above)
Comment (mrsaicharan1) [reply app/templates/components/public/ticket-list.hbs]: @niranjan94 Yeah, Will do that.

Comment (mrsaicharan1) [reply app/templates/components/public/ticket-list.hbs]: @niranjan94 The validation for it being between the minimum and maximum price wasn't working. For it to be greater than 1(`integer[1..]`), it's working. `checkMinMax[max_price, min_price]` doesn't seem to work.

File: app/templates/components/widgets/forms/ticket-input.hbs (hunk 14 above)
Comment (mrsaicharan1) [reply app/templates/components/widgets/forms/ticket-input.hbs]: @niranjan94 Okay.

File: app/components/widgets/forms/ticket-input.js (hunk 12 above)
Comment (mrsaicharan1) [reply app/components/widgets/forms/ticket-input.js]: Screenshot 2019-07-04 at 7 39 32 AM
I've used the semantic tooltip for this

File: app/templates/components/public/ticket-list.hbs (hunk 13 above)
Comment (mrsaicharan1) [reply app/templates/components/public/ticket-list.hbs]: @niranjan94 What do you suggest?

Comment (niranjan94) [reply app/templates/components/public/ticket-list.hbs]: @mrsaicharan1 what is stopping you from using `integer` ? That can be used easily for this right ?

Generate the validation rules dynamically ... One rule per ticket with varying integer ranges based on that ticket's min/max price

File: app/components/widgets/forms/ticket-input.js [hunk 15]
```diff
@@ -1,8 +1,15 @@
 import Component from '@ember/component';
+import { computed } from '@ember/object';
 
 export default Component.extend({
-  classNames: ['ui', 'celled', 'stackable', 'grid', 'ticket-row'],
-
+  classNames  : ['ui', 'celled', 'stackable', 'grid', 'ticket-row'],
+  minMaxValid : computed('ticket.minPrice', 'ticket.maxPrice', function() {
+    if (this.ticket.minPrice > this.ticket.maxPrice) {
```
Comment (niranjan94) [inline app/components/widgets/forms/ticket-input.js]: Use [`gt`](http://api.emberjs.com/ember/3.10/functions/@ember%2Fobject%2Fcomputed/gt)

File: app/templates/components/widgets/forms/ticket-input.hbs [hunk 16]
```diff
@@ -11,11 +11,11 @@
       </div>
     {{else if (eq ticket.type 'donation')}}
       <div class="two fields">
-        <div class="field">
-          {{input type='number' name='min_price' placeholder=(t 'Min') value=ticket.minOrder}}
+        <div class="field {{if (eq minMaxValid false) 'error'}}" >
```
Comment (niranjan94) [inline app/templates/components/widgets/forms/ticket-input.hbs]: Why are you equating it with false ? 

Just `{{unless minMaxValid 'error'}}` would work

Comment (mrsaicharan1) [reply app/templates/components/widgets/forms/ticket-input.hbs]: @niranjan94 Done. Forgot about unless!

File: app/components/widgets/forms/ticket-input.js (hunk 15 above)
Comment (mrsaicharan1) [reply app/components/widgets/forms/ticket-input.js]: Yeah, I guess that's better

File: app/components/public/ticket-list.js [hunk 17]
```diff
@@ -176,14 +200,32 @@ export default Component.extend(FormMixin, {
...
+            {
+              type   : `integer[${donationTicket.minPrice}..${donationTicket.maxPrice}]`,
+              prompt : this.l10n.t(`Please enter a donation amount between ${donationTicket.minPrice} and ${donationTicket.maxPrice}`)
+            }
+          ]
+        }
+      });
+    });
+    return validationRules;
+  }),
```
Comment (mrsaicharan1) [inline app/components/public/ticket-list.js]: @niranjan94 I've generated one rule per ticket in this way, and merged it with the fields of validationRules in the end. It works fine now.

File: app/templates/components/public/ticket-list.hbs (hunk 13 above)
Comment (mrsaicharan1) [reply app/templates/components/public/ticket-list.hbs]: @niranjan94 Done.

File: app/components/widgets/forms/ticket-input.js [hunk 18]
```diff
@@ -1,8 +1,12 @@
 import Component from '@ember/component';
+import { computed } from '@ember/object';
+import { gte } from '@ember/object/computed';
 
 export default Component.extend({
-  classNames: ['ui', 'celled', 'stackable', 'grid', 'ticket-row'],
-
+  classNames  : ['ui', 'celled', 'stackable', 'grid', 'ticket-row'],
+  minMaxValid : computed('ticket.minPrice', 'ticket.maxPrice', function() {
+    gte('this.ticket.maxPrice', 'this.ticket.minPrice');
```
Comment (niranjan94) [inline app/components/widgets/forms/ticket-input.js]: @mrsaicharan1 did you even test this ? Please don't copy paste code from the documentation without even seeing how it works and how to use it ... 

And also, please test stuff locally ...

File: app/templates/components/public/ticket-list.hbs (hunk 13 above)
Comment (niranjan94) [reply app/templates/components/public/ticket-list.hbs]: > Generated one rule per ticket and merged it with the validation rules

Perfect 🎉

**Comment by mrsaicharan1** [comment]
Umm, i've just seen the documentation and I didn't just copy & paste it😅.
It seems to be working locally.

File: app/components/widgets/forms/ticket-input.js (hunk 18 above)
Comment (mrsaicharan1) [reply app/components/widgets/forms/ticket-input.js]: @niranjan94 Uh-oh. This would be breaking the check in a reckless manner. I didn't mean to push this. Sorry for that. I've properly used the helper now...

File: app/templates/components/widgets/forms/ticket-input.hbs [hunk 19]
```diff
@@ -11,11 +11,11 @@
       </div>
     {{else if (eq ticket.type 'donation')}}
       <div class="two fields">
-        <div class="field">
-          {{input type='number' name='min_price' placeholder=(t 'Min') value=ticket.minOrder}}
+        <div class="field {{unless (gte ticket.maxPrice ticket.minPrice) 'error'}}" >
```
Comment (mrsaicharan1) [inline app/templates/components/widgets/forms/ticket-input.hbs]: @niranjan94 Travis fails by saying   `14:35  error  Using {{unless}} in combination with other helpers should be avoided. MaxHelpers: 0  simple-unless`.

Comment (mrsaicharan1) [reply app/templates/components/widgets/forms/ticket-input.hbs]: Okay. Just got it. ES6 style classes.

File: app/components/widgets/forms/ticket-input.js (hunk 18 above)
Comment (niranjan94) [reply app/components/widgets/forms/ticket-input.js]: @mrsaicharan1 not the template helper. I meant this => [`gte`](http://api.emberjs.com/ember/3.10/functions/@ember%2Fobject%2Fcomputed/gte).

Try not to keep validation logics in the template.

Comment (mrsaicharan1) [reply app/components/widgets/forms/ticket-input.js]: Just to be clear, instead of this in the template`{{unless (gte ticket.maxPrice ticket.minPrice) 'error'}}`, we need it in the controller logic right(using gte)?

**Comment by mrsaicharan1** [comment]
@niranjan94 I've made the requested changes. used `gte` from the Ember API for comparison and removed major validation logic from the template. Please have a look.

**Comment by mrsaicharan1** [comment]
@niranjan94 I've made the requested changes. Used `gte` from the ember API for comparison & removed major validation logic in the template

File: app/components/public/ticket-list.js [hunk 20]
```diff
@@ -176,14 +200,32 @@ export default Component.extend(FormMixin, {
       this.send('togglePromotionalCode', this.code);
     }
   },
+  donationTicketsValidation: computed('donationTickets.@each.id', 'donationTickets.@each.minPrice', 'donationTickets.@each.maxPrice', function() {
+    let validationRules = {};
+    this.donationTickets.forEach(donationTicket => {
+      validationRules = merge(validationRules, {
```
[the remark this answers is not in the document]
Comment (mrsaicharan1) [reply app/components/public/ticket-list.js]: @niranjan94 Yeah, I guess you're right. Removed the redudant merge.

File: app/components/public/ticket-list.js [hunk 21]
```diff
@@ -176,14 +200,32 @@ export default Component.extend(FormMixin, {
       this.send('togglePromotionalCode', this.code);
     }
   },
+  donationTicketsValidation: computed('donationTickets.@each.id', 'donationTickets.@each.minPrice', 'donationTickets.@each.maxPrice', function() {
+    let validationRules = {};
+    this.donationTickets.forEach(donationTicket => {
```
[the remark this answers is not in the document]
Comment (mrsaicharan1) [reply app/components/public/ticket-list.js]: @niranjan94 Done.

File: app/components/public/ticket-list.js [hunk 22]
```diff
@@ -39,8 +46,25 @@ export default Component.extend(FormMixin, {
       ticket => (ticket.orderQuantity || 0)
     ) > 0;
   }),
+  donationTickets: computed.filterBy('data', 'type', 'donation'),
+
+  isDonationPriceValid: computed('donationTickets.@each.orderQuantity', 'donationTickets.@each.price', function() {
+    let returnValue = false;
```
Comment (niranjan94) [inline app/components/public/ticket-list.js]: Can be simplified into 

```js
  for (const ticket of this.donationTickets) {
    if (donationTicket.orderQuantity > 0) {
      if (donationTicket.price < donationTicket.minPrice || donationTicket.price > donationTicket.maxPrice) {
        return false
      }
    }
  }
  return true
```

File: app/components/public/ticket-list.js [hunk 23]
```diff
@@ -176,14 +200,30 @@ export default Component.extend(FormMixin, {
...
+            prompt : this.l10n.t(`Please enter a donation amount between ${donationTicket.minPrice} and ${donationTicket.maxPrice}`)
+          }
+        ]
+      };
+    }
+    return validationRules;
+  }),
   getValidationRules() {
-    return {
+    let validationRules = {
```
Comment (niranjan94) [inline app/components/public/ticket-list.js]: Can be a const

File: app/components/public/ticket-list.js [hunk 24]
```diff
@@ -176,14 +200,30 @@ export default Component.extend(FormMixin, {
       this.send('togglePromotionalCode', this.code);
     }
   },
+  donationTicketsValidation: computed('donationTickets.@each.id', 'donationTickets.@each.minPrice', 'donationTickets.@each.maxPrice', function() {
+    let validationRules = {};
```
Comment (niranjan94) [inline app/components/public/ticket-list.js]: Can be a const

File: app/components/public/ticket-list.js (hunk 22 above)
Comment (mrsaicharan1) [reply app/components/public/ticket-list.js]: @niranjan94 Done.
