### PR TITLE
fix: Remove draft button in published events

### LINKED ISSUE #2865: Don't show "Save as Draft" in Wizard once event is published
Once an event is published the option "Saved as Draft" is very confusing. Clicking it will result in unpublishing the event. Don't show the option "Save as Draft" once the event is published. Only show the option "Save as Draft" if an event is in the stage "Unpublished.

Screenshot from 2019-05-06 01-08-16

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
remove save as draft button from published events

Fixes #2865

### CODE REVIEW

**Comment by uds5501** [comment]
@CosmicCoder96 @ritikamotwani Please review

File: app/components/forms/wizard/basic-details-step.js [hunk 1]
```diff
@@ -91,6 +91,10 @@ export default Component.extend(FormMixin, EventWizardMixin, {
     return this.get('data.event.topic.subTopics');
   }),
 
+  showDraftButton: computed('data.event.state', 'data.event.location', function() {
```
Comment (CosmicCoder96) [inline app/components/forms/wizard/basic-details-step.js]: why do you want to watch `data.event.location`?

File: app/components/forms/wizard/basic-details-step.js [hunk 2]
```diff
@@ -91,6 +91,10 @@ export default Component.extend(FormMixin, EventWizardMixin, {
...
+    return (this.get('data.event.state') !== 'published');
```
Comment (CosmicCoder96) [inline app/components/forms/wizard/basic-details-step.js]:
```js
 return this.data.event.state !== 'published';
```

File: app/components/forms/wizard/basic-details-step.js (hunk 1 above)
Comment (uds5501) [reply app/components/forms/wizard/basic-details-step.js]: Accidentally put it there, removing it

**Comment by uds5501** [comment]
@CosmicCoder96 Please review
