### PR TITLE
Fix : Improving filter for admin/user active list

### LINKED ISSUE #2134: Inactive Users  being shown in Active sections of Admin/Users
**Describe the bug**

Currently Inactive Users  are being shown in Active sections of Admin/Users
**To Reproduce**
1. Go to Admin/Users
2. Click on Active
3. See error

**Expected behavior**

It should not show the Inactive User over here

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

Working on it

### PR DESCRIPTION
**Pull request by uds5501**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Currently the non deleted users are being shown in Active tab , additional filter is required for utilising last accessed status  

#### Changes proposed in this pull request:

- Using `last-accessed-at` as a query parameter

image

Fixes #2134

### CODE REVIEW

File: app/routes/admin/users/list.js [hunk 1]
```diff
@@ -22,9 +23,18 @@ export default Route.extend({
...
+          and: [
+            {
+              name : 'deleted-at',
+              op   : 'eq',
+              val  : null
+            },
+            {
+              name : 'last-accessed-at',
+              op   : 'ge',
+              val  : moment().subtract(1, 'M').toISOString()
```
Comment (CosmicCoder96) [inline app/routes/admin/users/list.js]: Make it one year

Comment (uds5501) [reply app/routes/admin/users/list.js]: @CosmicCoder96  Doing so
