### PR TITLE
 fix: Team Page Empty email fields

### LINKED ISSUE #5526: Team Page : Empty email fields
**Bug**
Whenever an organiser tries to add people with empty input fields, the frontend shows the empty fields after submission.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Events Section
2. Create an Event
3.  Go to teams section
4. Add people with empty fields
5) See the bug

**Expected behaviour**
When an owner tries to add another organizer without providing an email it should not be possible submit the form. The form should just show "field required" or similar error message.

**Screenshot**
Screenshot 2020-11-08 at 1 41 21 PM

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5526 

#### Short description of what this resolves:
Fixed showing empty email fields in the team.

#### Changes proposed in this pull request:

- when we click on add people and then click on side of the screen, the empty entry that was created for creating the people still appears which is fixed by adding an if statement

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@iamareebjamal Please see to the changes I have made.
These changes were made only in UI bcz the empty entries on reloading page is no longer shown but only shown when being on same page and clicking add people and then clicking on backdrop.

**Comment by iamareebjamal** [comment]
That's not a fix. The entry should be deleted if someone clicks out of the window

**Comment by daretobedifferent18** [comment]
@iamareebjamal Please see the changes I have made and let me know to change anything.

File: app/components/modals/modal-base.js [hunk 1]
```diff
@@ -15,6 +15,9 @@ export default UiModal.extend({
     if (this.isOpen) {
       $element.modal(this.defaultOptions).modal('show');
     } else {
+      if(this.unloadRecord){
```
Comment (iamareebjamal) [inline app/components/modals/modal-base.js]: Please remove. You already have a callback for modal closing. Makes no sense to put logic of user role modal in modal base

Comment (daretobedifferent18) [reply app/components/modals/modal-base.js]: @iamareebjamal then the solution to this problem could be disabling clicking outside the window so that the modal won't unless user click on cancel button and clicking on cancel button is already deleting the empty record created.

Comment (iamareebjamal) [reply app/components/modals/modal-base.js]: Not really. There are tons of ways to solve it

Comment (daretobedifferent18) [reply app/components/modals/modal-base.js]: @iamareebjamal So in the previous solution where I was calling the function when the user click outside the box in the modal-base.Is this not be good enough sol? bcz what actually we want to do is that calling the function when the modal closes.

Comment (daretobedifferent18) [reply app/components/modals/modal-base.js]: > Please remove. You already have a callback for modal closing. Makes no sense to put logic of user role modal in modal base

@iamareebjamal and I have removed the function which was calling for modal closing and put it inside modal-base bcz we want same thing to happen even if user click on cancel button or outside the model

**Comment by daretobedifferent18** [comment]
@iamareebjamal I have come with the changes. Please see to the changes I have made now and let me know to change anything

**Comment by iamareebjamal** [comment]
Check every other modal that it's working correctly

**Comment by daretobedifferent18** [comment]
> Check every other modal that it's working correctly

@iamareebjamal I have checked all the modals and every modal is working correctly.

File: app/components/modals/modal-base.js [hunk 2]
```diff
@@ -15,6 +15,7 @@ export default UiModal.extend({
     if (this.isOpen) {
       $element.modal(this.defaultOptions).modal('show');
     } else {
+      this.close();
```
Comment (iamareebjamal) [inline app/components/modals/modal-base.js:18]: Won't this cause recursive error?

**Review by iamareebjamal — APPROVED** [review]

File: app/components/modals/modal-base.js (hunk 2 above)
Comment (daretobedifferent18) [reply app/components/modals/modal-base.js:18]: No its no causing
