### PR TITLE
Fix dropdowns for session-speaker create and edit form

### LINKED ISSUE #2023: Additional session dropdown fields displaying no options
**Describe the bug**

Any extra field asked for a new session results in a `No results found` given that the field type is drop-down.
**To Reproduce**
1. Add any drop-down type field in customize registration form
2. Now go to Create Session from event management
3. Scroll down to the new drop-down field

**Expected behavior**

Any new drop-down should be returning a list of valid options.

**Screenshots**

The Drop down options:  
sessionerror
The customized registration: 
sessionsettings

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Google Chrome 
 - Version [e.g. 22]  71.0.3578.98

**Additional context**

Open for all

### PR DESCRIPTION
**Pull request by ritikamotwani**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Adds a country drop down to the form.
- Adds a language drop down to the form.

Fixes #2023

### CODE REVIEW

File: app/components/forms/session-speaker-form.js [hunk 1]
```diff
@@ -467,6 +468,10 @@ export default Component.extend(FormMixin, {
     return orderBy(countries, 'name');
   }),
 
+  languages: computed(function() {
```
Comment (niranjan94) [inline app/components/forms/session-speaker-form.js]: I don't think we need this to be a computed property. Both `languages` and `countries` can just be be direct properties on the object.

```js
countries: orderBy(countries, 'name'),
languages: orderBy(languages, 'name')
```
