### PR TITLE
fix: Only allow one email address of "event owner" in the Reply-to email

### LINKED ISSUE #6686: Organizer Speaker Info: Only allow one email address of "event owner" in the Reply-to email
The reply-to field in the speaker notification emails has one field. Currently all organizers are filled in. However Sendgrid only support one emails. Therefore please only keep the event owner in this email reply-to field.

Screenshot from 2021-02-13 06-38-13

### PR DESCRIPTION
**Pull request by ranjitkshah**
Fixes #6686 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: app/components/modals/session-notify-modal.js [hunk 1]
```diff
@@ -50,10 +50,15 @@ export default class SessionNotifyModal extends ModalBase {
 
   @computed('sessionId')
   get organizersEmails() {
+    const session = this.store.peekRecord('session', this.sessionId);
```
Comment (iamareebjamal) [inline app/components/modals/session-notify-modal.js:53]: Remove this function as it is not needed anywhere now
