### PR TITLE
fix: Timezone Display shows numbers instead of timezone name

### LINKED ISSUE #5749: Timezone Display shows numbers instead of timezone name
Some events display the timezone while others display e.g. (+08). Please change the implementation in a way that it always displays timezones correctly in all areas including on:
* Frontpage
* Events Dashboard
* Specific event dashboard
* Public event pages
* Admin pages

Screenshot from 2020-11-25 09-30-27l a
Screenshot from 2020-11-25 09-29-50

Screenshot from 2020-11-25 09-30-49

Screenshot from 2020-11-25 09-31-42

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #5749

#### Short description of what this resolves:
Some events display the timezone while others display e.g. (+08). Please change the implementation in a way that it always displays timezones correctly in all areas.

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@iamareebjamal Pls review this, its done

**Comment by iamareebjamal** [comment]
Once we do #5796, it'll be much simpler to do

**Comment by iamareebjamal** [comment]
I'll discuss the approach to be used in the meeting at 7 PM

**Comment by daretobedifferent18** [comment]
@iamareebjamal I was searching for the approach u asked for and I found some useful information which might be useful. 
https://github.com/moment/moment-timezone/issues/477
https://github.com/moment/moment-timezone/issues/500

**Comment by iamareebjamal** [comment]
But what's the solution?

**Comment by daretobedifferent18** [comment]
> But what's the solution?

Solution could be defining all the country codes manually in an array and taking the country code from there bcz acc to the issue i linked in the above comment, they have removed country code bcz those country don't use them

**Comment by iamareebjamal** [comment]
Did you try `moment.tz(params[0], timezone).zoneAbbr()`

See what it returns

**Comment by iamareebjamal** [comment]
I changed it from that to (z) and it has been broken since https://github.com/fossasia/open-event-frontend/pull/4794/files

**Comment by daretobedifferent18** [comment]
> I changed it from that to (z) and it has been broken since https://github.com/fossasia/open-event-frontend/pull/4794/files

ok I'll see to it

**Comment by iamareebjamal** [comment]
Also check this if it doesn't work https://gist.github.com/redoPop/3915761

**Comment by daretobedifferent18** [comment]
@iamareebjamal I have tried with both the approach, they both are giving numbers only and not tz abbr

**Comment by iamareebjamal** [comment]
Then get abbr and if it doesn't give code back, use a dict of mapping tz codes. Dict should only contain those timezones which are not mapped in moment

**Comment by daretobedifferent18** [comment]
> Then get abbr and if it doesn't give code back, use a dict of mapping tz codes. Dict should only contain those timezones which are not mapped in moment

Okay so what I should do now is create a dict for all those tz where moment is giving back number instead of tz abbr and then get abbr from moment and if it gives number then take tz abbr from dict I will be creating.

**Comment by daretobedifferent18** [comment]
And what I found is that there are 226 tz whose tz Abbr is number.

**Comment by daretobedifferent18** [comment]
@iamareebjamal 
I was thinking of the approach of getting country code from moment and then concating it with 'T' but the results are not coming correct for all. So I think the approach left is what we discussed above.

**Comment by daretobedifferent18** [comment]
@iamareebjamal could you pls tell me from where I should reference timezone abbr for left out countries.

**Comment by iamareebjamal** [comment]
https://www.timeanddate.com/time/zones/

File: app/helpers/general-date.js [hunk 1]
```diff
@@ -25,12 +26,14 @@ export function generalDate(params, { tz }) {
...
-  if (reg.test(z)) {
-    dateTime = dateTime.replace(z, timezone);
+  const formatWithoutTz = format.replace(' (z)', '');
+
+  let dateTime = moment(params[0]).tz(timezone).format(formatWithoutTz);
+
+  const timezoneAbbr = tzAbbr[timezone] || moment(params[0]).tz(timezone).format('z');
+
+  if (format.includes('(z)')) {
+    dateTime = dateTime.concat(` (${timezoneAbbr})`);
```
Comment (iamareebjamal) [inline app/helpers/general-date.js:36]: Don't do this much of replacing and concat

Just remove (z) from the format literal, and append the abbreviation if the passed in code format was among the tz variants

Comment (daretobedifferent18) [reply app/helpers/general-date.js:36]: and then what about default case?

Comment (iamareebjamal) [reply app/helpers/general-date.js:36]: I thought we moved all timezone displaying strings in keywords. That was the goal of this PR

Comment (daretobedifferent18) [reply app/helpers/general-date.js:36]: > I thought we moved all timezone displaying strings in keywords. That was the goal for this PR

oh really, if that's the case then I can do that

Comment (iamareebjamal) [reply app/helpers/general-date.js:36]: Please check once as well

Comment (daretobedifferent18) [reply app/helpers/general-date.js:36]: goal for this or for the other timezone add argument tz one PR ?

Comment (daretobedifferent18) [reply app/helpers/general-date.js:36]: Done with all tz display string keywords

**Comment by daretobedifferent18** [comment]
@iamareebjamal Its Done. Pls let me know to make any changes further

File: app/components/public/add-to-calender.hbs [hunk 2]
```diff
@@ -3,11 +3,10 @@
     <i class="clock alternate outline icon pt-1"></i>
     <div class="content">
       {{#if this.isSingleDay}}
-        {{general-date @event.startsAt "dddd, D MMMM, YYYY" tz=@event.timezone}}<br>{{general-date @event.startsAt "h:mm A" tz=@event.timezone}} {{t 'to'}} {{general-date @event.endsAt "h:mm A" tz=@event.timezone}} 
+        {{general-date @event.startsAt "dddd, D MMMM, YYYY" tz=@event.timezone}}<br>{{general-date @event.startsAt 'time-tz-short' tz=@event.timezone}} {{t 'to'}} {{general-date @event.endsAt "h:mm A" tz=@event.timezone}}
```
Comment (iamareebjamal) [inline app/components/public/add-to-calender.hbs:6]: Better is to create another keyword like `time-tz-short` -> `tz` and use it to replace `({{this.timezone}})`

File: app/helpers/general-date.js [hunk 3]
```diff
@@ -17,14 +18,23 @@ export function generalDate(params, { tz }) {
...
     format = format.replace(' a', '');
   }
-  return moment(params[0]).tz(timezone).format(format);
+
+  let dateTime = moment(params[0]).tz(timezone).format(format);
+
+  const timezoneAbbr = tzAbbr[timezone] || moment(params[0]).tz(timezone).format('z');
+
+  if (!params[1] || params[1].includes('tz')) {
+    dateTime = dateTime.concat(` (${timezoneAbbr})`);
```
Comment (iamareebjamal) [inline app/helpers/general-date.js:34]: Why concat? Why not just ```return dateTime + ` (${timezoneAbbr})`;```

File: app/utils/dictionary/tzAbbr.ts [hunk 4]
```diff
@@ -0,0 +1,228 @@
...
+  'America/Argentina/Cordoba'        : 'ART',
+  'America/Argentina/Jujuy'          : 'ART',
+  'America/Argentina/La_Rioja'       : 'ART',
+  'America/Argentina/Mendoza'        : 'ART',
+  'America/Argentina/Rio_Gallegos'   : 'ART',
+  'America/Argentina/Salta'          : 'ART',
+  'America/Argentina/San_Juan'       : 'ART',
+  'America/Argentina/San_Luis'       : 'ART',
+  'America/Argentina/Tucuman'        : 'ART',
+  'America/Argentina/Ushuaia'        : 'ART',
```
Comment (iamareebjamal) [inline app/utils/dictionary/tzAbbr.ts:15]: Please remove any ambiguous entry, i.e., any code which is repeated for 2 timezones

Comment (daretobedifferent18) [reply app/utils/dictionary/tzAbbr.ts:15]: but they all are diff timezones

Comment (iamareebjamal) [reply app/utils/dictionary/tzAbbr.ts:15]: Exactly, and they all show ART, which is ambiguous

Comment (daretobedifferent18) [reply app/utils/dictionary/tzAbbr.ts:15]: I understand all but like 
'America/Argentina/Buenos_Aires'   : 'ART',
'America/Argentina/Catamarca'      : 'ART',

both are unique so removing any on one results in not getting tz abbr

@iamareebjamal 
I want to know that is there a way we can create multiple keys with a single value object?

Comment (iamareebjamal) [reply app/utils/dictionary/tzAbbr.ts:15]: No, just remove them and let the offset show as the timezone like the current situation

When you see CRT, should it be considered China Standard Time or Cuba Standard Time. Hence, remove all entries which have ambiguous abbreviations between two timezones.

Comment (daretobedifferent18) [reply app/utils/dictionary/tzAbbr.ts:15]: ohk like that :+1:
but also I think I should not remove that abbr where they are duplicated but have same full forms like in above ART is used for Argentina Time which is same?

Comment (iamareebjamal) [reply app/utils/dictionary/tzAbbr.ts:15]: No, they can be confusing, better to remove them

Comment (daretobedifferent18) [reply app/utils/dictionary/tzAbbr.ts:15]: Last question like 'TRT' abbr is for 3 of them then which one to keep and which to remove?

Comment (iamareebjamal) [reply app/utils/dictionary/tzAbbr.ts:15]: Remove all which have more than one, so no TRT will be shown, because then how would a person know which of the 3 TRT represents?

**Comment by daretobedifferent18** [comment]
@iamareebjamal Done

File: app/helpers/general-date.js [hunk 5]
```diff
@@ -1,13 +1,15 @@
...
   'date-time-long'     : 'dddd, D MMMM, YYYY h:mm A',
-  'date-time-tz-long'  : 'dddd, D MMMM, YYYY h:mm A (z)',
+  'date-time-tz-long'  : 'dddd, D MMMM, YYYY h:mm A',
   'date-time-short'    : 'D MMM, YYYY h:mm A',
-  'date-time-tz-short' : 'D MMM, YYYY h:mm A (z)',
+  'date-time-tz-short' : 'D MMM, YYYY h:mm A',
   'date-short'         : 'D MMM, YYYY',
-  'time-tz-short'      : 'h:mm A (z)'
+  'time-tz-short'      : 'h:mm A',
+  'tz'                 : ' '
```
Comment (iamareebjamal) [inline app/helpers/general-date.js:12]: Shouldn't it be empty string?

**Comment by iamareebjamal** [comment]
Run `yarn lint`

File: app/helpers/general-date.js (hunk 5 above)
Comment (daretobedifferent18) [reply app/helpers/general-date.js:12]: No bcz then format will be 'tz' which after passing to moment will convert to for eg tz is Asia/Kolkata then will convert to tIST and then after appending timezoneabbr again will finally give ```tIST (IST)```

So just to get format correct when this line is executed 
```js
let format = (dateFormats[params[1]] || params[1]) || 'h:mm A, MMMM Do YYYY';
```

'tz' : ' '

Comment (daretobedifferent18) [reply app/helpers/general-date.js:12]: Conclution tz : '' returns false
