### PR TITLE
fix: Virtual Events: Further enhance design and video tab page

### LINKED ISSUE #6005: Virtual Events: Further enhance design and in page details of organizer video tab page
Please change the organizer video tab details as follows:

**Tables**

* Match the width of both tables to the width of the box "This feature is still in alpha stage"

**Table Headings**

* Rename Video Room -> Video Source URL
* Rename Link -> Join Video
* Rename heading "Pin" to "Room Password" on both tables
* Rename heading "Pin" to "Room Password" on the specific session video page
* Ensure that "Pin" is also showing up as "Room Password" on the public event page for ticket holders

**Table Columns and Content**

* Extend colum Event/Microlocation and make video room  URL column smaller a bit
* Change URL in Video room URL to display only a limited number of characters that fit onto one line without https, e.g. meet.jit.si/eventyay/a315169f-stream...
* In the link column implement a box of the link that is not editable similar to the "copy link box" of the Call for Speakers using a _gray_ button. Keep the link "linkified" and open the link in a new tab
Screenshot from 2020-12-11 20-56-27
* Reduce the width of the column "Link" a bit and expand the column "Additional Information" in exchange a bit

### PR DESCRIPTION
**Pull request by daretobedifferent18**
Fixes #6005 

#### Short description of what this resolves:
Change the organizer video tab details

#### Changes proposed in this pull request:
- Tables
  - [x] Match the width of both tables to the width of the box "This feature is still in alpha stage"

- Table Headings
  - [x] Rename Video Room -> Video Source URL
  - [x] Rename Link -> Join Video
  - [x] Rename heading "Pin" to "Room Password" on both tables
  - [x] Rename heading "Pin" to "Room Password" on the specific session video page
  - [x] Ensure that "Pin" is also showing up as "Room Password" on the public event page for ticket holders

- Table Columns and Content
  - [x] Extend colum Event/Microlocation and make video room URL column smaller a bit
  - [x] Change URL in Video room URL to display only a limited number of characters that fit onto one line without https, e.g. meet.jit.si/eventyay/a315169f-stream...
  - [x] In the link column implement a box of the link that is not editable similar to the "copy link box" of the Call for Speakers using a gray button. Keep the link "linkified" and open the link in a new tab

#### ScreenShot
Screenshot from 2020-12-12 19-48-17

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] The acceptance, integration, unit tests and linter pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by daretobedifferent18** [comment]
@mariobehling Pls have a look

**Comment by mariobehling** [comment]
Good job. 

The "Open/Copy" button is missing the "Copy" feature. We need both:
* the feature to copy the URL to access the event room
* the feature to open the URL in a new tab

**Comment by mariobehling** [comment]
Please also compare the wizard step 5 Call for Speakers private link to understand the required feature better.

**Comment by mariobehling** [comment]
In your previous PR I missed the point that you also changed all tables on all pages to come with a blue line now. This results in the blue line being very dominant on pages. Whereas: There is no reason to change the color on other pages except the video page. Please revert this specific change in the follow up PR.

E.g. sponsors box suddenly stands out on the dashboard with a dominant blue line. This is not desired.

Screenshot from 2020-12-12 11-38-33

**Comment by mariobehling** [comment]
As the position of the button "Add Room" has changed the first heading "Event Video Room" now looks stuck together with the above message. Therefore please add some spacing between the "Alpha" message and the heading.

**Comment by daretobedifferent18** [comment]
> Good job.
> 
> The "Open/Copy" button is missing the "Copy" feature. We need both:
> 
>     * the feature to copy the URL to access the event room
> 
>     * the feature to open the URL in a new tab

So I need to implement same as that for call for speaker? Just to add linkified to make it as a link.

**Comment by mariobehling** [comment]
> > Good job.
> > The "Open/Copy" button is missing the "Copy" feature. We need both:
> > ```
> > * the feature to copy the URL to access the event room
> > 
> > * the feature to open the URL in a new tab
> > ```
> 
> So I need to implement same as that for call for speaker? Just to add linkified to make it as a link.

There are different ways to solve this. I can imagine the following works well:
1. link box (not editable) and with copy button the right similar to Call for speakers.
2. Next to it on the right a button "Open". This button could also use an icon like the below one or something similar.
Screenshot from 2020-12-12 14-15-40

**Comment by daretobedifferent18** [comment]
@mariobehling Done all the changes. Pls review

**Review by mariobehling — APPROVED** [review]
Thank you. Looks good to me and I can test this UI with some users. Cheers!

File: app/components/ui-table/cell/events/view/videoroom/cell-video-url.js [hunk 1]
```diff
@@ -1,5 +1,15 @@
...
+import { computed } from '@ember/object';
 
 @classic
-export default class CellVideoUrl extends Component {}
+export default class CellVideoUrl extends Component {
+  @computed
+  get shortUrl() {
+    let url = this.record.replace('https://', '').replace('www.', '');
+    if (url.length > 37) {
+      url = url.slice(0, 36) + ' . . .';
```
Comment (iamareebjamal) [inline app/components/ui-table/cell/events/view/videoroom/cell-video-url.js:11]: It'll be better if you use CSS for truncating

https://daily-dev-tips.com/posts/css-truncate-text-with-ellipsis/

There must be a class in semantic UI already

File: app/controllers/events/view/tickets/attendees/list.js [hunk 2]
```diff
@@ -3,7 +3,6 @@ import { action } from '@ember/object';
 import EmberTableControllerMixin from 'open-event-frontend/mixins/ember-table-controller';
 import moment from 'moment';
 
-
```
Comment (iamareebjamal) [inline app/controllers/events/view/tickets/attendees/list.js:6]: Revert

File: app/templates/events/view/videoroom/list.hbs [hunk 3]
```diff
@@ -1,4 +1,4 @@
-<div class="ui warning message">
+<div class="ui warning message" style="margin: 1rem -1rem 2rem -1rem;">
```
Comment (iamareebjamal) [inline app/templates/events/view/videoroom/list.hbs:1]: Please use helper classes like mb-, m-, mt-

**Comment by daretobedifferent18** [comment]
@iamareebjamal Done

File: app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js [hunk 4]
```diff
@@ -0,0 +1,11 @@
+import classic from 'ember-classic-decorator';
+import Component from '@ember/component';
+import { computed } from '@ember/object';
+
+@classic
```
Comment (iamareebjamal) [inline app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js:5]: Use non classic component

File: app/extensions/ember-table/template.hbs [hunk 5]
```diff
@@ -1,5 +1,5 @@
 
-<table class="ui unstackable table {{or @tableColor 'blue'}}">
+<table class="ui unstackable table {{@tableColor}}">
```
Comment (iamareebjamal) [inline app/extensions/ember-table/template.hbs:2]: Won't this apply blue to all tables?

Comment (daretobedifferent18) [reply app/extensions/ember-table/template.hbs:2]: No

Comment (daretobedifferent18) [reply app/extensions/ember-table/template.hbs:2]: bcz we have to color in Default for getting color on top of table and that is past only in case of videoroom/list

File: app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js [hunk 6]
```diff
@@ -0,0 +1,9 @@
+import Component from '@ember/component';
```
Comment (iamareebjamal) [inline app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js:1]: glimmer component

File: app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js [hunk 7]
```diff
@@ -0,0 +1,9 @@
...
+import { computed } from '@ember/object';
+
+export default class CellStreamUrl extends Component {
+    @computed
```
Comment (iamareebjamal) [inline app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js:5]: Indentation

Comment (iamareebjamal) [inline app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js:5]: No need of computed here

File: app/extensions/ember-table/template.hbs (hunk 5 above)
Comment (iamareebjamal) [reply app/extensions/ember-table/template.hbs:2]: Sorry, I was seeing before part of the diff

File: app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js [hunk 8]
```diff
@@ -0,0 +1,8 @@
+import Component from '@glimmer/component';
+
+export default class CellStreamUrl extends Component {
+  @computed
```
Comment (iamareebjamal) [inline app/components/ui-table/cell/events/view/videoroom/cell-stream-url.js:4]: Not needed

File: app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs [hunk 9]
```diff
@@ -1,3 +1,19 @@
 {{#if @record}}
-  <a class="mt-2" href="{{href-to 'public.stream.view' (or @extraRecords.identifier @extraRecords.event.identifier) @record.slugName @record}}" target="_blank" rel="noopener">{{t 'Open'}}</a>
+  <div class="ui action input fluid">
+    <input type="text" name="private_link" value={{concat this.host '/e/' (or @extraRecords.identifier @extraRecords.event.identifier) '/video/' @record.slugName '/' @record.id}} placeholder={{concat this.host '/e/' (or @extraRecords.identifier @extraRecords.event.identifier) '/video/' @record.slugName '/' @record.id}} readonly>
+    <UiPopup @on="click" @content={{t "Link copied to clipboard"}} @position="bottom right">
+      <CopyButton @clipboardText={{concat this.host '/e/' (or @extraRecords.identifier @extraRecords.event.identifier) '/video/' @record.slugName '/' @record.id}} @class="ui black right labeled icon copy button">
```
Comment (iamareebjamal) [inline app/templates/components/ui-table/cell/events/view/videoroom/cell-stream-url.hbs:5]: Repeating logic. Please create a computed property in component and put `concat this.host '/e/' (or @extraRecords.identifier @extraRecords.event.identifier) '/video/' @record.slugName '/' @record.id}} placeholder={{concat this.host '/e/' (or @extraRecords.identifier @extraRecords.event.identifier) '/video/' @record.slugName '/' @record.id` there

**Review by iamareebjamal — DISMISSED** [review]

**Comment by iamareebjamal** [comment]
Test failing

**Comment by daretobedifferent18** [comment]
> Test failing

I am not getting first test of cell-stream-url is failing

File: tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-url-test.ts [hunk 10]
```diff
@@ -7,11 +7,30 @@ module('Integration | Component | ui-table/cell/events/view/videoroom/cell-strea
   setupRenderingTest(hooks);
 
   test('it renders', async function(assert) {
-    this.set('record', { id: 23, name: 'Main Hall', slugName: 'main-hall' });
-    this.set('extraRecords', { event: { identifier: 'abcd' } });
+    this.set('record', { get(dataType: string) {
```
Comment (iamareebjamal) [inline tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-url-test.ts:10]: Instead, you can use EmberObject.create

Comment (daretobedifferent18) [reply tests/integration/components/ui-table/cell/events/view/videoroom/cell-stream-url-test.ts:10]: its showing same error if I use EmberObject.create
